### ISSUE TITLE
Create new discussion hub for real-time ddev-specific communication (replace CMS-specific slacks)

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#3383] opened 2021-11-18 16:44 UTC
**Is your feature request related to a problem? Please describe.**

Spinoff discussion from #2057 

@rfay 
> It would be great to have a unified place for communication and support for DDEV. Perhaps try to get people to move to a new DDEV slack org. That way the various CMS communities, especially TYPO3 and Drupal, could share their expertise and experience.

@Lefaux
> I would advise against using Slack for a new community hub.
Slack is a temporary solution because once the community becomes too big, Slack will ask you to move off their platform eventually.
> 
> We're currently in planning phase to get 8k people off Slack and I have to say... it's not pretty :)

@ekl1773
> I'm biased, but you could use Mattermost. Happy to help make that happen if it would be the right fit :)
> 
> https://docs.mattermost.com/about/subscription.html#do-you-have-a-program-for-official-non-profits-open-source-projects-and-charities

@andy-blum 
>  I'd be extremely hesitant to move away from slack. It's the de facto hub for distributed async discussion and I know that I wouldn't likely keep a new chat application open when my agency chat, client chat, and open source communities chat are all already on slack.

**Comment by rfay** [comment] 2021-11-18 16:58
Thanks!

* Slack might work for us for the time being (a new DDEV slack), but I sure do have enough slacks already.
* Discord: Lots of open-source projects like discord. I haven't come to terms with it yet.
* Gitter: We've had a space on [gitter.im](https://gitter.im/drud/ddev) for ages, but it hasn't gotten any traction. Easy to use. Poor threading, etc.

We need to think about what our actual priorities are. Some I can think of:

* Needs to be inexpensive or free, the project doesn't need new expenses.
* Preferably familiar to people, so they'll use it.
* We'd like to consolidate all users into one platform, instead of having so many
* Integration with github is a plus (show issues, PRs, etc.)

**Comment by andy-blum** [comment] 2021-11-18 17:00
It might be good to get a few acceptable solutions together here and then put out feelers in the CMS-specific communities?

**Comment by deviantintegral** [comment] 2021-11-18 17:36
> Discord: Lots of open-source projects like discord.

The nice thing about Discord is it's a single account, whereas with Slack each instance is a separate set of credentials. Their business model also may be a better fit, in that instead of a central org handling billing, individual users can pay for additional features. It's been reasonable enough for me as a user in the Home Assistant instance.

I noticed that [discussions](https://github.com/drud/ddev/discussions) are available but relatively quiet. While I still think there's a need for real-time chat, perhaps the problem space becomes simpler if we encourage the community to use Discussions first.

**Comment by BrianGilbert** [comment] 2021-11-18 21:22
Discord also has what I consider the best voice, video, and screen sharing capabilities

I use to manage the various systems in a single interface https://getferdi.com/

**Comment by rfay** [comment] 2021-11-19 00:17
@deviantintegral I agree that Github Discussions has promise, but I haven't much liked it so far. I'd actually be fine with putting everything in github issues. The problem is... not everybody follows or participates in those, so it's good for *me* to give support, but a platform like slack or discord is much more likely to get a community involved. I know that in another world where everybody subscribed to all github discussions we'd do fine with it, but it doesn't seem to work right now. I was thinking about turning it off.

**Comment by rfay** [comment] 2021-11-19 00:17
So @BrianGilbert ferdi will combine slack and discord and all?

**Comment by BrianGilbert** [comment] 2021-11-19 11:17
> So @BrianGilbert ferdi will combine slack and discord and all?

@rfay Yes... Slack, Discord, and a plethora of other services in a single app.  

226 of them in all, plus you can create custom ones for any app you need that has a URL!

**Comment by rfay** [comment] 2021-11-22 19:14
IMO we should start moving to discord, without cutting anything off at this time. 

I welcome everybody to https://discord.com/channels/664580571770388500/689166305315520541

I also created a `#typo3`, `#drupal`, `#laravel`, `#magento` and `#shopware` channels there, hope to teach people to use those for CMS-specific things.

**Comment by andy-blum** [comment] 2021-11-22 19:25
@rfay that link isn't directing me to the ddev discord server.

**Comment by rfay** [comment] 2021-11-22 19:26
How about this? https://discord.gg/x9srMwSH

**Comment by Lefaux** [comment] 2021-11-22 19:47
want me to ask our partnermanager to get the server „official“ via fast track or do you want to get there organically?

**Comment by rfay** [comment] 2021-11-22 19:58
Not sure we have to move fast on it. Let's see if we can do it organically at first. A few things to get used to at this point.

**Comment by rpkoller** [comment] 2021-11-23 19:11
great idea. and one suggestion it might perhaps ben idea to provide OS specific text channels like ddev-linux, ddev-macos and ddev-windows for os specific support requests and discussions as well?

**Comment by andy-blum** [comment] 2021-11-23 19:14
Mentioned this Randy yesterday. His response: 

> My preference is to not have OS-specific channels. In general, DDEV works the same everywhere. As for CMS-specific channels, I put a note on them suggesting that they mostly get used only when something is really specific to that CMS, which it usually isn't.

**Comment by rpkoller** [comment] 2021-11-23 19:23
ah that makes sense, thanks for the heads-up @andy-blum

**Comment by mkalkbrenner** [comment] 2021-11-24 10:21
I don't like Slack. But I don't like Discord, too.
In general it is a pain to have multiple chat solutions running in parallel.

**Comment by WarpedOne** [comment] 2021-11-25 01:04
Discord is planning on removing public access to their message API, only allowing it for top verified bots. https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-for-Verified-Bots

**Comment by andy-blum** [comment] 2021-11-25 01:10
@WarpedOne I don't think that's an issue.

> This change applies only to verified bots and apps, which means those that are in 75 or more servers.

**Comment by WarpedOne** [comment] 2021-11-25 02:20
many eatures. When Drupal moved to  issues, but it also means you can lose some along the way who aren't interested in yet another platform. Matrix was designed to combine platforms into a more unified structure. Using bridges, you can still communicate with IRC, Slack, Telegram and other platforms without needing to login to all of them thru their apps with a variety of UIs and features. When Drupal moved to Slack, many people remained on IRC, but there were rarely any responses to the occaisional question that popped up there.

**Comment by WarpedOne** [comment] 2021-11-27 11:40
Read the "WHAT WILL AN UNAPPROVED BOT LOSE ACCESS TO?" section.

**Comment by rfay** [comment] 2021-12-08 15:11
Calling this done. We still have to encourage people to move over from the other places. 

Discord is at https://discord.gg/kDvSFBSZfs

**Closed by rfay** 2021-12-08 15:11 UTC
