### ISSUE TITLE
Regression: ddev v1.5.0 lost the docker "cached" mount feature, slowing considerably (macOS only)

### ISSUE THREAD

**Issue by phifa** [drud/ddev#1352] opened 2018-12-21 22:48 UTC
Everything is really slow on my Mac. TYPO3 Frontend and Backend take at least 10 seconds to load. You cannot really work with it. The same project on a Windows Machine is super fast. 

MacBook Pro (Retina 13 Zoll, Anfang 2013)
2,6 GHz Intel Core i5
8 GB 1600 MHz DDR3
SSD Drive 256 GB  / 50 GB free
Mac OS Mojave. 

Question: How can I debug this? 

Here is my config file: 

```
APIVersion: v1.4.1
name: myproject
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
# This config.yaml was created with ddev version v1.4.1
# webimage: drud/ddev-webserver:v1.4.0
# dbimage: drud/ddev-dbserver:v1.4.0
# dbaimage: drud/phpmyadmin:v1.4.0
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.local and https://projectname.ddev.local

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.1"  # PHP version to use, "5.6", "7.0", "7.1", "7.2"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"

# webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

additional_hostnames:
  - myproject2
# would provide http and https URLs for "somename.ddev.local"
# and "someothername.ddev.local".

# additional_fqdns:
#  - example.com
#  - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# upload_dir: custom/upload/dir
# would set the destination path for ddev import-files to custom/upload/dir.

# working_dir:
#   web: /var/www/html
#   db: /home
# would set the default working directory for the web and db services.
# These values specify the destination directory for ddev ssh and the
# directory in which commands passed into ddev exec are run.

# omit_containers: ["dba", "ddev-ssh-agent"]
# would omit the dba (phpMyAdmin) and ddev-ssh-agent containers. Currently
# only those two containers can be omitted here.

# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks after the ddev command is
# executed.
# See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:

```

**Comment by rfay** [comment] 2018-12-21 22:50
You're saying it's faster with ddev on Windows? I've never ever heard that before. Windows is normally significantly slower.

Please reset your docker to factory defaults and see what happens. You can do that safely if you don't have any non-ddev containers or volumes you're counting on.

**Comment by phifa** [comment] 2018-12-21 23:00
OK, now first thing that happens: 
`ERROR: for ddev-myproject-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /Applications/MAMP/myproject/.ddev/import-db` 

So what I did last time to get rid of the message, is add the folder to the shared folders in docker. Is this correct?

**Comment by rfay** [comment] 2018-12-21 23:02
Docker and nearly every other tool assumes that you put a project directory in your home directory. 

But if you really want to run things out in the /Applications area (highly discouraged, that's not the way it should work for many reasons) then you'll have to share /Applications in file sharing in your docker config.

**Comment by phifa** [comment] 2018-12-21 23:12
OK, set up a new project in `~/projects/myProject`. No binding errors, but still super slow. I am running DDEV 1.5.0. How can I debug this? How can I find out where the bottleneck is between docker and DDEV?

**Comment by rfay** [comment] 2018-12-21 23:16
Could you please set up a simple basic TYPO3 project using composer (if that's not what you've already done)? https://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart

See what that does. 

Your config.yaml posted earlier showed ddev v1.4.1, so if you've upgraded, you'll want to just run `ddev config`. 

I'd recommend temporarily turning off any virus checker or firewall that you might have going, and just as a regular paranoid step, reboot your machine.

Like I say I have never ever seen a Windows machine faster than Mac.

**Comment by rfay** [comment] 2018-12-21 23:37
This is just a regular filesystem on a regular mac right?  You say "SSD Flash Drive 256 GB" but I assume you just mean it's on a regular SSD, not on a flash drive. If it's on a flash drive that's never going to work out.

**Comment by phifa** [comment] 2018-12-21 23:50
> Could you please set up a simple basic TYPO3 project using composer (if that's not what you've already done)? https://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart
I did just that: https://streamable.com/05jzs 

> This is just a regular filesystem on a regular mac right? 
Yes, regular filesystem, nothing fancy. It's a SSD, correct.

**Comment by rfay** [comment] 2018-12-21 23:54
Looks painful! A 2013 mac is getting old of course, but I used a 2013 MacBook Air until recently.   I assume your Windows machine was newer.

You are welcome to try out the webcache feature we just introduced, https://www.drud.com/ddev-local/ddev-locals-new-webcache-feature/ - you might be really happy with it. 

But I do wish we knew what was going on for you.

Oh, you don't say... but you're using Docker-for-Mac right? Not Docker Toolbox? Could you give a `ddev version` please?

**Comment by micnap** [comment] 2018-12-22 05:59
I am having the same issue - every page load is slow as molasses.  The Drupal 8 install was painfully slow - 20+ minutes.  Once installed, page loads are taking 6-8 seconds each.  Drupal 8 running on MAMP Pro with no caching is snappy.  

I'm also on a 2013 Mac but it is still blazing fast with most other operations.

2.8 GHz Intel Core i7
16 GB DDR3 memory
750 GB SSD with about half free

Docker was installed via the Docker for Mac dmg.

My config file (everything else in the file is commented out):
APIVersion: v1.5.0
name: probirt.d8.local
type: drupal8
docroot: web
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default

Otherwise, getting up and running with ddev was a dream.  I'm hoping I can get this resolved so that I can actually be productive with it.

**Comment by phifa** [comment] 2018-12-22 08:11
> Oh, you don't say... but you're using Docker-for-Mac right? Not Docker Toolbox? Could you give a ddev version please?

It's just the normal Mac installer, Docker Desktop Community. 
It is set to Factory Reset, docker settings not changed. 

<img width="696" alt="docker" src="https://user-images.githubusercontent.com/3061129/50372126-dbc17e80-05c8-11e9-832e-251f04431b44.png">


```
$ ~/projects/my-typo3-site> ddev version
bgsync        		drud/ddev-bgsync:v1.5.0
cli	          	v1.5.0
commit        		v1.5.0
db            		drud/ddev-dbserver:v1.5.0-10.2
dba           		drud/phpmyadmin:v1.5.0
ddev-ssh-agent		drud/ddev-ssh-agent:v1.5.0
docker        		18.09.0
docker-compose		1.23.2
domain        		ddev.local
router        		drud/ddev-router:v1.5.0
web           		drud/ddev-webserver:v1.5.0
```

I used the guide here to set up a basic TYPO3 example page: 
https://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart 

I used the installer script to install DDEV: 
https://ddev.readthedocs.io/en/latest/#installationupgrade-script-linux-and-macos

**Comment by micnap** [comment] 2018-12-22 15:12
Docker Desktop and ddev version exactly the same as OP:

<img width="596" alt="screen shot 2018-12-22 at 10 09 04 am" src="https://user-images.githubusercontent.com/659979/50375826-b4bb7a80-05d1-11e9-8841-5b2bb43e3ff8.png">

<img width="360" alt="screen shot 2018-12-22 at 10 08 54 am" src="https://user-images.githubusercontent.com/659979/50375827-bdac4c00-05d1-11e9-932d-4a6e9499a80c.png">

Also used the same install but for Drupal 8:
https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart

I used the homebrew install:
https://ddev.readthedocs.io/en/latest/#homebrew-macos

**Comment by micnap** [comment] 2018-12-22 20:19
That's about right for installing Drupal on MAMP for me - the 7ish minutes.  The Drupal install on ddev was 3 times that though.  Either way, I can live with 20 minutes installs as it's not something I need to do everyday.  But 10 second page loads makes it pretty unusual for daily development.  Hoping you can reproduce with your 2013 MBP.

**Comment by rfay** [comment] 2018-12-22 22:37
Hope you'll try the webcache_enabled while you're at it as well, would love to know how it works for you. @micnap you did try resetting docker to factory defaults?

**Comment by MrPaulDriver** [comment] 2018-12-23 21:05
Just adding that I too am finding performance quite slow on a 2013 i7 MBP. 

I also have DDEV running on a Ubuntu 18.04 machine with almost identical CPU and likewise 16GB memory and I am finding the difference between the two setups to be very noticeable. 

I understand there are file access issues with Docker on Mac and Windows versus Linux, but this issue make me wonder if something else might be in play.

**Comment by rfay** [comment] 2018-12-23 21:09
Linux is crazy faster, always. Linux is massively faster even when running in a *virtual machine* on MacOS :) So that's not a good comparison. But I do wonder what might be going on, and if it's only on older macs. I'll get out the 2013 MBP we have and relieve it from its testbot duties hopefully later today.

**Comment by rfay** [comment] 2018-12-23 21:14
Oh, Could each of you please update your reports to include the filesystem you're using? People who have reinstalled recently have APFS. If you have "MacOS Extended", that could be a significant difference. And I remember that Docker made a major change in behavior when APFS came along.

**Comment by MrPaulDriver** [comment] 2018-12-23 21:38
APFS

**Comment by rfay** [comment] 2018-12-23 21:40
Oh, interesting, I note that this MBP2013 (tests still in progress) is still High Sierra, so that gives us a little opportunity to see if that's what has happened here.

**Comment by MrPaulDriver** [comment] 2018-12-23 21:58
I should say that I just bought this (used) MBP only a few days ago. So it has a brand new install of High Sierra.

<img width="895" alt="screen shot 2018-12-23 at 21 56 32" src="https://user-images.githubusercontent.com/3405783/50387834-d6198500-06fd-11e9-9411-5c78b09fd588.png">

**Comment by rfay** [comment] 2018-12-24 00:52
Here's what I see on our MBP 2013, it's pretty painful, I'll admit. Note that after poking around, I turned on `webcache_enabled: true` to show you the result. It's mighty nice. It *is experimental* as explained in the [blog post](https://www.drud.com/ddev-local/ddev-locals-new-webcache-feature/)

<iframe width=948 height=712 frameborder="0" scrolling="no" src="https://screencast-o-matic.com/embed?sc=cFlZcErMFT&v=5&ff=1" allowfullscreen="true"></iframe>

**Comment by micnap** [comment] 2018-12-24 03:30
Woot!  That did it for me.  webcache_enabled set to true makes it load quickly like I'm used to.

For reference, I'm also on Sierra (10.12.5) and my file system is Logical Volume.  

THANK YOU!

**Comment by rfay** [comment] 2018-12-24 04:02
It's super nice, but be watching carefully. 2-way sync like this is experimental, but the feeling is fantastic, isn't it. Please, if you have any problems with it, let us know what happened and please try hard to figure out if you can recreate it. For example, if I bring up a project and then suddenly rm -r the entire vendor directory, it will in fact break the syncing, and I might even have to `composer install` as a result.

**Comment by MrPaulDriver** [comment] 2018-12-24 09:56
Wow. I installed the Droopler distribution, which has quite a number of modules enabled. Loading the module page without webcache took an average 15 seconds. With webcache, about 1.6 seconds.

Regarding your comment above Randy. Would 'ddev remove' protect against your example of how syncing might get broken?

**Comment by rfay** [comment] 2018-12-24 13:37
So `ddev rm` and `ddev start` is pretty much a cure for putting anything on the host that ought to be in the container, easy recovery if something does go wrong. The problem is if something important happens in the container and doesn't get properly propagated back to the host. In that case, the contents of the host will not be fully consistent.  So for example, if you do a massive `ddev composer remove`, which removes all kinds of things from vendor inside the container, and then syncing fails during that process, the result won't make it onto the host, and then the remove/start combination wont help.  Another example, although less likely, would be a webserver activity (uploading files?) that changed a lot of stuff and then syncing failed. It would never make it back onto the host. 

Mostly when you do something on the host, you're doing it on purpose, and it doesn't matter if it somehow doesn't reach consistency inside the container; in that case remove/push is a total solution.

`ddev logs -s bgsync -f` is fascinating (for a little while) and will tell you what's actually going on.

**Comment by phifa** [comment] 2018-12-31 05:36
`webcache_enabled: true` helped me too. still weird though, that the only the mbp2013 has issues here.

**Comment by MrPaulDriver** [comment] 2019-01-02 12:45
Is this so? No issues with later Macs

**Comment by rfay** [comment] 2019-01-02 15:14
I did some study on this and found that in ddev v1.5.0 we had a performance regression related to how we mount the code into the docker container. I think you'll find that v1.4.1 performs better for you, and we'll try to get a v1.5.1 solving this problem in your hands pretty soon.

**Comment by alexfinnarn** [comment] 2019-01-02 15:56
@rfay I'm upgrading to 1.5.0 now and testing out the web caching feature in hopes of finally getting over the Mac OS Docker file mounting issues that have kept me from using Docker-based dev solutions on large projects, but is there a way I can add this line somewhere until 1.5.1 is released? 

Since it's just a small change, I'd like to see how it adds to the performance difference between 1.4.1 and 1.5.0.

I installed/updated via Homebrew and I see the `ddev.rb` file but I've never tried messing with Homebrew outside of that process.

**Comment by alexfinnarn** [comment] 2019-01-02 15:59
So with web caching enabled in my test of a clean `admin/config` after clearing cache on a D7 site went from 12 - 15 second response to 4 - 5 second response. Very cool and satisfying for now!

**Comment by rfay** [comment] 2019-01-02 16:41
Yes, I find it very satisfying as well. There's more detail at https://www.drud.com/ddev-local/ddev-locals-new-webcache-feature/ if you haven't read/watched that; there are caveats there for you; it's an experimental feature and we want to hear your results and any problems you have.

**Comment by kaystrobach** [comment] 2019-01-03 08:57
@rfay also slow on my 2018 mbp will try webcache. Have you considered selective caching? Means that only some folders (like vendor) are cached and others are still bin mounted? 

If this is configurable it would make live a lot easier 😉 and ddev faster as well.

**Comment by MrPaulDriver** [comment] 2019-01-03 12:21
Selective caching? This sounds interesting.

One problem I am finding with webcache_enabled is when theming with a browser refresh tool like BrowserSync. Such applications watch scss/css/js files for changes and automatically reload the browser for previewing after a change is detected. As well as BrowserSync there are similar others, including LIve Reload and Prepros

BrowserSync not seem to notice file changes on the host immediately and it seems necessary save a file twice, which breaks the workflow.

In https://github.com/drud/ddev/issues/1363#issuecomment-451101716 @kaystrobach seems to be seeing something similar.

**Comment by kaystrobach** [comment] 2019-01-03 12:46
Yes, changing files with webcache enabled does not seem to trigger the sync always. But selective caching would speed up work a lot.

And as written in #1363 i would prefer using rsync instead of plain old dumb copy which is slow and resource intensive.

**Comment by rfay** [comment] 2019-01-03 21:59
Thank you all so much for your patience. The issue here was basically one line that was missing in v1.5.0, massively affecting (only) macOS. [v1.5.1 is out](https://github.com/drud/ddev/releases/tag/v1.5.1) - Could you please try it?

I pulled out the 2013 MBP and got a Drupal 8 web install in 2:40 instead of the 10:00 that v1.5.0 had on that machine. I think you'll be happier now. Again, thanks for your patience in pursuing this and helping me to understand the severity of the problem. I have a pretty fast mac (and was also working on Windows) and was also so focused on the webcache feature that I missed the regression.

For those of you now hooked on webcache_enabled: Please report in other issues (or new ones). If you possibly can, please try to recreate specific issues. If a particular file doesn't show up in a particular context, please see if you can ssh in and use "touch" to recreate the problem if it's a container-initiated file, or use "touch" on the host if it's host-initiated. If you can use `ddev logs -s bgsync -f` to see any misbehavior when you go that, it helps enormously. And if there's any "big" thing that you did before the misbehavior, please help me try to do your big thing.

**Comment by kaystrobach** [comment] 2019-01-04 10:33
same here

**Comment by rfay** [comment] 2019-01-04 15:00
Fixed in https://github.com/drud/ddev/pull/1361 - thanks all!

**Comment by phifa** [comment] 2019-01-05 11:10
@rfay what?

**Comment by rfay** [comment] 2019-01-05 15:04
Hmm, I thought both of you were reporting success. It's 4 times as fast as 1.5.0 on things like a D8 install. The regression was clear.

**Comment by kaystrobach** [comment] 2019-01-05 16:41
Mhmm one project was still slow - another one got faster - need to investigate that further.

@phifa can you check 1.5.1 after ddev config?

**Comment by rfay** [comment] 2019-01-05 16:49
Please make sure you've done `ddev rm` and `ddev start` again; I'm sure you have. And do just one project up at a time. 

The one-line key issue is in .ddev/docker-compose.yaml, you should see `consistency: cached`. 

```
  web:
    container_name: ddev-${DDEV_SITENAME}-web
    image: $DDEV_WEBIMAGE
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: ../
        target: /var/www/html

        consistency: cached
```

**Comment by kaystrobach** [comment] 2019-01-07 12:50
it seems to work now - strange ... maybe docker cached needs some time to optimize requests

anyway i would like to specify webcache very granuarly ... this could massively speed things up ...

**Comment by alexfinnarn** [comment] 2019-01-07 14:30
I too was thinking about a granular webcache since I'm only currently working with a few files that will change after booting up, but the project root and all it's child directories amounts to 12,000+ files.

```
webcache_enabled: true
# Fill in if you want more granular control, ex. "./i-only/work-in/this-dir"
webcache_directories: "./"
```
I'd like to see something like that where you specify the files you care about syncing and the default is all of them...and I think all files in the root are being "webcached" currently if you enable that flag?

I don't know enough about the `docker-compose.yml` file of where to do that, but I can test out something in a branch or config file change.

**Comment by phifa** [comment] 2019-01-07 14:34
@kaystrobach @rfay now it looks good after ddev rm. Thanks!

**Comment by rfay** [comment] 2019-01-07 18:58
I experienced what you two did today; I'm using MBP2013 because my regular laptop is in the shop. I started up and installed a fresh D8 composer build and it was previous-horrible slow. Then after some combination of ddev rm and docker restart it's normal again. Baffled how that could be.

**Comment by rfay** [comment] 2019-01-14 18:34
Calling this fixed now as it seems to have gotten sorted out.

**Closed by rfay** 2019-01-14 18:34 UTC
