### ISSUE TITLE
TYPO3 and ddev 1.19.3 and Docker Desktop 4.9.0 does not work on Linux Mint 20.3

### ISSUE THREAD

**Issue by dbunkerd** [drud/ddev#3893] opened 2022-06-07 05:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

After and upgrade from Docker Desktop 4.8.2 to 4.9.0 this morning, all TYPO3 projects stopped working. The TYPO3 Backend becomes unusable.

Downgrade to Docker 4.8.2 solved the problem.

### Current Behavior

**TYPO3 logs the following error:**
`The temporary cache file "/var/www/html/typo3temp/var/cache/data/l10n/xxxx.temp" could not be written.`
This absolute path is (of course) out of ddev's reach.

### Expected Behavior

An absolute path is not to be used.
It was not defined by me in config.yaml

### Anything else?

After some testing on other machines, I came to the conclusion that Docker Desktop 4.9.0 must be buggy. For example on a Macbook M1 the Docker Dashboard is completely empty (plain white) as long as ddev is running. After a ddev poweroff, Docker Dashboard is normal again with its usual content.

### Requested gists

[ with Docker Desktop 4.8.2](https://gist.github.com/dbunkerd/8afbf727914576637c7f70f31cc2945f)
[ with Docker Deskop 4.9.0](https://gist.github.com/dbunkerd/9808dda94230995c139244bdb1ba37ff)
[ with Docker engine version 20.10.17](https://gist.github.com/dbunkerd/b2fb8c20d6d373f639e7ae9787a1d1ab)

**Comment by rfay** [comment] 2022-06-07 12:40
Hi @dbunkerd - When you were creating the issue you were requested to do a `ddev debug test` and put it in a gist; that gives me lots of information about your environment.  Could you please do that? You can edit the issue and add the link.

There are lots of issues reported with Docker Desktop 4.8.2 and 4.9.0 - Most of them are related to turning on experimental settings. Do you have any experimental settings turned on?

I imagine you have a `docker-compose.*.yaml` which puts a special tmpfs on your TYPO3 projects? What happens if you remove that?

**Comment by rfay** [comment] 2022-06-07 12:53
Oh, you're using Docker Desktop for Linux? You're probably the first person I've heard of that's doing that. I haven't tried it. How long have you been using it? 

I would probably recommend using the normal Linux Docker Engine, using the regular instructions.  Docker on Linux is really, really predictable and stable. Docker Desktop on all platforms has trouble with every single release.

**Comment by dbunkerd** [comment] 2022-06-07 23:11
Hi @rfay 
thanks for your quick reply. I am using Docker Desktop for Linux, because I also use it with Windows and on a Macbook M1. But I've followed your advice and purged Docker Desktop on Linux and used Docker Engine instead. Everything is fine now.

Please find the requested gists for all three scenarios in my original issue.

**Comment by rfay** [comment] 2022-06-07 23:34
The `docker-compose.*.yaml` files are part of your project - you added them. (I'm not talking about `.ddev-docker-compose*`, but rather about `docker-compose.*.yaml`, which is commonly used to set the var directory on typo3.

You may want to open an issue with the Docker folks if you can pin this down and you're interested. https://github.com/docker/desktop-linux/issues

Thanks for the gists. You can't imagine how much those help me. Dozens of questions I then don't have to ask, back-and-forth.

I note that the plain-vanilla project that `ddev debug test` created on Docker Desktop 4.9.0 was fine, so I imagine the problem is that mounting a tmpfs volume on your var/tmp (which lots of people do in TYPO3-land) is the problem. That should be easy to check and easy to replicate for an issue over in the Docker Desktop for Linux issue queue.

I'm going to close this as it doesn't seem to have anything to do with ddev, but happy to continue the conversation here or elsewhere.

**Closed by rfay** 2022-06-07 23:34 UTC
