### ISSUE TITLE
Performance: Repeat manual tests of ddev and related dev competitors

### ISSUE THREAD

**Issue by rfay** [drud/ddev#257] opened 2017-05-23 14:03 UTC
## What happened (or feature request):

@tannerjfco did a quick survey of performance for a number of dev tools including Kalabox some time ago. One of the first thing we need to do in evaluating ddev's performance is to repeat that manual evaluation and get both some numbers *and* a basic subjective feel about where we are. 

Although we've proposed long-term tracking of our performance against other tools, this simple manual technique and "feel" test should tell us more short-term about where we're at than a lot of fancy tools and instrumentation. 

Key tests:
* How long does it take to get or other environments installed?
* How long does it take to get a site set up?
* How is the page-serving performance? Is it something a dev would endure?

Although this is a simple entry point, the technique should be documented so that it's repeatable, and the results should be documented in a place where they can be revisited and hopefully be useful against future attempts.

## Related source links or issues:

**Comment by rickmanelius** [comment] 2017-05-23 16:16
@tannerjfco Can you link your previous audit here?

**Comment by rickmanelius** [comment] 2017-05-23 21:43
In addition to the subjective feel and objective results, I'd put a final request:

* Provide recommendations (if any) to improve performance based on what was learned from this follow-up set of tests.

With that said. I feel this is actionable, but feel free to re-tag it as incubate if the size/scope is still debatable. FWIW, I think Kalabox and native *AMP stack are the most valuable tests to compare. However, feel free to throw in docksal or outrigger.sh for good measure.

**Comment by tannerjfco** [comment] 2017-05-24 20:46
Unfortunately, the tests I ran in December weren't done or documented in a way that sufficiently facilitated re-running the tests with accuracy. I made a best effort to reproduce them, and added new metrics for ddev 0.4, as well as ddev tested w/ user-guided caching (see #253 for more info). I do not know that this is an accurate recreation of the test conditions from December however.

Moving forward, I have introduced test scripts in #246. This should allow us to reproduce test conditions more easily and more accurately in the future. A new set of metrics has been recorded for these tests, which test vanilla drupal 7 and 8 sites, as well as commerce kickstart.

The results from both of these tests are captured here in separate sheets: https://docs.google.com/a/drud.com/spreadsheets/d/1vgABX1VzQjd3B9478zfMj__LYT2NVmlnODKDuwUb0tQ/edit?usp=sharing

**Comment by rfay** [comment] 2017-05-26 15:26
@tannerjfco for the "ddev HEAD + docker 17.05" stanza - did you manually add :cached to the mounts on the .ddev/docker-compose.yml?

**Comment by tannerjfco** [comment] 2017-05-26 15:54
I built a binary with the :cached option added to the docker compose template, so that the option was present on the test sites. Manually adding the option would work as well.

**Comment by rickmanelius** [comment] 2017-05-26 16:07
@tannerjfco One question. Were any tests run through the UI? In https://github.com/drud/ddev/issues/253#issuecomment-303728071, I see a significant change in performance on a site install through the UI versus CLI. In an offline conversation, you had noted that the difference might be attributable to one of the following: post-install hooks, file mount choice, and/or running traffice through the proxy. Seeing if Kalabox has a similar performance delta between the UI/CLI would be helpful to know how important this is to address in our v0.6.

**Comment by rickmanelius** [comment] 2017-05-30 13:17
My only request would be to compare the install time through the Drupal install.php interface to see if Kalabox suffers from the same discrepancy and then use that to make a recommendation. This might be fixed with https://github.com/drud/ddev/issues/277.

**Comment by rickmanelius** [comment] 2017-06-02 21:30
Testing on Kalabox now.

**Comment by rickmanelius** [comment] 2017-06-02 22:38
I must be an unlucky one. Installing Kalabox borks my Docker for Mac version and requires me to uninstall/reinstall. I've tried authenticating with Pantheon or spin up locally. I'm still unable to do either and get errors that I've since filed in their GitHub issue queue. Closing this and we can revisit later. However, if @tannerjfco or @rfay can simply run one more test of spinning up D8 with Kalabox from the GUI and compare to a drush site install, that will help me understand the overhead differences of the GUI versus CLI install times.

**Closed by rickmanelius** 2017-06-02 22:38 UTC
Labels: actionable, needs docs, work in progress

**Comment by rfay** [comment] 2017-06-05 22:48
I finally got kbox going and ran one-shot installs on my Macbook Air 2013:

kbox d8 install time web: 2:11
kbox d8 drush si -y install time: 2:03

**Comment by rfay** [comment] 2017-06-05 23:34
Just for future reference:
* kbox from Nov 2016 is incompatible with docker edge (17.06.0), so can't be run alongside ddev, which requires 17.06+
* I was finally successful with kbox by
    1. Uninstall current docker 17.06
    2. Install kbox [v2.1.3](https://github.com/kalabox/kalabox/releases/tag/v2.1.3) and let it install its own docker
    3. Let that docker update itself, which results in a 17.05 stable install. (This will only work for a little while longer, until stable updates).

In general, I found that getting started with kbox was easiest to understand from the command line, where it gives feedback about what's going right or wrong, or what's being downloaded.

Starting with `kbox create pantheon` after doing the above got me pretty far down the line.
