### ISSUE TITLE
Symlinks broken on Windows and Docker Desktop 2.2.0.0

### ISSUE THREAD

**Issue by pulponair** [drud/ddev#2045] opened 2020-01-22 11:30 UTC
After ugrading Docker from 2.1.0.5 to 2.2.0.0 symlinks created by 
`ddev composer install` do not work anymore neigher do thoose directly created from inside the container by e.g. `composer install`  (haven't tried more use cases) 

They look good from the host but from the container they are not accessable -> "input/output error".
 
I guess this might be cause by the "new filesharing implementation" that has been introduced in 2.2.0.0

Downgrading back to 2.1.0.5. Fixes this issue.

**Comment by Kephson** [comment] 2020-01-22 13:01
Hello, many thanks, I could follow this problem.
How is it possible to downgrade Docker for Windows?

**Comment by KaffDaddy** [comment] 2020-01-22 13:16
You must deinstall the whole "Docker Desktop" software from your system and execute the installer from here: https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe
But beware: after that all your docker images are gone. Create snapshots from your databases of all of your DDEV projects.

**Comment by rfay** [comment] 2020-01-22 13:22
I haven't looked at the (many) docker 2.2.0.0 problems on Windows yet, but probably using NFS mounting would fix most of them. Not saying it's worth sticking with docker 2.2.0.0, but it's a great technique in general, https://ddev.readthedocs.io/en/stable/users/performance/

**Comment by pulponair** [comment] 2020-01-22 13:25
@rfay maybe you want to add a note to the Documentation section until these problems are fixed  :)

**Comment by pulponair** [comment] 2020-01-22 13:27
> You must deinstall the whole "Docker Desktop" software from your system and execute the installer from here: https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe
> But beware: after that all your docker images are gone. Create snapshots from your databases of all of your DDEV projects.

Yes i ran straight into that and lost a ton of db containers :) Backups FTW

**Comment by rfay** [comment] 2020-01-22 15:21
I confirm as expected that symlinks work fine if `nfs_mount_enabled: true`, https://ddev.readthedocs.io/en/stable/users/performance/#windows-nfs-setup. Ironically, the major performance improvement in Docker Desktop 2.2.0.0 would have been likely to make NFS a no-op, not necessary. 

An initial review of this (without NFS) may suggest that ddev is not detecting those symlinks in order to convert them to windows symlinks. It will take some debugging time to sort it out. I guess it's to be expected since they changed the whole mount style.

The reason I never detected this working on Windows with Docker edge is that I invariably use NFS for performance reasons, and recommend it to everyone.

**Comment by rfay** [comment] 2020-01-22 17:10
I'm going to close this as a duplicate of https://github.com/drud/ddev/issues/2046 - Since ddev can't find symlinks that have been created in the container, it can't update them. And that's because they don't ever get presented to the host. 

The very simple and very effective alternative is to use nfs_mount_enabled in ddev so then you're not using the new Fuse filesystem.

**Closed by rfay** 2020-01-22 17:10 UTC
