### ISSUE TITLE
v1.18.0-rc1: panic on `ddev describe`: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by weitzman** [drud/ddev#3215] opened 2021-09-03 14:04 UTC
Getting the error below on every ddev command. `describe` gives no output except the error. 

```
Starting mass... 
Using custom PHP configuration: [/home/weitzman/reps/openmass/.ddev/php/my-php.ini] 
Custom configuration takes effect when container is created,
usually on start, use 'ddev restart' if you're not seeing it take effect. 
Running   Command=ip address show dev docker0
Building web 
ddev-mass-backstop is up-to-date 
ddev-mass-portainer is up-to-date 
ddev-mass-chromedriver is up-to-date 
ddev-mass-dbmass is up-to-date 
ddev-mass-memcached is up-to-date 
Recreating ddev-mass-web ... done
 
ddev-router is up-to-date 
Not creating CMS settings files because disable_settings_management=true 
Successfully started mass 
Project can be reached at https://mass.local https://127.0.0.1:49165 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Describe(0xc0000ba600, 0x406112c00, 0xec4bc0, 0xa99e3c, 0x19)
	/workdir/pkg/ddevapp/ddevapp.go:380 +0x44f6
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).SetInstrumentationAppTags(0xc0000ba600)
	/workdir/pkg/ddevapp/instrumentation.go:83 +0x151
github.com/drud/ddev/cmd/ddev/cmd.glob..func38(0xeb99e0, 0xef3a40, 0x0, 0x0)
	/workdir/cmd/ddev/cmd/root.go:136 +0x645
github.com/spf13/cobra.(*Command).execute(0xeb99e0, 0xef3a40, 0x0, 0x0, 0xeb99e0, 0xef3a40)
	/workdir/vendor/github.com/spf13/cobra/command.go:870 +0x33a
github.com/spf13/cobra.(*Command).ExecuteC(0xeb8a20, 0x61322a90, 0xb901374, 0x9b10df94011e)
	/workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/workdir/vendor/github.com/spf13/cobra/command.go:895
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/workdir/cmd/ddev/cmd/root.go:151 +0x3c
main.main()
	/workdir/cmd/ddev/main.go:21 +0xf4
```

**Comment by rfay** [comment] 2021-09-03 14:07
I assume this is a duplicate of https://github.com/drud/ddev/issues/3210 ?

**Comment by rfay** [comment] 2021-09-03 14:09
Actually, it might not be a dup, seems like the stack trace is different. Is it possible to provide the top part of your project's .ddev/config.yaml and the top part of your ~/.ddev/global_config.yaml?

**Comment by weitzman** [comment] 2021-09-03 14:12
I think it is different. I havent yet enabled Mutagen and I'm on Linux host right now. I an the commands in that issue anyway and its still happenning. And now I am seeing a different backtrace for describe

```
anic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Describe(0xc00041a900, 0x0, 0x0, 0xc00012bd00, 0xc00029a008)
	/workdir/pkg/ddevapp/ddevapp.go:380 +0x44f6
github.com/drud/ddev/cmd/ddev/cmd.glob..func14(0xeb5300, 0xef3a40, 0x0, 0x0)
	/workdir/cmd/ddev/cmd/describe.go:47 +0x14e
github.com/spf13/cobra.(*Command).execute(0xeb5300, 0xef3a40, 0x0, 0x0, 0xeb5300, 0xef3a40)
	/workdir/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xeb8a20, 0x61322cdf, 0x2e532bb4, 0x9b9a9caf6f36)
	/workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/workdir/vendor/github.com/spf13/cobra/command.go:895
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/workdir/cmd/ddev/cmd/root.go:151 +0x3c
main.main()
	/workdir/cmd/ddev/main.go:21 +0xf4
```

**Comment by weitzman** [comment] 2021-09-03 14:47
Global
```
omit_containers: []
nfs_mount_enabled: false
mutagen_enabled: false
instrumentation_opt_in: true
router_bind_all_interfaces: false
internet_detection_timeout_ms: 750
last_started_version: v1.18.0-rc1
mkcert_caroot: /home/weitzman/.local/share/mkcert
use_hardened_images: false
use_letsencrypt: false
letsencrypt_email: ""
auto_restart_containers: false
fail_on_hook_fail: false
web_environment: []
disable_http2: false
table_style: default
simple_formatting: false
project_info:
  annotated-command:
    approot: /home/weitzman/reps/annotated-command
  mass:
    approot: /home/weitzman/reps/openmass

```

The project config.yml is at https://github.com/massgov/openmass/blob/8d36cb6cfa21de78eb8befe52c7a7aa9df14b69c/.ddev/config.yaml

**Comment by rfay** [comment] 2021-09-03 14:52
I'll bet it's the
```yaml
omit_containers:
  - db
  - dba
```

Thanks so much for the report. Loads of complex and fragile code to implement the fancy new `describe`.

**Comment by rfay** [comment] 2021-09-04 19:37
Thanks so much for providing the config.yaml - that made it much easier to understand. The bug you triggered was using environment variables in .ddev/config.yaml without values. I imagine this is a straight port from docker-compose, where that implies to pick up the actual docker-compose environment variable and pass it on. 

I fixed the code to not be so fragile (assuming the right-side of assignment was there) and checked in the generated .ddev-docker-compose-base.yaml to see that it seems to do what you want.

These were the things it choked on:

```yaml
  - AC_API2_KEY
  - AC_API2_SECRET
  # New Relic. Needed for deployments.
  - MASS_NEWRELIC_APPLICATION
  - MASS_NEWRELIC_KEY
  # Acquia basic auth.  Needed for tests on Acquia environments.
  - LOWER_ENVIR_AUTH_USER
  - LOWER_ENVIR_AUTH_PASS
  # For Cloudflare Terraform.
  - CLOUDFLARE_EMAIL
  - CLOUDFLARE_TOKEN
```

**Closed** 2021-09-06 19:03 UTC
