### ISSUE TITLE
I can't clear cache using symfony on ddev

### ISSUE THREAD

**Issue by Nitharandis** [drud/ddev#2529] opened 2020-09-29 05:59 UTC
I'm trying to clear the cache in a symfony 3.4 project but this does not work. When I use "cache:clear" command nothing happens, but when I use ddev restart, changes are there. It may have ddev any kind of an internal cache or anything related to docker volumes?

Currently running DDEV-local 1.15.3 in Ubuntu 20 without NFS config.

**Comment by managume** [comment] 2020-09-29 08:16
Hey workmate!

I tested it in a macOS DDEV environment with and without NFS and in a custom docker compose environment but I can't reproduce that behaviour. There's no problem displaying a change even without clearing cache.

Try deleting DDEV environment and whole the project. Then clone it again and rebuild DDEV environment.

**Comment by rfay** [comment] 2020-09-29 13:08
Hi @Nitharandis - If the cache:clear command doesn't do anything, it most likely means that something is wrong in the logic of your project, not that there's anything going on with ddev. ddev is just a hosting environment, and it doesn't even know that there *is* a cache:clear command. So one next step might be turning on xdebug and stepping through the cache:clear command, or using other debugging techniques.

**Comment by rfay** [comment] 2020-09-30 13:49
I'm going to close this for now, but happy to continue the conversation here or elsewhere. I don't think the problem likely has to do with ddev.

**Closed by rfay** 2020-09-30 13:49 UTC
