### ISSUE TITLE
Unable to start DDEV with `nodejs_version: 18` (upstream problem, fix with nodejs 16)

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4614] opened 2023-02-06 18:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

For startup to succeed without fail.

### Actual Behavior

```
Preparing to unpack .../nodejs_18.14.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (18.14.0-deb-1nodesource1) ...
Setting up nodejs (18.14.0-deb-1nodesource1) ...
npm ERR! `unsafe-perm` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-06T18_20_13_278Z-debug-0.log
ERROR: executor failed running [/bin/sh -c bash /tmp/setup_node.sh && apt-get install nodejs && npm config set unsafe-perm true && npm install --global gulp-cli yarn]: exit code: 1
------
 > [drud/ddev-webserver:v1.21.4-houston-built  9/12] RUN bash /tmp/setup_node.sh && apt-get install nodejs && npm config set unsafe-perm true && npm install --global gulp-cli yarn:
```

### Steps To Reproduce

* ddev version v1.21.4
* Macbook M1 - OS X Ventura
* Github Actions `ubuntu-latest` - Ubuntu 22.04

In config.yaml:

```yml
type: drupal9
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.3"
php_version: 8.1
nodejs_version: 18
```

### Anything else?

This job used to succeed four days ago and started failing three days ago. I can confirm this in GIthub Actions as well as my local machine.

**Comment by deviantintegral** [comment] 2023-02-06 19:17
Strangely I can't reproduce this on my Apple Silicon Mac. One of my coworkers pointed out there's breaking npm changes in the latest nodejs release :(

https://nodejs.org/es/blog/release/v18.14.0/

**Comment by davereid-pfg** [comment] 2023-02-06 19:23
Looks like `npm config set unsafe-perm true` is only supported on NPM 6: https://docs.npmjs.com/cli/v6/using-npm/config?v=true (NodeJS 14) and is no longer supported on NodeJS 16+ / NPM 7+?

**Comment by davereid-pfg** [comment] 2023-02-06 19:24
I cannot replicate a failure with `npm config set unsafe-perm true` on my local NPM 8 / NodeJS 18 install on my Mac, this only happens as a failure inside the DDEV container/start.

**Comment by davereid-pfg** [comment] 2023-02-06 19:26
I can confirm that the last Github Action job that passed without error was using:
```
NodeJS version: v18.13.0
NPM version: 8.19.3
```

So this does seem to be caused by npm 18.14.0

**Comment by davereid-pfg** [comment] 2023-02-06 19:28
I can replicate it locally now:

```
> node --version
v18.14.0

> npm config set unsafe-perm true
npm ERR! `unsafe-perm` is not a valid npm option

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/R654600/.npm/_logs/2023-02-06T19_27_37_218Z-debug-0.log
```

**Comment by deviantintegral** [comment] 2023-02-06 20:49
Given that node intentionally added breaking changes in an LTS release, I think ddev should consider pinning the minor version, or at least allowing the minor to be specified in `config.yaml`.

Normally, I'd also want to report this upstream... but they clearly knew there were breaking changes and released it anyways: https://github.com/nodejs/node/pull/46396

**Comment by rfay** [comment] 2023-02-06 20:54
I'm pretty sure this was already solved in 
* https://github.com/drud/ddev/pull/4610

I hope you'll try HEAD, `brew install --HEAD --fetch-head ddev`

**Comment by deviantintegral** [comment] 2023-02-06 21:05
@rfay do you expect to roll a new release to fix this soon? If not, that's fine, but then we'll probably invest some time in working on https://github.com/jonaseberle/github-action-setup-ddev/issues/15.

**Comment by rfay** [comment] 2023-02-06 21:06
v1.21.5 is planned to be released on March 5. 

Do you think it needs some kind of emergency patch release?

**Comment by rfay** [comment] 2023-02-06 21:07
I think there might be a possible workaround that could be implemented with a `Dockerfile.pre.*`

**Comment by rfay** [comment] 2023-02-06 21:13
@deviantintegral I'm not even sure that they make packages available for non-current versions, but they may. Many debian package providers don't provide the old ones. We could probably figure out how to move to nvm-only. But wow, this was sure nasty. Thanks for tracking down the issue. I was really annoyed when *all* the tests broke at once.

**Comment by deviantintegral** [comment] 2023-02-06 21:18
I was just able to replicate on my Mac after wiping my docker images completely - I must have had some dangling docker images I thought I'd removed.

This is certainly broken for node 18. Node 16 works correctly. As far as a hotfix goes, I guess it depends how many users you expect to be on node 18?

**Comment by deviantintegral** [comment] 2023-02-06 21:29
For anyone else searching: The files are `pre.Dockerfile.*`: https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

From our read, because there's no conditional on the line that errors there isn't a way to use that file to fix this.

**Comment by rfay** [comment] 2023-02-06 21:45
I'll take a look this afternoon and see if I can see a workaround.

**Comment by deviantintegral** [comment] 2023-02-06 21:49
It looks like we don't have any hard node 18 dependencies so we can actually downgrade to 16 for now. Given there's only a few in this issue I'm guessing the majority of ddev users are on 16 and not 18.

**Comment by rfay** [comment] 2023-02-06 22:28
I don't see a way to use a .ddev/web-build/pre.Dockerfile.npm and solve this. 

So the options I can think of are these, given a release is scheduled for the first Sunday in March, March 6:

1. People can try to get by with `nodejs_version: 16` (or lower) in the meantime. (node 16 is the default version)
2. We can do a tiny patch release (on its own branch) just fixing this and #4608 
3. We can do an edge/prerelease now that includes everything currently on master; this is likely to be low risk.

**Comment by rfay** [comment] 2023-02-06 23:23
Added a 4th option to the possibilities in https://github.com/drud/ddev/issues/4614#issuecomment-1419870911

**Comment by davereid-pfg** [comment] 2023-02-08 20:02
I'd probably support #3 or #4.

**Comment by deviantintegral** [comment] 2023-02-09 00:04
I've been running HEAD since Monday and it's been fine. I would lean towards towards #4. Make sure that the release notes indicate this is all changes and reflects the upcoming release, and then if you get feedback about bugs you could roll a hotfix only release but you'd have the benefit of the bug reports for the March release.

**Comment by gilbertsoft** [comment] 2023-02-09 16:47
Prerelease fixing this issue is available https://github.com/drud/ddev/releases/tag/v1.21.5-alpha1

**Comment by rfay** [comment] 2023-02-09 17:26
Closing, leaving it pinned.

**Closed by rfay** 2023-02-09 17:26 UTC
