### ISSUE TITLE
Experimenting with Mutagen enabled for Windows legacy installation.

### ISSUE THREAD

**Issue by JonMcL** [drud/ddev#3361] opened 2021-11-08 14:45 UTC
I am just getting up to speed on Mutagen, but it seems interesting to me. I haven't really noticed the benefits yet, but only enabled today on my MacOS development machine. :)

I have never been completely happy with performance on Windows and I'm curious why Mutagen isn't recommended for a Windows WSL2 installation?

My Windows performance issues are all connected to using Windows native applications (PHPStorm and Git Fork). The PHP and MySQL execution inside of the WSL2 container (Ubuntu) is perfect. PHPStorm is somewhat usable, but Git Fork is completely unusable unless I install the wslgit utility (which pipes git commands into the WSL2 container's native git).

I'm also not a huge fan of having all the project files stored only on the WSL2 container file system instead of the Windows native file system.

So if I use choco to install ddev in Windows, instead of brew to install inside of WSL2, would Mutagen work to let me leave the files on the native Windows file system, but still execute PHP and run the database inside of a Linux container?

Or am I missing something?

**Comment by rfay** [comment] 2021-11-08 14:53
* If you're running ddev inside WSL2, you'll find that the performance is as fast as mutagen can provide, at least with my testing.
* If you're having trouble with performance of *Windows*-side applications like PhpStorm and GitFork, mutagen (as provided with ddev) has absolutely no impact on those. The problem is with those apps reaching across from windows essentially over a network mount, which is slow. You may be interested in reading https://ddev.com/ddev-local/ddev-local-and-phpstorm-debugging-with-wsl2/

If you prefer to use ddev on the Windows side, it is vastly improved by mutagen, but the initial sync is dreadfully slow. But after that it's wonderful.  But that has nothing to do with WSL2 - it's running on the Windows site.

You're welcome to use mutagen on WSL2. It does no harm. Our CI tests mutagen on Linux, it works perfectly. But it doesn't deal with the problem you're experiencing, Windows side applications reaching across into the WSL2 filesystem.

(And if you enabled mutagen on macOS and didn't immediately see the benefits, something is terribly wrong. )

> So if I use choco to install ddev in Windows, instead of brew to install inside of WSL2, would Mutagen work to let me leave the files on the native Windows file system, but still execute PHP and run the database inside of a Linux container?

Yes, it works great. Not as fast as WSl2, but yes, it works, slow syncing. But your issue was "Why not recommend mutagen for Windows WSL2 installations", which is a completely different topic.

**Comment by JonMcL** [comment] 2021-11-08 15:01
Sorry, I'm still confused :)

If I put my PHP project files in a Windows directory, install ddev with choco, configure ddev to use Mutagen, then run ddev start --- wouldn't ddev create Docker container(s) for MySQL and and web, use Mutagen to sync the files from Windows into the web container, and execute PHP inside web container at the same WSL2 speeds as if I installed the PHP project files inside of the Ubuntu container myself?

I can tolerate an initial sync that is slow, but then I would have full speed Fork and PHPStorm access to the source project files since they are on the native Windows FS. Or will a I see a slowdown of PHP execution because the web container was created and initialized from the Windows version of ddev instead of the Linux version?

**Comment by JonMcL** [comment] 2021-11-08 15:03
> You'd have to think long and hard about the consistency issues that might result.

Understood, but I don't modify any project files except through PHPStorm and git. Only exception is CSS building (gulp and SASS). I think PHPStorm might execute the CLI commands inside the container, so I may need to manually configure some of that if PHPStorm is no longer using the //wsl$/ path.

**Comment by JonMcL** [comment] 2021-11-08 15:03
I will give it a try and let you know what I find :)

**Comment by JonMcL** [comment] 2021-11-08 22:35
So far so good. Installation was simple. After a git clone (executed through Git Fork), the initial sync of a Drupal 9 site took about 50 seconds. Performance seems good, but I didn't do any real benchmarks or comparisons yet. Git Fork performance is very fast. PHPStorm seems a little quicker as well. AND all my project files are in the native Windows file system.

One issue that might be more of a Mutagen issue in this environment -- the eXecution bit of the drush files inside of /vendor/ is not being set properly. So I'm currently getting permission denied errors when I try and run `ddev drush` commands.

**Comment by rfay** [comment] 2021-11-09 01:30
If you're using `ddev drush` then you should see the permissions on /var/www/html/vendor/bin/* be fine (inside web container). Not sure what you're doing. If you're then trying to relay that from WSL2 into Windows you're likely to have some trouble, because windows doesn't have the concept of permissions bits.

**Comment by rfay** [comment] 2021-11-09 01:57
I haven't been able to follow exactly what you're doing now. Are you using mutagen-enabled on Windows, ignoring WSL2? In that case, you may be looking at the symlinks in vendor/bin on the windows side using git-bash or whatever. Not only does Windows not really have the same permissions case as Linux (what is in the container) but symlink ownership and permissions don't translate directly. https://github.com/mutagen-io/mutagen/issues/282 is probably related.

**Comment by JonMcL** [comment] 2021-11-09 15:32
I'm trying to keep the project files primarily inside of the Windows filesystem instead of putting them inside of the Ubuntu filesystem (my WSL2 Linux VM). I do have WSL2 installed and I believe that is recommended for Docker performance anyway. I'm just not using the Ubuntu/Linux CLI when I run ddev commands. Instead I'm using Windows PowerShell (or git-bash) to execute ddev commands.

Reasons for me to explore this are to avoid hacks to Windows GUI apps (Git Fork) and hopefully improve PHPStorm performance a little (although I don't notice any major improvements there). This is to avoid having Windows apps accessing the project files through the //wsl$/ path (which is known to be very slow and MS doesn't seem to be prioritizing any fixes). I also have some issues with WSL2 and my VPN (Cisco AnyConnect). There is a known issue that ends up breaking all network connectivity inside the WSL2 VM when the VPN connects.

I did solve my drush permissions issues. We (unfortunately) are committing vendor and other composer installed filed into our repo. So the simple solution was to delete the vendor directory and run `ddev composer install` after the `git clone`. This way, composer takes care of file permissions inside of the ddev container. I could probably be more selective with which composer packages I force to re-install, and there might be some .sh files in Drupal core that aren't getting their +x enabled.

Overall, it's working (using PowerShell instead of the WSL2 virtual machine CLI). Performance appears good all around. I do notice odd pauses when I try and execute ddev commands, but I suspect that is my Windows laptop or possibly security related software being nosey in the background. `ddev xdebug on` too upwards of 7 to 10 seconds to complete. 

I do have to do more testing, but so far everything seems to work well with ddev and Mutagen and only using the Windows native file system. Having to run `ddev composer install` for every new developer installation is going to be problematic, but that could also be solved by removing composer packages from our git repo.

**Comment by rfay** [comment] 2021-11-09 20:10
Hi @JonMcL - 

First, let's keep the terminology straight. WSL2 for Docker is a completely different subject. Although Docker Desktop supports the legacy Hyper-V technique, it's basically obsolete and has nothing to do with these topics. Anybody using current Docker should use the WSL2 docker back-end. But that has nothing to do with DDEV or mutagen. 

If you want to work on the WIndows filesystem, you absolutely need to work on the Windows side, use the Windows DDEV, and essentially ignore WSl2, (even though we know that Docker is using it).

And yes, DDEV works fine with mutagen on Windows, after you put up with the initial sync.

Thanks for changing the title. I'll go ahead and close this now, happy to continue the conversation here though, and would love to hear your reactions after using it for awhile.

**Closed by rfay** 2021-11-09 20:10 UTC
