### ISSUE TITLE
Host commands trigger the pre-start hook.

### ISSUE THREAD

**Issue by dkd-kaehm** [drud/ddev#2851] opened 2021-03-04 12:27 UTC
**Describe the bug**
I have a custom host command, which does only file movements, file deletions and `ddev delete --omit-snapshot --yes`.
By each call of this command, the configured `pre-start` hooks are executed.
But even if I define a  host command with simple echo, the ddev fires the `pre-start` hooks.

**To Reproduce**

1. define simple host command e.g. `exampleHostCommand`
2. define some pre-start hooks in your `.ddev/config.yaml` with simple echoes to show that pre-start hook is called
3. Call this command via `ddev exampleHostCommand`

**Expected behavior**
The pre-start MUST NOT be called on any host commands.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10, macOS, WSL 2, Ubuntu, etc. 
- Docker Desktop version: does not matter
- ddev version information:

 ```
DDEV-Local version	v1.16.6                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba               	phpmyadmin:5                           
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0            
docker            	20.10.5                                
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.16.2               
web               	drud/ddev-webserver:v1.16.6             
  ```

- config.yaml contents for the misbehaving project: https://github.com/TYPO3-Solr/solr-ddev-site/blob/c313aaecd8b63fe3b3a0956d052a444de18517be/.ddev/config.yaml
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? No

**Additional context**
My trouble host command -> https://github.com/TYPO3-Solr/solr-ddev-site/blob/c313aaecd8b63fe3b3a0956d052a444de18517be/.ddev/commands/host/clean
Commenting to `ddev delete --omit-snapshot --yes

**Comment by rfay** [comment] 2021-03-04 14:39
Unfortunately, in the current implementation, all custom commands do a `start` if the project is not running. 

Closing this as a duplicate of the feature request in https://github.com/drud/ddev/issues/2688

Happy to continue the conversation here, there, or elsewhere.

**Closed by rfay** 2021-03-04 14:39 UTC
