### ISSUE TITLE
docroot not automatically set to "web" for Craft CMS in 1.21.4

### ISSUE THREAD

**Issue by jessedobbelaere** [drud/ddev#4477] opened 2022-12-22 00:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://share.jessedobbelae.re/n/7ws4hw

### Expected Behavior

With ddev 1.21.4, I should see: `docroot: web` in the config after setting up a fresh ddev project for craftcms, according to the instructions on https://craftcms.com/docs/getting-started-tutorial/install/

### Actual Behavior

I see output `docroot: ""` in the `config.yaml` file.

### Steps To Reproduce

1. Update to the latest version (ddev 1.21.4)
2. Run these commands:

```bash
# Taken from: https://craftcms.com/docs/getting-started-tutorial/install/
ddev config --project-type=craftcms

# Check docroot value
cat .ddev/config.yaml | grep docroot
```

### Anything else?

The `docroot` is "web" on 1.21.3 and 1.21.2. The empty docroot bug seems introduced in 1.21.4?

Note: when I first install craft via a method that's not using ddev, or take an existing craft project, and then add ddev, it detects the web folder automatically:

```bash
composer create-project --no-scripts --no-install craftcms/craft .
ddev config --project-type=craftcms
cat .ddev/config.yaml | grep docroot # outputs docroot: web
```

**Comment by rfay** [comment] 2022-12-22 02:37
`git bisect` says this change happened in de59cdca32c45ee24bb54432c7f78d09dc4bdb3a, 
* #4317

However, I'm a little surprised in general because normally docroot is detected, not wired. So normally DDEV looks to see what the code has and finds the docroot that way. That's why the normal recipe specifies the docroot (`ddev config --project-type=craftcms --docroot=web --create-docroot`) because the code doesn't exist yet in the composer recipe, so ddev can't autodetect.

**Comment by rfay** [comment] 2022-12-22 02:39
The configOverrideAction was removed in https://github.com/drud/ddev/pull/4317/files#diff-192cf62e03f84f6c3b082d68b248344eebb6e4f8d5dcfbd40880e921d374e7c1L71

and 

https://github.com/drud/ddev/pull/4317/files#diff-5799e15d18a89a9d31d37f6e9e80b06f41c6e5e20bcfc74ebeb8af8f10d06d3bL20-L26

I actually think that the configOverrideAction setting it to "web" was a mistake and. it was appropriate to remove it.

**Comment by jessedobbelaere** [comment] 2022-12-22 11:27
Thanks for checking @rfay ! 

If this change was intended, your recommendation would be to adjust https://craftcms.com/docs/4.x/installation.html#quick-start to mention `ddev config --project-type=craftcms --docroot=web --create-docroot` instead of `ddev config --project-type=craftcms` ?

**Comment by AugustMiller** [comment] 2022-12-22 22:21
Thanks, all, for investigating. 💞

We (Pixel & Tonic) recently decided to emphasize DDEV in our official documentation (in [craftcms/docs#450](https://github.com/craftcms/docs/pull/450)), with instructions that worked as of 1.21.3.

My initial reaction was that this was a regression, but my position has changed in the last day. DDEV should be as easy to set up for new projects as existing ones, and therefore a hard-coded docroot doesn't make sense.

Our install guide only covers usage of the [`craftcms/craft`](https://github.com/craftcms/craft) starter project, which _does_ have a default web/docroot of `web/`, but under virtually any other circumstance (including use of community starter projects), the same assumption can't be made.

I will make the change on our end to reflect the un-opinionated `docroot` default.

---

In the process of investigating this, I noticed that the install directions had been changed a couple more times, so I'll be submitting a PR to bring them into alignment with the team’s latest, tested recommendations.

**Comment by rfay** [comment] 2022-12-22 22:33
Thanks so much!

**Comment by khalwat** [comment] 2022-12-23 16:27
Yeah, that's why I was concerned with the removal of this.  Apparently DDEV isn't auto-detecting as advertised

If we have to specify it with `--docroot=web --create-docroot` every time, that seems less good than it defaulting to this, and being able to _override_ that setting if you need to.

**Comment by khalwat** [comment] 2022-12-23 16:32
@AugustMiller 

> My initial reaction was that this was a regression, but my position has changed in the last day. DDEV should be as easy to set up for new projects as existing ones, and therefore a hard-coded docroot doesn't make sense.

The intent was to hard-code the default to match the Craft starter, but allow it to be overridden via `--docroot=web --create-docroot` if you need something else.

I think the current setup of forcing you to specify what should be the default every time is significantly more verbose/error-prone, and thus, significantly worse.

It should do the right thing by default, and allow for overriding it if you need something else.

**Comment by rfay** [comment] 2022-12-23 16:41
@khalwat DDEV can't auto-detect when there's no code, which is the typical case before composer install.

**Comment by khalwat** [comment] 2022-12-23 17:33
...so probably having it default to `web/` but allow it to be overridden via `--docroot=web` is the best way forward?

That was how it was originally supposed to work.

**Comment by rfay** [comment] 2022-12-23 17:41
Yeah, I removed that because the assumption of "web" even with no code available was different from all other project types.  If code exists, DDEV will autodetect both docroot and project type.

**Comment by khalwat** [comment] 2022-12-23 17:47
I think having to do this for the install process:

```
ddev config --project-type=craftcms --docroot=web --create-docroot
```

...is worse than just:

```
ddev config --project-type=craftcms
```

Can't you just have it default to `--docroot=web --create-docroot` for the `craftcms` project type, so it does the right thing by default?

**Comment by lindseydiloreto** [comment] 2022-12-23 18:19
I've been following this issue (both here and on Discord) and have to say that I fully agree with @khalwat. If you are using the `craftcms` project type, the `docroot` should default to `web` instead of being blank. As long as it can be overridden, I don't see why that would be a problem.

For the overwhelming majority of new Craft installations, the default `web` folder will be the document root. The small minority (including myself) who rename that folder will be able to easily override it, just as they already do.

Leaving the `docroot` value to be blank by default is already causing multiple people to have issues on Craft Discord...

![Ω  2022-12-23  10 17 24](https://user-images.githubusercontent.com/5309692/209390333-b7c4114f-764b-462d-bdfd-615f351a57be.png)

![Ω  2022-12-23  10 16 34](https://user-images.githubusercontent.com/5309692/209390350-1c1ac6b3-c5c3-45c1-940e-5131685351aa.png)

**Comment by rfay** [comment] 2022-12-23 19:38
What I'd actually like to see is an alternate reality for DDEV where the composer install happens before the config, or where we do a config again after the composer install, when the code is there to guide it. Then we'd have full functionality for everybody. For example, `ddev config --auto` and then `ddev composer create ...` and then `ddev config` again. IIRC `ddev config` has too much respect for what's there already in this case, but that could be fixed. Another approach is for `ddev composer create` to be able to be run without a config, or to return to the config after it is done.

**Comment by rfay** [comment] 2023-01-06 17:56
I'm interested in future alternatives, but think we have it right for the current world. 

I really would like ideas about how to combine the DDEV config and composer create stages so that these ideas are consolidated.

Closing for now, happy to continue the conversation. It sounds like the Craft CMS docs will sync up with the existing DDEV quickstart.

**Closed by rfay** 2023-01-06 17:56 UTC
