### ISSUE TITLE
import-files not working for the project type typo3

### ISSUE THREAD

**Issue by michadu** [drud/ddev#928] opened 2018-06-17 21:27 UTC
**Describe the bug**
Running this command
ddev import-files --src ~/Downloads/fileadmin.zip
results in this message
No upload directory has been specified for the project type typo3

**Expected behavior**
The files are imported into the fileadmin folder of the website root folder.

**Version and configuration information:**
 - macOS Sierra
 - Docker version 18.03.1-ce, build 9ee9f40
 - DDEV v0.19.0

**Comment by rfay** [comment] 2018-06-17 21:28
We hope to have this for you in the next release! Thanks for the issue. Duplicate of https://github.com/drud/ddev/issues/666

**Closed by rfay** 2018-06-17 21:28 UTC
