### ISSUE TITLE
Documentation incorrect/inconsistent for Docker Compose file overrides

### ISSUE THREAD

**Issue by decafdennis** [drud/ddev#829] opened 2018-05-07 16:39 UTC
## What happened (or feature request):

I tried to customize the Docker Compose configuration per https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/ by creating a file `docker-compose.override.yaml` with the following:

```yaml
version: '3'

services:
  web:
    volumes:
      - "../:/var/www/html:cached"
      - "../../octomodel/:/var/www/html/web/profiles/octomodel:cached"
      - ".:/mnt/ddev_config"
```

My overrides did not get picked up. When I renamed to `docker-compose.overrides.yaml` (notice the plural overrides) it did work.

## What you expected to happen:

My custom mounts would work and be listed when using `$ docker inspect` on the web service container.

## How to reproduce this:

Create the aforementioned override file and notice the custom mount is not listed when running `$ docker inspect` on the web service container.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

```
$ ddev version
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.17.0                        
domain	ddev.local                     
cli   	v0.17.0                        
web   	drud/nginx-php-fpm-local:v1.2.2
db    	drud/mariadb-local:v0.9.0       

$ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

`.ddev/config.yml`:
```
APIVersion: "1"
name: octomodel-drupal
type: drupal8
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
provider: default
```

## Anything else do we need to know:

Might just need a documentation change... but I also noticed there are test cases that cover the `docker-compose.override.yml` that may need to be changed/fixed.

**Comment by rfay** [comment] 2018-05-07 16:42
Sorry to say that "override" was broken until v0.18.0 (this week). https://github.com/drud/ddev/issues/815

But if you use any name *other* than override you should be able to make it work. Like docker-compose.mystuff.yaml.

**Comment by rfay** [comment] 2018-05-14 16:18
Closing as a duplicate of #815 , please let us know if that's not correct, and hope v0.18.0 is working ok for you.

**Closed by rfay** 2018-05-14 16:18 UTC
