### ISSUE TITLE
Configuration router_bind_all_interfaces is not working

### ISSUE THREAD

**Issue by benjifisher** [drud/ddev#2076] opened 2020-02-07 22:54 UTC
**Describe the bug**

I set `router_bind_all_interfaces: true` in `~/.ddev/global_config.yaml` but my site is still available only from localhost.

**To Reproduce**

1. Either edit `~/.ddev/global_config.yaml` and set `router_bind_all_interfaces: true` or use the command  `ddev config global --router-bind-all-interfaces=true`. (I tried both.)
2. Check the assigned ports with `ddev describe`.
3. Check the active ports with `sudo netstat -lntp`.
4. Visit the site from another computer on the same network.

**Expected behavior**

I expect the ports I find in Step 2 to be open to all interfaces in Step3.

I expect to see my site in a browser in Step 4.

**Screenshots**

How about screen dumps instead of shots?

Step 2:

```
$ ddev describe
NAME        TYPE     LOCATION            URL                           STATUS        
demo-site2  drupal8  ~/sites/demo/site2  https://demo-site2.ddev.site  running

Project Information
-------------------
PHP version:   	7.3
MariaDB version	   
MySQL version  	   

URLs
----
http://demo-site2.ddev.site 
http://127.0.0.1:32792      
https://demo-site2.ddev.site
https://127.0.0.1:32791     

MySQL/MariaDB Credentials
-------------------------
Username: "db", Password: "db", Default database: "db"

or use root credentials when needed: Username: "root", Password: "root"

Database hostname and port INSIDE container: db:3306
To connect to db server inside container or in project settings files: 
mysql --host=db --user=db --password=db --database=db
Database hostname and port from HOST: 127.0.0.1:32790
To connect to mysql from your host machine, 
mysql --host=127.0.0.1 --port=32790 --user=db --password=db --database=db

Other Services
--------------
MailHog:   	http://demo-site2.ddev.site:8025
phpMyAdmin:	http://demo-site2.ddev.site:8036

DDEV ROUTER STATUS: healthy	
ssh-auth status: healthy 
```

Step 3:

```
$ sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      910/systemd-resolve 
tcp        0      0 127.0.0.1:32790         0.0.0.0:*               LISTEN      3339/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      6079/sshd           
tcp        0      0 127.0.0.1:32791         0.0.0.0:*               LISTEN      3486/docker-proxy   
tcp        0      0 127.0.0.1:32792         0.0.0.0:*               LISTEN      3498/docker-proxy   
tcp6       0      0 :::32788                :::*                    LISTEN      3511/docker-proxy   
tcp6       0      0 :::22                   :::*                    LISTEN      6079/sshd           
tcp6       0      0 :::8025                 :::*                    LISTEN      4304/docker-proxy   
tcp6       0      0 :::443                  :::*                    LISTEN      4336/docker-proxy   
tcp6       0      0 :::8036                 :::*                    LISTEN      4278/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      4361/docker-proxy
```

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04 (bionic)
 - Docker version information 
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information
```
$ ddev version
DDEV-Local version	v1.13.0                                
commit            	v1.13.0                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.13.0            
docker            	19.03.5                                
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.13.0               
web               	drud/ddev-webserver:v1.13.0
```
 - config.yaml contents for the misbehaving project
```
$ cat .ddev/config.yaml | grep -v ^# | grep -v ^$
APIVersion: v1.13.0
name: demo-site2
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? No

**Additional context**

The host computer is a VM (Vagrant, VirtualBox). This might cause all sorts of problems, but see the following comments.

As the screendumps show,

- MailHog and phpMyAdmin are running on ports 8025, 8036.
- These two ports are available on all interfaces.

Sure enough, when I visit http://192.168.33.10:8025 or http://192.168.33.10:8036 in my browser, I see those two services. (I have configured the IP address of my VM to be 192.168.33.10.)

I started the site before setting `router_bind_all_interface: true`, but then I did

```
ddev poweroff
ddev delete --omit-snapshot --yes demo-site2
```

before starting it again.

**Comment by rfay** [comment] 2020-02-07 23:38
Your netstat command seems to show ports 80 and 443 being listened to on all interfaces:
```
tcp6       0      0 :::443                  :::*                    LISTEN      4336/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      4361/docker-proxy
```

Here's what I see on Ubuntu 18.04 when set up normally (listening only on 127.0.0.1):
```
$ sudo netstat -lntp | egrep ":(80|443)"
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      21262/docker-proxy  
tcp        0      0 127.0.0.1:8025          0.0.0.0:*               LISTEN      21199/docker-proxy  
tcp        0      0 127.0.0.1:443           0.0.0.0:*               LISTEN      21231/docker-proxy  
tcp        0      0 127.0.0.1:8036          0.0.0.0:*               LISTEN      21167/docker-proxy  
```

And here's what I see when set up with router-bind-all-interfaces:
```
$ sudo netstat -lntp | egrep ":(80|443)"
tcp6       0      0 :::80                   :::*                    LISTEN      12450/docker-proxy  
tcp6       0      0 :::8025                 :::*                    LISTEN      12416/docker-proxy  
tcp6       0      0 :::443                  :::*                    LISTEN      12434/docker-proxy  
tcp6       0      0 :::8036                 :::*                    LISTEN      12383/docker-proxy  
```

I don't actually know why netstat switches from using the tcp header to tcp6; I imagine it's simplifying the output. 

You don't mention what OS and variant you're using. I've inferred that it's Linux because of the netstat command you used? If you provide that info it will help.

Note that you do not need to `ddev delete` at all here, you only need to `ddev poweroff` (to kill off the ddev-router, which is what is doing the binding/listening on those ports) 

I imagine you already know that you have to provide name resolution separately to your remote computer. When your remote computer (the host?) looks up "demo-site2.ddev.site", it's going to get 127.0.0.1, which is absolutely not going to get you connected to your ddev computer. You'll either have to provide an entry in the /etc/hosts of the remote computer pointing to the one where ddev is running, or run a local DNS, or whatever.  ddev-router uses the name header to sort out where to send the request.

**Comment by benjifisher** [comment] 2020-02-08 00:00
> You don't mention what OS and variant you're using.

The VM (where Docker and Ddev are running) has

Host computer OS and Version: Ubuntu 18.04 (bionic)

as I said at the top. That is where I ran `netstat`. The actual computer is also running Linux: Pop!_OS 19.10, which is basically Ubuntu 19.10 (eoan).

> ... you only need to `ddev poweroff`

Thanks. That is good to know.

> When your remote computer (the host?) looks up "demo-site2.ddev.site" ...

It never has to do that, since I enter something like http://192.168.33.10:8025/ (MailHog) or http://192.168.33.10:8036/ (phpMyAdmin) in the browser.

Maybe I misunderstand: is the intention of `router_bind_all_interface: true` just to expose ports 80 and 443 (or whatever is used for HTTP and HTTPS) and not the individual ports for each running site? Is it just an accident that MailHog and phpMyAdmin are exposed?

**Comment by rfay** [comment] 2020-02-08 00:31
router_bind_all_interfaces is for the *router*, which is what proxies ports 80 and 443 and 8025 and 8036. It does nothing with the localhost ports that are automatically bound to localhost. 

The router can't route anything without a host header, so http://192.168.33.10:8025/ can't get you to the right place. 

You can use `curl -H Host: <hostname>` to access things like that, and you can add host headers with various browser addons. But the router needs hostnames to be able to route.

Maybe I'm not understanding your question yet, in which case let's keep going.

**Comment by rfay** [comment] 2020-02-08 00:44
If you want the ephemeral ports for a specific project (only http and https) to be on 0.0.0.0, you can do that with a docker-compose.bindall.yaml, 
```
version: '3.6'
services:
  web:
    ports:
    - "0.0.0.0:$DDEV_HOST_WEBSERVER_PORT:80"
    - "0.0.0.0:$DDEV_HOST_HTTPS_PORT:443"
```

**Comment by benjifisher** [comment] 2020-02-08 05:03
That is close. When I try that, the web container fails to start, and I think this is the relevant part of the error message:

```
Error starting userland proxy: listen tcp 127.0.0.1:59018: bind: address already in use
```

The port is `59018` because that is what I set in `.ddev/config.yaml` for HTTPS (and `59017` for HTTP).

I replaced the two environment variables with different numbers (`49017` and `49018`) and now I can access the site at http://192.168.33.10:49017 or https://192.168.33.10:49018.

That will work for my purposes. I can manage a small YAML file for each site I set up.

Thanks for the help!

**Comment by rfay** [comment] 2020-02-08 13:33
You can do a `ddev poweroff` (or even just `ddev stop` and then `ddev start` again, you're right about the cause.  And this seems like a pretty good strategy for your need.

**Comment by rfay** [comment] 2020-02-10 15:16
It sounds like this is resolved. In the end, you were interested in using a port-specific binding for each project, which can be accomplished at the project level. `router_bind_all_interfaces` is for system-level exposure via the ddev-router, and requires some kind of name resolution in the local network to be able to work.

Happy to continue the conversation here, closing for now.

**Closed by rfay** 2020-02-10 15:16 UTC
