### ISSUE TITLE
name: <projectname> doesn't automatically provides an http://projectname.ddev.local

### ISSUE THREAD

**Issue by acnimda** [drud/ddev#1566] opened 2019-05-02 12:09 UTC
**Describe the bug**
 visiting https://dreamteam.ddev.local returns into can't connect to the server 

**To Reproduce**
1. `ddev config`
2.` ddev start`
3. result in
`Successfully started dreamteam
Project can be reached at http://dreamteam.ddev.local, https://dreamteam.ddev.local, http://127.0.0.1:32773`

4. `ddev describe dreamteam`
`NAME       TYPE     LOCATION                  URL(s)`
       `STATUS`
`dreamteam  drupal8  x:/xxx/dreamteam  http://dreamteam.ddev.local   running https://dreamteam.ddev.local`

`Project Information`
`-----------------`
`PHP version:    7.3`

`URLs:           http://dreamteam.ddev.local, https://dreamteam.ddev.local, http://127.0.0.1:32773`

`MySQL Credentials`
`-----------------`
`Username:       db`
`Password:       db`
`Database name:  db`
`Host:           db`
`Port:`
`MariaDB version 10.2`
`To connect to mysql from your host machine, use port 32772 on 127.0.0.1.`
`For example: mysql --host=127.0.0.1 --port=32772 --user=db --password=db --database=db`

`Other Services`
`--------------`
`MailHog:        http://dreamteam.ddev.local:8025`
`phpMyAdmin:     http://dreamteam.ddev.local:8036`

`DDEV ROUTER STATUS: healthy`
`ssh-auth status: healthy`

**Expected behavior**
I expected visiting https://dreamteam.ddev.local should resulting in the same result as visiting 
http://127.0.01:32771

**Screenshots**
If asked will be added.

**Version and configuration information (please complete the following information):**
 - Host computer OS: Windows 10
 -  `docker version` 2.0.0.3
 -  `ddev version` 1.7.1
 - config.yaml contents for the misbehaving project
 - custom configuration (nginx, php, mysql) in the .ddev folder
` php_version: "7.3"` # default = 7.2

**Additional context**
In ddev version 1.6.0 it was working like a charm, upgraded ddev with choco `choco upgrade ddev` and  now having this issue. Also downgraded ddev to 1.6.0 `install ddev --version 1.6.0 --allow-downgrade` resulted in same issue.

**Comment by rfay** [comment] 2019-05-02 12:51
You don't mention what code you're using, so I don't know how to recreate this. Please say what the difference is between hitting the direct-localhost URL and going through the ddev.local path.

My bet is that you've added more than 10 projects, and Windows 10 /etc/hosts doesn't work after that. Could you please try `ddev remove --all && sudo ddev hostname --remove-inactive` and then start again?

**Comment by acnimda** [comment] 2019-05-02 13:04
> 
> 
> You don't mention what code you're using, so I don't know how to recreate this. Please say what the difference is between hitting the direct-localhost URL and going through the ddev.local path.
> 
> My bet is that you've added more than 10 projects, and Windows 10 /etc/hosts doesn't work after that. Could you please try `ddev remove --all && sudo ddev hostname --remove-inactive` and then start again?

thnx for the quick reply and your advise. with `sudo` didn't work. When removed inactives it was over the 10 hosts 
for furter googlers use:    
`ddev remove --all && ddev hostname --remove-inactive`

**Comment by rfay** [comment] 2019-05-02 13:25
Thanks, glad it's working! I wish WIndows didn't do that, and I wish the library we use (goodhosts) didn't use the one-line-for-all approach. 

This ended up a duplicate of [More than 10 hostnames per line of /etc/hosts breaks on Windows OS](https://github.com/drud/ddev/issues/948). My plan is actually to fork goodhosts, which seems to be unmaintained, and see if we can solve the problem that way.

**Closed by rfay** 2019-05-02 13:25 UTC
