### ISSUE TITLE
Allow custom hostnames

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev#868] opened 2018-05-21 15:46 UTC
**Is your feature request related to a problem? Please describe.**
I wish that additional hostnames didn't get `.ddev.local` affixed to them.

**Describe the solution you'd like**
I want to be able to define hostnames like `dev.fillpdf.io` and have them added to `/etc/hosts` as-is. I'm OK with it being a separate config variable than the existing one. 

**Describe alternatives you've considered**
Manually adding it to my `/etc/hosts` myself...

**Additional context**
I'm starting to move over my lesser-used VMs that were previously on `hashbangcode/vlad` to DDEV. It'd be nice to keep the same domain names I'm habituated to.

**Comment by rfay** [comment] 2018-05-21 19:58
I think this is mostly a duplicate of #834 (allow changing from .ddev.local), although that one just wants freedom of the TLD.

**Comment by mglaman** [comment] 2018-05-21 22:46
I would close this as a duplicate. It is a desire to customize `const DDevTLD`

**Comment by jeffsheltren** [comment] 2018-06-14 14:55
+1 for this. Some of our clients have SSO systems which require using the company's domain name in order for SSO to work on localdev (same as described in #834).

**Comment by testevez** [comment] 2018-07-10 21:29
I am watching this space for how to Configure the TLD (change from ddev.local to something else).

**Closed** 2018-07-13 13:04 UTC
Labels: actionable
