### ISSUE TITLE
ddev ssh fails on windows with .env file present, Docker Desktop 2.2.0.0

### ISSUE THREAD

**Issue by r3h6** [drud/ddev#2043] opened 2020-01-22 10:48 UTC
**Describe the bug**
ddev ssh
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[11544] Failed to execute script docker-compose

**To Reproduce**
Trouble is, ddev ssh still works for some projects.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10
 - Docker version: Docker version 19.03.5, build 633a0ea
 - Docker desktop: 2.2.0.0
 - ddev version: 1.12.1
 - config.yaml contents for the misbehaving project: See below
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? Yes, tried without them, still fails

**Additional context**
APIVersion: v1.12.1
name: esb
type: php
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""

**Comment by DaRealFreak** [comment] 2020-01-22 14:30
the issue is not related to ddev directly but to docker-compose version 1.25.2
related issue (with a working workaround included) of the docker/compose repository: https://github.com/docker/compose/issues/7169
the binary I've replaced my docker-compose with: https://github.com/docker/compose/releases/tag/1.24.1

**Comment by r3h6** [comment] 2020-01-22 14:43
Suggested workaround worked, thanks, closing issue

**Comment by rfay** [comment] 2020-01-22 14:44
Let's keep this open until everything about Docker 2.2.0.0 is resolved

**Comment by rfay** [comment] 2020-01-22 15:04
This seems to be a problem ONLY if a .env file is present, true? I tested and didn't have trouble, and https://github.com/docker/compose/issues/7169 seems to indicate that situation.

**Comment by DaRealFreak** [comment] 2020-01-22 15:07
yes, I also ran tests with new projects which all succeeded since I had no .env file.
only projects with a .env file failed,

**Comment by rfay** [comment] 2020-01-28 18:01
This is fixed in next version of docker, so I'm going to go ahead and close this one since there's nothing we can do about it.

**Closed by rfay** 2020-01-28 18:01 UTC
