### ISSUE TITLE
`ddev` command with Colima doesn't show shell commands like 'launch'

### ISSUE THREAD

**Issue by cmuench** [drud/ddev#3831] opened 2022-05-11 08:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
```
❯ ddev debug test
Running bash [-c /var/folders/q4/z9_k3vcx3v9g7d4crdy0vdtm0000gn/T/test_ddev.sh] 
OS Information: Darwin MacBook-Pro-von-Christian.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64
User information: uid=501(cmuench) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.19.2                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.3:v1.19.2 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0             
 docker           20.10.11                                
 docker-compose   v2.3.3                                  
 docker-platform  colima                                  
 mutagen          0.12.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.19.0                
 web              drud/ddev-webserver:v1.19.2             
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=750
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
no-bind-mounts=false

======= DOCKER info =========
docker location: lrwxr-xr-x  1 cmuench  admin  36 May  9 09:10 /opt/homebrew/bin/docker -> ../Cellar/docker/20.10.15/bin/docker
Docker Desktop Version: Print: Entry, ":CFBundleShortVersionString", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Docker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plistDocker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plist
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.12.0-beta7
--------------------------------------------------------------------------------
No synchronization sessions found
--------------------------------------------------------------------------------
mutagen is running on this system:
  501 86780     1   0 29Mar22 ??         0:38.69 mutagen daemon run
  501 79937 79917   0 10:35AM ttys000    0:00.00 grep mutagen
======= Docker Info =========
Docker platform: colima 
Colima version: 0.3.4 
Using docker context: default (unix:///Users/cmuench/.colima/docker.sock) 
docker-compose: v2.3.3 
Using DOCKER_HOST=unix:///Users/cmuench/.colima/docker.sock 
Docker version: 20.10.11 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.8G     23.5G     32.3G  42% /

The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers: 
CONTAINER ID   IMAGE          COMMAND     CREATED      STATUS    PORTS     NAMES
e0fbde71c4f7   2b0ab03212b0   "/bin/sh"   2 days ago   Created             phpstorm_helpers_IU-221.5080.210
Creating a new ddev project config in the current directory (/Users/cmuench/tmp/tryddevproject-14679) 
Once completed, your configuration will be written to /Users/cmuench/tmp/tryddevproject-14679/.ddev/config.yaml
 
Found a php codebase at /Users/cmuench/tmp/tryddevproject-14679 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-14679... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Network ddev-tryddevproject-14679_default  Created 
Container ddev-tryddevproject-14679-web  Started 
Container ddev-tryddevproject-14679-dba  Started 
Container ddev-tryddevproject-14679-db  Started 
Container ddev-router  Started 
Project type has no settings paths configured, so not creating settings file. 
Project type has no settings paths configured, so not creating settings file. 
Successfully started tryddevproject-14679 
Project can be reached at https://tryddevproject-14679.ddev.site https://127.0.0.1:49255 
+ curl --fail -I http://tryddevproject-14679.ddev.site
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Wed, 11 May 2022 08:36:08 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

+ '[' 0 -ne 0 ']'
+ set +x
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-14679'
```

### Expected Behavior

If I run "ddev" in a ddev enabled project then I want to see all custom command defined in `.ddev/commands` directory.

### Steps To Reproduce

1. Start colima
2. Install ddev 1.19.1
3. run "ddev" in a project with custom command. 
4. All commands are listed
5. Update to ddev 1.19.2
6. run "ddev" in a project with custom command. 
7. Custom commands are missing in the list (but can be executed)

**Comment by rfay** [comment] 2022-05-11 12:42
I think it does list them (and use them) but only after `ddev start`, right?

**Comment by cmuench** [comment] 2022-05-11 16:53
It's interesting. I just compiled ddev (master branch) and it's working.

**Comment by rfay** [comment] 2022-05-11 17:05
Take a look at `launch` - if launch shows up in the list, then shell commands are being recognized. All shell commands are equivalent, whether custom or not.

**Comment by rfay** [comment] 2022-05-11 17:06
Also, a command that doesn't show up there also shouldn't be usable.

**Comment by cmuench** [comment] 2022-05-11 17:13
I am just digging.
Looks like `app, err := ddevapp.GetActiveApp("")` is returning an error.
We do not have a good error handling in `cmd/ddev/cmd/commands.go:27

**Comment by cmuench** [comment] 2022-05-11 17:15
`err.Error()` return this:

error GetActiveAppGet "http://unix.sock/containers/json?all=1&filters=%7B%22label%22%3A%5B%22com.ddev.site-name%3Dnetz98-wordpress%22%2C%22com.docker.compose.service%3Dweb%22%5D%7D": dial unix /var/run/docker.sock: connect: no such file or directory

**Comment by rfay** [comment] 2022-05-11 17:19
With colima and ddev v1.19.2 on arm64 macOS I'm not seeing troubles. `ddev` shows "launch" and `ddev launch` works.

**Comment by cmuench** [comment] 2022-05-11 17:22
ok. It works with the source code of 1.19.1 on my machine (fresh compiled). Will try to figure out what the difference is.
So just ignore the issue.

**Comment by rfay** [comment] 2022-05-11 17:23
I imagine you've already stopped and restarted colima...

**Comment by cmuench** [comment] 2022-05-11 18:03
The issues is caused by a missing `DOCKER_HOST` variable.
A `export DOCKER_HOST="unix://${HOME}/.colima/docker.sock"` fixes the issue on my machine.

The `unix:///var/run/docker.sock` is a fallback.

see: vendor/github.com/fsouza/go-dockerclient/client.go:1091

```go
if dockerHost == "" {
    dockerHost = defaultHost
}
```

**Comment by cmuench** [comment] 2022-05-11 18:21
@rfay I am not sure if this is an ddev issue.
If the DOCKER_HOST variable is set to the colima docker.sock, then it works as expected.
IMHO the DOCKER_HOST variable is optional.

**Comment by rfay** [comment] 2022-05-11 18:27
Yeah, DOCKER_HOST is not needed if `docker context` is set. But *if* DOCKER_HOST is set, it wins. 

Happy to do a debugging screenshare call if that's useful to get this sorted.

**Comment by rfay** [comment] 2022-05-12 16:44
Did you figure anything out? Did you have  DOCKER_HOST setting in your environment?

**Comment by rfay** [comment] 2022-05-14 16:20
I'm going to close this for now, but happy to continue the conversation here or elsewhere. Did you have DOCKER_HOST set to something?

**Comment by cmuench** [comment] 2022-05-14 17:38
I had not set DOCKER_HOST. Without env variable set, it's broken on my M1 with Catalina.
Docker context set does not fix it.
With DOCKER_HOST env variable set, it's working.

**Comment by rfay** [comment] 2022-05-14 18:19
That's totally weird. I'm going to reopen this, but I can't reproduce and don't know what could be going on. 

What colima version are you using?

**Comment by rfay** [comment] 2022-05-15 12:49
I see in https://github.com/abiosoft/colima/pull/284 "Mirror docker socket path to previous location for backward compatibility
". 

I'll bet you had an existing context, and he moved it and it wasn't updating the context. If you're still able to recreate this I'll bet deleting the colima context would fix it.

**Comment by cmuench** [comment] 2022-05-15 13:18
Missing info:

colima version 0.3.4
git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae

runtime: docker
arch: aarch64
client: v20.10.15
server: v20.10.11

I will try out to re-create the context.

**Comment by cmuench** [comment] 2022-05-15 13:29
Deleting the colima context did not fix it.

**Comment by rfay** [comment] 2022-05-15 23:35
Could you please show `docker context inspect colima` - thanks. Also note that new colima release came out today, and that it requires removal of .colima and .lima.

**Comment by cmuench** [comment] 2022-05-16 07:35
```
[
    {
        "Name": "colima",
        "Metadata": {
            "Description": "colima"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///Users/cmuench/.colima/default/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/cmuench/.docker/contexts/meta/f24fd3749c1368328e2b149bec149cb6795619f244c5b584e844961215dadd16",
            "TLSPath": "/Users/cmuench/.docker/contexts/tls/f24fd3749c1368328e2b149bec149cb6795619f244c5b584e844961215dadd16"
        }
    }
]
```

Just updated to colima 0.4.0 and removed the .colima and .lima directory.
It's not fixed.

After that I tested again with ddev-1.19.1. Old ddev version works on my Mac.

**Comment by rfay** [comment] 2022-05-16 14:11
My `docker context inspect colima` is essentially the same.

I thought it would be a reasonable thing to `rm -r /Users/cmuench/.docker/contexts/meta/f24fd3749c1368328e2b149bec149cb6795619f244c5b584e844961215dadd16`, `docker context rm colima` and `colima stop && colima start` BUT I just discovered that in colima v0.4.? `colima stop` deletes the context and sets docker context back to default. I don't think it used to.

I note that your docker client is 20.10.15 and current in brew is 20.10.16. It might be worth updating to current but I don't expect that to mean anything.  I upgraded to the brew docker client 20.10.16 and still have no trouble. (Weirdly though, you have docker server 20.10.11 and current colima has 20.10.14. That may mean you didn't fully destroy your ~/.colima and ~/.lima folders...

Just as a checkpoint: I'm using `ddev start` and `ddev | grep launch` as a test, since your problem seems to be shell commands. I hope that matches what you're using. launch is a normal global shell command. 

I'm happy to do a debugging screenshare call with you, and you're also welcome to step through or add some debug output to https://github.com/drud/ddev/blob/b8328bc55286dbe0fd43885ac050d879a7773bd4/pkg/dockerutil/dockerutils.go#L87-L111 - that's where we get the connection to the docker server and determine what DOCKER_HOST should be. 

I so much appreciate you sticking with this and continuing to work on it. It's a gift to our whole community, because obviously if you have this, others will as well.

**Comment by cmuench** [comment] 2022-05-16 14:29
Thanks for investigating. I did a `rm -Rf ~/.lima` and `rm -Rf ~/.colima`.
I did not test with global command. I created a command in the `.ddev/commands/web` directory.
Maybe that's a difference.

**Comment by cmuench** [comment] 2022-05-16 14:41
colima version:
```
colima version 0.4.1
git commit: 5d39343b2bdc827e554d78ae306ebc836bf1d02c

runtime: docker
arch: aarch64
client: v20.10.16
server: v20.10.14
```

docker context inspect colima:
```json
[
    {
        "Name": "colima",
        "Metadata": {
            "Description": "colima"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///Users/cmuench/.colima/default/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/cmuench/.docker/contexts/meta/f24fd3749c1368328e2b149bec149cb6795619f244c5b584e844961215dadd16",
            "TLSPath": "/Users/cmuench/.docker/contexts/tls/f24fd3749c1368328e2b149bec149cb6795619f244c5b584e844961215dadd16"
        }
    }
]
```

No difference after update.

**Comment by rfay** [comment] 2022-05-16 14:59
And `ddev | grep launch` in a running project directory does *not* show the launch command right?

Your comment in https://github.com/drud/ddev/issues/3831#issuecomment-1124107405 sure seems to set us down the road of understanding the role of DOCKER_HOST and the `docker context`. There were absolutely changes in the order of getting the docker client in v1.19.2, because of some ugly results in various situations, but since I can't recreate your situation at this point, I can't chase.

**Comment by cmuench** [comment] 2022-05-17 07:56
@rfay Gotcha!
`ddev -h` shows the custom commands.

**Closed** 2022-05-21 00:35 UTC
Labels: quickfix
