### ISSUE TITLE
Update composer version

### ISSUE THREAD

**Issue by Graloth** [drud/ddev#2563] opened 2020-10-19 10:06 UTC
**Is your feature request related to a problem? Please describe.**
Composer has started throwing the following warning:
```
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
```

**Describe the solution you'd like**
I would like the composer version updated to the most recent 1.x release to be able to test with the same version as we're running in production and similar, and simply to remove the warning.

**Describe alternatives you've considered**
I considered just updating to 2.x but we have quite a few packages that are not compatible with composer 2.x and as such we can't do a direct update to it.

**Additional context**
There might be a discussion if the composer version should also be configurable similar to php version, that way a project can control itself what composer version to use, allowing people to use 2.x or 1.x depending on what the project needs.

**Comment by Graloth** [comment] 2020-10-19 11:15
Something to note is that it's still relatively easy to update the composer version inside a project's container by doing the following:
* `ddev ssh` - to go into the container
* `sudo composer self-update` - sudo is needed or the update fails due to file permission issues.

As of this writing this updated my composer to 1.10.15, yet I assume that if this is done in the future on an older composer version, it would update to 2.x which is not what I want.

I would love to see the composer version be configurable in the config.yaml, since the difference between 1.x and 2.x can be breaking changes for some projects.

**Comment by rfay** [comment] 2020-10-19 14:00
This is a duplicate of https://github.com/drud/ddev/issues/2383

But I wrote up a how-to in https://github.com/drud/ddev/issues/2383#issuecomment-712175038

Closing, ongoing conversation is better in the other issue

**Closed by rfay** 2020-10-19 14:00 UTC
