### ISSUE TITLE
Documentation: How to Connect ddev to Hosting Providers

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#298] opened 2017-06-07 17:12 UTC
## What happened (or feature request):

Request!

## What you expected to happen:

Given that we're still discussing how to support different hosting providers / PaaS solutions, it will be helpful to provide end-users with instructions on how to best connect ddev to a generic production environment. This could be focused on using things like drush (which has rsync and sql-sync capabilities) or other scripts/solutions on pulling databases and files.

Technically, this is already documented at a command level, but this would be more of a tutorial / quick start guide.

**Comment by rickmanelius** [comment] 2017-06-20 19:43
Related to #242

**Comment by beeradb** [comment] 2017-07-06 20:35
Duplicate of #369?

**Comment by rickmanelius** [comment] 2017-08-22 15:00
This is something that I think would be incredibly valuable for our agency partners that would like to begin using ddev more in their day to day, but need additional guidance/functionality to plug into their current hosting solution prior to there being a fully built 3rd party integration like we did with Pantheon.

Notably, I recently had a conversation with the newmedia devs, who are essentially working on a previous version of ddev that is hardcoded to work with their storage endpoint (an S3 bucket with encrypted files) containing drush archives.

What would be valuable is a simple script wrapper that would provide a simple intermediary between the core ddev functionality and the few steps they need to take to pull down that archive. It could be a simple matter of:
* End user specifies the client key.
* Search storage endpoint for the last archive.
* Perform a download (unless identical cached copy exists).
* Run `import-db` using additional flags to parse the drush archive.
* Run `import-files` using additional flags to parse the drush archive.

Once completed, we can get a few test users using this very quickly. It could be generic enough that the script could be modified for other hosting providers that essentially require downloading a drush archive from a known storage endpoint and importing from the drush archive pattern.

**Comment by rickmanelius** [comment] 2017-08-22 15:01
Updated the milestone to reflect that this is not a blocker for v1.0.0.

**Comment by rickmanelius** [comment] 2017-08-22 15:02
While the scope of this ticket (as it's currently written) is more a way to provide examples on how to wrap ddev to more easily connect with arbitrary hosting solutions, the following issue is a more compehensive strategy on how to create first class integrations https://github.com/drud/ddev/issues/122.

**Comment by rickmanelius** [comment] 2017-09-26 16:07
Hi @rfay and @nmccrory. This might be a low hanging fruit item that would prove valuable for hosting providers that don't have a full on integration. Perhaps @nmccrory takes this on this sprint?

**Comment by rfay** [comment] 2017-09-26 16:16
Well, one doesn't "connect" unless I'm missing the whole point. One downloads a db tarball and a files tarball, checks out a repo, starts ddev, and imports. Am I missing something?  This is the traditional old-timey way of local work on a site.

**Comment by jenlampton** [comment] 2018-05-18 00:37
I'd love to have a cleaner way to pull files and databases from remote sources. 

I prefer to use drush aliases and `rsync` to grab files. 

One of my sites has a HUGE pdf library. I don't want to download all the files (like I would get with a tarball) but instead only the images I need on the local copy of my site. Using `drush rsync` allows me to specify a sub-set of the files like `sites/default/files/images` or even `sites/default/files/images/gallery` so I can grab images for a single content type or field -- perfect for when I'm only working on styling one section of the site on my local.

**Comment by rfay** [comment] 2019-09-16 22:48
I don't think this is currently useful and hasn't had any recent discussion. Closing.

**Closed by rfay** 2019-09-16 22:48 UTC
Labels: actionable, needs docs
