### ISSUE TITLE
Drupal site does not preserve configuration entered during site installation

### ISSUE THREAD

**Issue by akshay-qed42** [drud/ddev#3978] opened 2022-07-08 07:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/akshay-qed42/071c0b9cacf9d969df317b0170cfc43b

### Current Behavior

I installed Drupal 9 instance with ddev. On install page I entered desired site name and email ID. On completing the installation, checked the **Basic site settings** page at `/admin/config/system/site-information`

But it's not preserving the configuration entered:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75740338/177934858-c803fe8e-aeaf-4d3c-8df9-0393b04511f2.png">

It shows Site name as Drupal whereas Email address field is blank.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/75740338/177934233-6d3095c9-1c5b-4334-9090-b2a4439c4b44.png">

### Expected Behavior

Ideally it should preserve the configurations and show appropriate site name and email address on **Basic site settings** page entered during installation process.

### Steps To Reproduce

1. Create a directory e.g. `mkdir drupal-9-site-settings-check`
2. Go inside that directory
3. Download Drupal 9 with composer command: `composer create-project drupal/recommended-project:9.5.x-dev .`
4. Run `ddev config`. Enter appropriate details.
5. Run `ddev start`
6. Open the generated link.
7. Proceed with site installation
8. After successful installation you will be shown home page as a logged in user.
9. Then check **Basic site settings** page at `/admin/config/system/site-information`

### Anything else?

It works well in Lando setup as well as LAMP stack.

**Comment by tyler36** [comment] 2022-07-08 07:29
@akshay-qed42

Thank you for the report. 

I followed your steps and was unable to reproduce the error.
Ie. When I visited `/admin/config/system/site-information`, it displayed the site name and email address I entered during site installation.

The offical quick start guide for Drupal is localed here: [https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-composer-setup-example](https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart)

I find it much quicker to get started. You can use switches to alter the site install command for your project. https://www.drush.org/latest/commands/site_install/

```shell
ddev drush site:install --account-mail=akshay@gmail.com --site-name="drupal-9-site-settings-check"  -y
```

View switches here: https://www.drush.org/latest/commands/site_install/

**Comment by akshay-qed42** [comment] 2022-07-08 08:33
Ok @tyler36 will try the official guide for Drupal installation.
Thanks for quick reply.

**Comment by rfay** [comment] 2022-07-08 13:38
Hi @akshay-qed42 - If this is a bug you discovered with the unreleased Drupal 9.5, it should be reported in the [Drupal issue queue](https://www.drupal.org/project/issues/drupal), it wouldn't have anything to do with DDEV.  Congrats on finding it, and please do search the issues there and if it's not yet reported, create one. You might also try it using gitpod.io.

Please link to the Drupal issue here when you find it or create it. 

I'll close this, but happy to continue the conversation here or elsewhere.

**Closed by rfay** 2022-07-08 13:38 UTC
