### ISSUE TITLE
ddev project name (and hostname) uniqueness should be enforced

### ISSUE THREAD

**Issue by rfay** [drud/ddev#136] opened 2017-04-10 23:34 UTC
## What happened (or feature request):

I tried a `ddev config` and used an existing 'name'. Then I did a `ddev start`. The new repo/ddev app took over the containers of the previously-existing app without warning.

## What you expected to happen:

I would expect that either
1. 'name' is *not* unique, where multiple apps named 'drupal8' could co-exist
or
2. uniqueness of names is enforced
or 
3. there's a "machine name" of an app name that is enforced to be unique

Anyway, I don't expect a `ddev start` in another repo to take over the containers already built for another app.

## How to reproduce it (as minimally and precisely as possible):

1. Config and start a container with the name 'abracadabra`
2. Go to another repo and config and start a container with the name 'abracadabra'

## Related source links or issues:

**Comment by tannerjfco** [comment] 2017-04-21 18:38
I think the best way to address this would be to check if the site name matches a site that is already running, exit with an error if one is found, and leave it to the user to resolve. I don't believe we should try to compensate by changing the name dynamically or anything like that, since changing the hostname can require more configuration (or db changes in wp's case), and we probably want to leave any such decisions up to the user.

**Comment by rfay** [comment] 2017-04-21 20:00
I fully support that approach (https://github.com/drud/ddev/issues/136#issuecomment-296270109)

**Comment by rickmanelius** [comment] 2017-04-25 15:08
I think this makes sense. I can see where edge cases might arise, and it might not be the smoothest experience to not just auto-increment the sitename with -N where N is a positive integer. That said, if someone is attempting to pull up multiple copies of a repo to work locally, it helps promote a best practice is they are naming the site with a -LABEL, so this provides us the ability to promote that practice with a suggestion and an exit.

+1 from me.

**Comment by rickmanelius** [comment] 2017-04-25 15:09
Also noting the need for a test to ensure this functionality works in the future.

**Comment by rickmanelius** [comment] 2017-04-25 15:11
I see this in the "Needs Review" column of our active sprint, but I'm not sure I see an open PR. Moving back to the TODO column.

**Comment by rfay** [comment] 2017-04-25 15:42
This is near done in https://github.com/drud/ddev/pull/169 @rickmanelius

**Comment by rickmanelius** [comment] 2017-04-25 15:45
I really wish github had a "Pull Request" column on the right. I see how I'm missing them now. Sorry about that.

**Comment by tannerjfco** [comment] 2017-04-28 22:05
Fixed with #169

**Comment by rickmanelius** [comment] 2018-01-24 21:15
I'm noting this a regression in the current stable release of v0.11.0. While testing functionality for ddev-ui, I am now able to have the same project name and starting a 2nd site effectively shuts down the containers of the previous running copy.

**Comment by rfay** [comment] 2018-01-24 23:13
I confirm that I can recreate this problem trivially. The new site takes over the namespace.

**Comment by rfay** [comment] 2018-05-14 16:35
This needs to be fixed, and also needs to take into account the multiple hostname feature if possible.

**Closed** 2018-05-25 23:46 UTC
Labels: actionable
