### ISSUE TITLE
Port 8036 (phpmyadmin dashboard) and frontend of a project are switched sometimes (wsl2)

### ISSUE THREAD

**Issue by iammati** [drud/ddev#2805] opened 2021-02-13 14:59 UTC
**Describe the bug**
Sometimes when running `ddev start` it shows in the frontend the phpmyadmin dashboard instead of my actual frontend, while the port `8036` - which is the actual default provided by DDEV  - is the frontend. Port race condition issue maybe?

**To Reproduce**
It only happens sometimes after running `ddev start`. Running simply `ddev restart` would resolve it but it's better to fix that in general I guess.

**Expected behavior**
That this shouldn't happen at all IMO.

**Screenshots**
![image](https://user-images.githubusercontent.com/41418763/107852889-6d2c8400-6e13-11eb-9f95-10c7fdee32cd.png)
![image](https://user-images.githubusercontent.com/41418763/107852895-761d5580-6e13-11eb-9d6b-33a70ed40080.png)
![image](https://user-images.githubusercontent.com/41418763/107852914-98af6e80-6e13-11eb-8542-74911e7cfddb.png)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10 Version 2004 (Build 19041.804)
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): Docker version 20.10.2, build 2291f61
- ddev version information: (See screenshot)
- config.yaml contents for the misbehaving project
```
name: contentbuilder.js
type: laravel
docroot: "public"
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: "2.0.9"
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
- > No, it's a new project without anything except Laravel. The issue also happens when booting sometimes my TYPO3 projects.

**Additional context**
Since it happens also on other project-types e.g. TYPO3, Laravel and plain PHP and the fact that it happens sometimes I'd say it's a race condition either or something similiar as in the containers are booting async - which is in fact faster for the performance for bootup time - but maybe worth taking a look into that..?

**Comment by iammati** [comment] 2021-02-13 15:07
Here the `ddev logs` output - couldn't find anything related to the ports nor to phpmyadmin at all though:

```
+ set -o errexit nounset pipefail
+ rm -f /tmp/healthy
+ DDEV_PHP_VERSION=8.0
+ DDEV_WEBSERVER_TYPE=nginx-fpm
+ '[' -n 8.0 ']'
+ update-alternatives --set php /usr/bin/php8.0
update-alternatives: using /usr/bin/php8.0 to provide /usr/bin/php (php) in manual mode
update-alternatives: warning: skip creation of /usr/share/man/man1/php.1.gz because associated file /usr/share/man/man1/php8.0.1.gz (of link group php) doesn't exist
+ ln -sf /usr/sbin/php-fpm8.0 /usr/sbin/php-fpm
+ export PHP_INI=/etc/php/8.0/fpm/php.ini
+ PHP_INI=/etc/php/8.0/fpm/php.ini
+ '[' '!' -z ']'
+ '[' -d /mnt/ddev_config/php ']'
+ '[' laravel = backdrop ']'
++ id -un
++ id -gn
+ printf '\nexport APACHE_RUN_USER=dev\nexport APACHE_RUN_GROUP=dev\n'
+ a2enmod access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex deflate dir env filter mime mpm_prefork negotiation reqtimeout rewrite setenvif status
Considering dependency authn_core for access_compat:
Module authn_core already enabled
Module access_compat already enabled
Module alias already enabled
Considering dependency authn_core for auth_basic:
Module authn_core already enabled
Module auth_basic already enabled
Module authn_core already enabled
Module authn_file already enabled
Module authz_core already enabled
Considering dependency authz_core for authz_host:
Module authz_core already enabled
Module authz_host already enabled
Considering dependency authz_core for authz_user:
Module authz_core already enabled
Module authz_user already enabled
Module autoindex already enabled
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
Module dir already enabled
Module env already enabled
Module filter already enabled
Module mime already enabled
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Enabling module mpm_prefork.
Module negotiation already enabled
Module reqtimeout already enabled
Enabling module rewrite.
Module setenvif already enabled
Module status already enabled
To activate the new configuration, you need to run:
  service apache2 restart
+ a2enconf charset localized-error-pages other-vhosts-access-log security serve-cgi-bin
Conf charset already enabled
Conf localized-error-pages already enabled
Conf other-vhosts-access-log already enabled
Conf security already enabled
Conf serve-cgi-bin already enabled
+ '[' nginx-fpm = apache-fpm ']'
+ '[' false = true ']'
+ disable_xdebug
Disabled xdebug
+ ls /var/www/html
+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache /mnt/ddev-global-cache/ddev-live
+ sudo mkdir -p /mnt/ddev-global-cache/bashhistory/contentbuilder.js-web
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /mnt/ddev-global-cache/ /home/dev/.ssh /home/dev/.drush /home/dev/.gitconfig /home/dev/.my.cnf
+ '[' -d /mnt/ddev_config/.homeadditions ']'
+ cp -r /mnt/ddev_config/.homeadditions/. /home/dev/
+ '[' -d /mnt/ddev_config/homeadditions ']'
+ cp -r /mnt/ddev_config/homeadditions/. /home/dev/
+ sudo mkdir -p /mnt/ddev-global-cache/mkcert
+ sudo chmod -R ugo+rw /mnt/ddev-global-cache/mkcert
+ mkcert -install
Using the local CA at "/mnt/ddev-global-cache/mkcert" ✨
The local CA is now installed in the system trust store! ⚡️

+ sudo CAROOT=/mnt/ddev-global-cache/mkcert mkcert -cert-file /etc/ssl/certs/master.crt -key-file /etc/ssl/certs/master.key contentbuilder.js.ddev.site localhost 127.0.0.1 127.0.0.1 web ddev-contentbuilder.js-web ddev-contentbuilder.js-web.ddev_default
Using the local CA at "/mnt/ddev-global-cache/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "contentbuilder.js.ddev.site"
 - "localhost"
 - "127.0.0.1"
 - "127.0.0.1"
 - "web"
 - "ddev-contentbuilder.js-web"
 - "ddev-contentbuilder.js-web.ddev_default"

The certificate is at "/etc/ssl/certs/master.crt" and the key at "/etc/ssl/certs/master.key" ✅

+ sudo chown 1000 /etc/ssl/certs/master.crt /etc/ssl/certs/master.key
+ echo 'Server started'
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
Server started
2021-02-13 14:47:59,400 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2021-02-13 14:47:59,400 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2021-02-13 14:47:59,400 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2021-02-13 14:47:59,405 INFO supervisord started with pid 1
2021-02-13 14:48:00,408 INFO spawned: 'child_exit_monitor' with pid 1715
2021-02-13 14:48:00,409 INFO spawned: 'php-fpm' with pid 1716
2021-02-13 14:48:00,410 INFO spawned: 'nginx' with pid 1717
2021-02-13 14:48:00,411 INFO spawned: 'mailhog' with pid 1718
[13-Feb-2021 14:48:00] NOTICE: fpm is running, pid 1716
[13-Feb-2021 14:48:00] NOTICE: ready to handle connections
[13-Feb-2021 14:48:00] NOTICE: systemd monitor interval set to 10000ms
2021-02-13 14:48:01,699 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-13 14:48:01,700 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-13 14:48:01,700 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-13 14:48:01,700 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by rfay** [comment] 2021-02-13 16:49
Are you using WSL2 or regular Windows?  If regular Windows, Docker Desktop Hyper-V or WSL2 back-end?

I think `docker ps -a` may be useful for this. When this happens, please provide the name of the project that the mishap is happening on, the URL where you see the wrong contents, and `docker ps -a` - thanks.

Is it possible you have phpmyadmin disabled for one or more projects, but enabled for others? That would be done with `omit_containers["dba"]` in the global ~/.ddev/global_config.yaml or in the project .ddev/config.yaml

There was a bug like this that was fixed (I thought) in ddev v1.16, https://github.com/drud/ddev/issues/2345 - it was pretty easy to reproduce.  I haven't heard of anything like that in v1.16. Please read that bug carefully and see if you can reproduce it there.

**Comment by rfay** [comment] 2021-02-13 16:54
Please make sure you don't have any custom configuration in ~/.ddev - Could you please `ls -lR ~/.ddev` for me?

**Comment by iammati** [comment] 2021-02-13 17:59
@rfay I'm using WSL2

Output of `docker ps -a` - can't reproduce the mishap for now but I'll try to catch it up next time!
![image](https://user-images.githubusercontent.com/41418763/107857121-ba691f80-6e2c-11eb-9aa8-923f1d394365.png)

> Is it possible you have phpmyadmin disabled for one or more projects, but enabled for others? That would be done with omit_containers["dba"] in the global ~/.ddev/global_config.yaml or in the project .ddev/config.yaml
No. There's no project I've disabled phpmyadmin at all, neither I've configured anything inside of the global `~/.ddev/global_config.yaml`.

> There was a bug like this that was fixed (I thought) in ddev v1.16, #2345 - it was pretty easy to reproduce. I haven't heard of anything like that in v1.16. Please read that bug carefully and see if you can reproduce it there.
As far as I understood I can reproduce it by simply doing a `ddev stop` and I'd still be able to access the phpmyadmin? If that's it, then no, I'm not able to reproduce it.

Here the output of `ls -lR ~/.ddev`:
![image](https://user-images.githubusercontent.com/41418763/107857250-a114a300-6e2d-11eb-929c-5e8d4aac07a7.png)

**Comment by rfay** [comment] 2021-02-13 18:09
Thanks - You can delete the obsolete ~/.ddev/router_compose.yaml and ~/.ddev/ssh-auth-compose.yaml, they're not used any more. Not relevant here though. 

When you make this happen again, please provide up these things as a new gist on gist.github.com:

* the misbehaving project's .ddev/.ddev-compose-base.yaml, .ddev/.ddev-compose-full.yaml,
*  ~/.ddev/router-compose.yaml and ~/.ddev/router-compose-full.yaml
* Do a `docker cp ddev-router:/etc/nginx/conf.d/ddev.conf /tmp` and provide that ddev.conf as well. 

I don't know how we're going to be able to figure it out without those. May be hard to grok with them. 

Feel free to ping me in any of the support channels (or here) if you want to look at this together on a zoom call. 

Please do make sure you've done a `ddev poweroff`, I'm sure you have, and that there are no existing containers after that, `docker ps -a` should show nothing.

**Comment by rfay** [comment] 2021-02-13 18:13
Oh... since you're using WSL2... is there any chance at all that you have something running on the Windows side? Did you ever use ddev on the Windows side? Is it possible there's ever a webserver running on the Windows side? Is it possible you have two WSL2 instances?

Windows WSL2 does some absolutely wonderful and magical things with networking to make WSL2 work. But there are some very confusing things that can happen. A process can be listening on the Windows side, but of course not inside WSL2. But if you use a browser on the Windows side... you're expecting the WSL2 results. 

The best way to sort out this kind of problem is to install a browser inside WSL2 and use X410 or similar X server to display it, then you can see exactly what's going on in WSL2 as opposed to the full system.

But if you don't want to do that (yet) just use curl on the Windows side and curl on the WSL2 side to verify that you're seeing the same thing.

**Comment by rfay** [comment] 2021-02-26 20:13
Yes @verdure-peuser please chase this down. It's most likely a WSL2 networking issue, or could be that you have ddev running on the Windows side. Please carefully rule those out, especially https://github.com/drud/ddev/issues/2805#issuecomment-778656404

**Comment by verdure-peuser** [comment] 2021-02-26 22:18
@rfay i'm running stock ubuntu, no wsl/windows. just ubuntu with docker and ddev installed. has'nt happened since the last restart, i'm still monitoring and waiting for it to happen again. when' i'll send you the information.

**Comment by rfay** [comment] 2021-02-27 01:02
@verdure-peuser if you could get `docker cp ddev-router:/etc/nginx/conf.d/ddev.conf /tmp` and get me the ddev.conf that might really help.

**Comment by rfay** [comment] 2021-03-08 13:39
The very best thing that would help is a set of steps to recreate this situation.

**Comment by verdure-peuser** [comment] 2021-03-08 14:33
@rfay strange, but since my last message it hasn't occured anymore. also haven't updated docker/ddev recently, still watching and will reply if it happens again.

**Comment by ErwinChatrer** [comment] 2021-03-11 13:17
Got the same issue today on mac bigsur 11.2.1
```
DDEV-Local version	v1.16.7                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba               	phpmyadmin:5                           
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0            
docker            	20.10.2                                
docker-compose    	1.27.4                                 
os                	darwin                                 
router            	drud/ddev-router:v1.16.2               
web               	drud/ddev-webserver:v1.16.7 
```
ddev stop/start fixed it for me.

**Comment by rfay** [comment] 2021-03-11 13:24
@ErwinChatrer there's a request for data and debugging and reproduction scenarios. If you still have this problem, could we do a zoom and look at it? https://github.com/drud/ddev/issues/2805#issuecomment-778655773

**Comment by bartlangelaan** [comment] 2021-03-29 14:12
I also have this problem currently (WSL2).
```
DDEV-Local version      v1.16.6
db                      drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba                     phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.16.0
docker                  20.10.5
docker-compose          1.25.0-rc4
os                      linux
router                  drud/ddev-router:v1.16.2
web                     drud/ddev-webserver:v1.16.6
```

When I run `docker cp ddev-router:/etc/nginx/conf.d/ddev.conf /tmp` the contents of `/tmp/ddev.conf` are:
<details><summary>ddev.conf contents</summary>
<pre><code>
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Default dhparam
# ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
client_max_body_size 0;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
    server_name _; # Catch-all for any server_name that is not matched in the config
    # Listen on all configured http ports + 80 (HTTPS_EXPOSE)
    # So that we can redirect any server_name that is invalid
    include /tmp/http_ports.conf;
    access_log /var/log/nginx/access.log vhost;
    error_page 503 @noupstream;
    location @noupstream {
        rewrite ^(.*)$ /503.html break;
        root /app;
    }
    location / {
        return 503;
    }
    location = /healthcheck {
        access_log off;
        return 200;
    }
}
server {
    server_name _; # Catch-all for any server_name that is not matched in the config
    # Listen on all configured https ports + 443 (HTTPS_EXPOSE)
    # So that we can redirect any server_name that is invalid
    include /tmp/https_ports.conf;
    access_log /var/log/nginx/access.log vhost;
    error_page 503 @noupstream;
    location @noupstream {
        rewrite ^(.*)$ /503.html break;
        root /app;
    }
    location / {
        return 503;
    }
    ## provide a health check endpoint
    location = /healthcheck {
        access_log off;
        return 200;
    }
    ssl_session_tickets off;
    ssl_certificate /etc/nginx/certs/master.crt;
    ssl_certificate_key /etc/nginx/certs/master.key;
}
        upstream dvgemdemo.ddev.site-80 {
        keepalive 100;
            # Container=ddev-dvgemdemo-web 172.18.0.5:80
            server 172.18.0.5:80;
        }
        upstream dvgemdemo.ddev.site-8025 {
        keepalive 100;
            # Container=ddev-dvgemdemo-web 172.18.0.5:8025
            server 172.18.0.5:8025;
        }
        upstream dvgemdemo.ddev.site-8036 {
        keepalive 100;
            # Container=ddev-dvgemdemo-dba 172.18.0.4:80
            server 172.18.0.4:80;
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 80 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-80;
                error_page 502 @brokenupstream;
            }
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 8025 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-8025;
                error_page 502 @brokenupstream;
            }
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 8036 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-8036;
                error_page 502 @brokenupstream;
            }
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 443 ssl http2 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            ssl_prefer_server_ciphers on;
            ssl_session_timeout 5m;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
                ssl_certificate /etc/nginx/certs/master.crt;
                ssl_certificate_key /etc/nginx/certs/master.key;
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-80;
                error_page 502 @brokenupstream;
            }
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 8026 ssl http2 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            ssl_prefer_server_ciphers on;
            ssl_session_timeout 5m;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
                ssl_certificate /etc/nginx/certs/master.crt;
                ssl_certificate_key /etc/nginx/certs/master.key;
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-8025;
                error_page 502 @brokenupstream;
            }
        }
        server {
            server_name dvgemdemo.ddev.site;
            listen 8037 ssl http2 ;
            access_log /var/log/nginx/access.log vhost;
            location @brokenupstream {
                rewrite ^(.*)$ /502.html break;
                root /app;
            }
            ssl_prefer_server_ciphers on;
            ssl_session_timeout 5m;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
                ssl_certificate /etc/nginx/certs/master.crt;
                ssl_certificate_key /etc/nginx/certs/master.key;
            location / {
                proxy_buffer_size   128k;
                proxy_buffers   4 256k;
                proxy_busy_buffers_size   256k;
                proxy_read_timeout 10m;
                proxy_http_version 1.1;
                proxy_pass http://dvgemdemo.ddev.site-8036;
                error_page 502 @brokenupstream;
            }
        }
</code></pre></summary>

**Comment by rfay** [comment] 2021-03-29 14:25
@bartlangelaan studied this nicely, and it turns out the current situation was dba= 172.18.0.5 and web= 172.18.0.4, but that's not what was shown in the generated nginx config, those are swapped, unless I'm confused. 

So some possibilities:
* docker's DNS gets confused
* docker's notification API gets confused and reports the wrong things.
* Our parsing in ddev-router is confused.

**Comment by bartlangelaan** [comment] 2021-03-29 15:31
In the generated ddev.conf, this config exists:

```
 upstream dvgemdemo.ddev.site-80 {
   keepalive 100;
   # Container=ddev-dvgemdemo-web 172.18.0.5:80
   server 172.18.0.5:80;
 }
```

However, as @rfay mentioned above, running `ping ddev-dvgemdemo-web` returns `172.18.0.4` (and phpmyadmin was running on `172.18.0.5`).

I have no experience with nginx, but according to [this documentation](http://nginx.org/en/docs/http/ngx_http_upstream_module.html) it is maybe possible to directly use hostnames instead of IP addresses in the configuration.

This would mean that this could possibly work:
```
 upstream dvgemdemo.ddev.site-80 {
   keepalive 100;
   server ddev-dvgemdemo-web:80;
 }
```

**Comment by rfay** [comment] 2021-04-01 23:29
@bartlangelaan 's suggestion was easy enough to implement, and if we properly understood his live-bug study, then #2913 should fix this. I'm going to leave this open though. The fix will be in v1.17 and will be in next RC, v1.17.0-rc3.

**Comment by iammati** [comment] 2021-04-24 21:46
Update: okay so, since the release of v1.17 (also updated to that version) the issue didn't occurred yet. Guess it's solved - for me at least. Would need some more users here to agree with that and in order to close this issue @verdure-peuser @bartlangelaan 
maybe you both could share your experiences in case one or both of you updated as well to v1.17 / 1.17.1 already.

**Comment by rfay** [comment] 2021-04-24 22:28
Hoping our luck holds out! @bartlangelaan 's idea was good, and hopefully it's prevented the confusion.

**Comment by bartlangelaan** [comment] 2021-04-25 21:34
I have also updated and not seen this issue since. So, I think we can close this issue until somebody reports otherwise.

**Comment by rfay** [comment] 2021-04-26 02:37
I'll close it for now and we'll reopen it if we see it pop up again. Thanks all!

**Closed by rfay** 2021-04-26 02:37 UTC
