### ISSUE TITLE
ddev command issues in composer post-create-project-cmd with ddev 1.18.2 (read /dev/stderr: bad file descriptor)

### ISSUE THREAD

**Issue by juban** [drud/ddev#3577] opened 2022-02-07 14:11 UTC
DDEV version    v1.18.2                                 
architecture    arm64                                   
db              drud/ddev-dbserver-mariadb-10.3:v1.18.2 
dba             phpmyadmin:5                            
ddev-ssh-agent  drud/ddev-ssh-agent:v1.18.0             
docker          20.10.12                                
docker-compose  v2.2.2                                  
mutagen         0.12.0                                  
os              darwin                                  
router          drud/ddev-router:v1.18.2                
web             drud/ddev-webserver:v1.18.2

**Describe the bug**
Some context:
We have PHP starter kits for CMS and frameworks containing framework settings, decencies, CI and ddev setups.
In order to install those, we leverage `composer create-project` command which trigger  `post-create-project-cmd` scripts.
As we need a specific ddev configuration provided by the starter kits themself, we can't use the custom `ddev composer create` command.
Commands will first launch ddev with `ddev start`, then run other ddev commands to initiate the project and the framework, `ddev yarn install` for example.
That was working like a charm with ddev 1.18.1 and lower, but no longer.

The bug (regression):
As of ddev 1.18.2 and higher, no matter which platform you're on (linux, Mac Intel or Mac M1), starting ddev will work but the remaining commands will fail with a `read /dev/stderr: bad file descriptor` error.

**To Reproduce**
Using ddev 1.18.2, install a PHP project using `composer create-project` containing a composer configuration like:
```
...
"type": "project",
...
"scripts": {
    "post-create-project-cmd": [
        "ddev start",
        "ddev yarn install",
...
```
Running that on ddev 1.18.2 will result in a `read /dev/stderr: bad file descriptor` on the `ddev yarn install` command.
(This has been tested on Linux, Mac Intel and Mac M1 arch).

**Expected behavior**
ddev commands should run without error.

**Comment by rfay** [comment] 2022-02-07 14:41
You must be running composer on the host, right, rather than using `ddev composer create`? I don't recommend mixing composer on the host with composer inside container, as they can be different versions, and different PHP versions, and different enabled PHP extensions.

You also don't say whether you have mutagen or what you may have set up, and you didn't run the requested script that would have told me those things, https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh

But I recommend doing some troubleshooting.

* What happens when you do these steps manually?
* What happens when you use  the recommended `ddev composer create` with a post-create just using yarn directly?
* Have you considered just using the `yarn install` as a ddev post-start?
* Do some pauses help?

Overall, I don't think the mixing of host-side composer and ddev is going to make you very happy in the end.

**Comment by juban** [comment] 2022-02-07 17:28
Yes, for the initial setup, we are running composer on the host, but only then.
As we tell composer to not consider the PHP version on host (`--ignore-platform-reqs`) and use a composer.lock to use specific dependancies, so far, that was working pretty well et we were happy about it for almost 2 years now ;)

Mutagen on or off doesn't make any difference regarding the issue.

Running the steps manually afterward works fine, no issues. Pauses in the post-create-project-cmd scripts doesn't help.

Issue with the ddev composer create is that we need to pass some unsupported flags like `--stability`, `--repository`, etc... resulting in a `Too many arguments` error.

**Comment by rfay** [comment] 2022-02-07 18:39
One thing that works really well for some people is to use `ddev composer create --no-install` and continue the no-install until a final `ddev composer install`. 

With NFS and colima I have seen some issues with composer and filesystem sync, and that may be what you're seeing. The --no-install approach might help you with those. You also might want to test and see if it does have to do with NFS.

**Comment by juban** [comment] 2022-02-08 08:34
I would be happy to find a suitable and clean solution using `ddev composer create` command but stuck on the following limitation:
I need to run something like `composer create-project --repository '{"type": "vcs", "url": "git@some-git-repo.git"}' --remove-vcs --prefer-dist --stability=dev "some/php-project"`. The repository part is important because we need to access some private repository. 

That kind of command won't run using the `ddev composer create` because the json payload quotes will be escaped (also, need one escape for the whole payload and one per key/values).

I can't see a solution using the `--no-install`, because I will need to specify the repository path somehow and, even if I find a way to do so (using `ddev ssh` for exemple), I won't be able to pull the project because the ddev config folder will already exists and the point is to preserve the one from the PHP project in the first place (which would probably not be an issue if I manage to run a `ddev composer create` command). Kind of chicken and egg situation :)

Sure, running composer command from the host is far from being optimal, but that's the only way to workaround the limitations. Once again, that was working just fine on previous ddev versions, but not anymore with ddev 1.18.2.

**Comment by jonaseberle** [comment] 2022-02-08 08:53
Isn't the `repositories` also copied from the packagist package repo that you are `create-project`ing?
You could also `ddev composer config repositories.foo vcs git@some-git-repo.git` in a second step.

It seems you want to employ a very integrated solution here. 
We've found [little recipes like this](https://github.com/TYPO3-Initiatives/structured-content-page-module#if-you-want-to-test-the-patch-locally-use-the-following-ddev-option) or [this](https://ddev.readthedocs.io/en/stable/users/cli-usage/#typo3-quickstart) to work well for users. The advantage of smaller steps being that you'll get better bug reports and that users are more in control and thus more "enabled" to environment-specific stuff themselves.

**Comment by rfay** [comment] 2022-02-08 14:43
@juban you still haven't said whether you're running NFS or mutagen or nothing, or even what OS you're working on, but because you say arm64 I'm going to guess Mac M1. Could you please run the script you were asked to run when filing this and post the results as a gist on gist.github.com? https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh

While I don't particularly like your method, the reason for the failure you're hitting is filesystem related, and can probably be fixed with a `ddev restart` and maybe a sleep.

**Comment by juban** [comment] 2022-02-08 15:01
@rfay Said that in the initial ticket in fact ^^
This has been tested on Linux, Mac Intel and Mac M1 setups. No NFS. Mutagen on or off doesn't make any difference regarding the issue (same `read /dev/stderr: bad file descriptor` error). Works well on ddev 1.18.1 and lower, issue only raise on ddev 1.18.2.
Would it help if I grant you an access on our repository so that you can test?

**Comment by rfay** [comment] 2022-02-08 16:13
Yes, if you give me access to the repo and explicit instructions I'll take a look.

**Comment by rfay** [comment] 2022-02-08 16:17
I have no idea in the world why this would be different between ddev v1.18.1 and v1.18.2.  Here are the commits, https://github.com/drud/ddev/compare/v1.18.1...v1.18.2

Are you able to recreate the difference between 1.18.1 and 1.18.2? You can `brew unlink ddev` and use `install_ddev.sh v1.18.1` to test.

Also, would appreciate if you could take a look at v1.19.0-alpha4.

**Comment by juban** [comment] 2022-02-08 17:29
@rfay Yes, we managed to verify the issue by downgrading to 1.18.0, 1.18.1 and upgrading to 1.18.2 again on the different architectures with same results every time (Linux, Mac Intel and Mac M1).
I did not tried the 1.19 beta yet, but will do right now and let you know.
Could you provide an email address so that I could grant you an access to our private Gitlab? Thank you so much for you help!

**Comment by juban** [comment] 2022-02-08 17:36
Same issue with v1.19 alpha I'm afraid.

**Comment by rfay** [comment] 2022-02-08 19:08
randy@randyfay.com, thanks.

It's wonderful that you can nail it down to v1.18.1..v1.18.2, because it shouldn't be hard to `git bisect`.

**Comment by juban** [comment] 2022-02-09 09:18
@rfay I've send you an invitation and an email with instructions to access a project on our Gitlab repository.
Let me know if you have and trouble with it and thanks again.

**Comment by rfay** [comment] 2022-02-11 00:50
I'm able to recreate the situation you describe with your instructions, thanks. However, if I then do a `ddev craft setup/welcome` manually it does fine. 

So if I do 
```
mkdir ~/tmp/x && cd ~/tmp/x
composer create-project simplonprod/craftcms-starter-kit --repository '{"type": "vcs", "url": "[git@gitlab.ecedi.fr](mailto:git@gitlab.ecedi.fr):simplonprod/devops/starter-kits/craftcms-starter-kit.git"}' --remove-vcs --ignore-platform-reqs --prefer-dist .
```

I do in fact get your same complaint
```
> ddev craft setup/welcome
read /dev/stderr: bad file descriptor
Failed to run craft setup/welcome: exit status 1
Script ddev craft setup/welcome handling the post-create-project-cmd event returned with error code 1
```

What's happening here is that the `craft` php script in the root of the repo is trying to use /dev/stderr (inside web container) and doesn't seem to like what it finds. 

It's not clear to me where `ddev craft setup/welcome` is even called. 

I think the right way to debug this is in a debugger or with printf-style debugging. But to do that you'll have to unbundle things so you can sort it out. Too much is happening here bundled in one (host-side) composer script. 

Did you try putting a sleep before the `ddev craft setup/welcome` ?

I'll try a git rebase to see if there's a hint of what might have been happening on the ddev side, but the bottom line is this isn't IMO a very sustainable way to build a site, and doing something with very obvious step-by-step scripting will help you understand it. And of course you already know that I don't like to depend on host-side resources like composer or php.

**Comment by rfay** [comment] 2022-02-11 01:10
I went to `git bisect` this problem based on your statement that ddev versions up through v1.18.1 did not have this problem, but both v1.18.0 and v1.18.1 do exactly the same for me using a macbook air M1 machine. 

I think you either have to just debug this one step at a time by making your scripts more visible and debuggable so you can do one thing at a time, or rethink how you're doing it. Of course I recommend doing it all inside the web container. But even there, you'll have to break apart the various functionalities so it's understandable and debuggable.

**Comment by rfay** [comment] 2022-02-12 22:41
I don't think it's the craft custom command that emits the error, I'm pretty sure it's the craft php cli that's doing it. But since `ddev craft` works fine afterward, it must be something about the context it's being run from the host. 

What I'd like to see happen is build a simple use-case of this with `ddev composer` or `ddev exec composer` so we can move past the unusual situation where composer is doing a bunch of stuff then running ddev and executing things inside web container. 

What you need to do at first is just

```
ddev composer create --repository '{"type": "vcs", "url": "git@some-git-repo.git"}' --remove-vcs --prefer-dist --stability=dev "some/php-project".
```

Is that correct?

**Comment by rfay** [comment] 2022-02-13 23:06
Experimenting with code for 
* https://github.com/drud/ddev/issues/2547

I used

`ddev composer create rfay/composer-private-test --repository '{"type": "vcs", "url": "git@github.com:rfay/composer-private-test.git"}'
`

And it was working fine. I'll have a pull request up before long, and perhaps this improved resiliency for the `ddev composer` and `ddev composer create` commands will help sort things out.

A couple of questions though:
1. Why do you need a private repository when working with something that appears to be something that could be public?
2. If you don't need a private repo, why not just put it on packagist?

**Comment by juban** [comment] 2022-02-14 08:37
First of all, thank you for the upcoming enhancement to allow quotes on ddev composer create command that will certainly help in many situations.
Secondly, regarding your question, there are numbers of reason why the project is not published publicly right now, but the main one is that there are a lot of things related to our in-house project workflow management (specific CI and deployment stuff mainly, specific README instructions not intended to be shared).

I've also made some progress on my side: I worked around the `ddev composer create` limitations by adding necessary internal repository and credentials into the `~/.ddev/homeadditions` folder (copying local host composer.json and auth.json files). That works fine as I don't have to specify the repository in the command anymore.
That way, I confirm that commands launched directly in the web container in the composer create project scripts, are running fine without any issues (craft, yarn, etc...).

However, to me, there is one major drawback to that approach: I need to setup an entire ddev configuration each time I want to install a composer project. We have a very specific ddev configuration which is provided by the project itself (a pretty long list of webimage_extra_packages, web_environment additional flags, custom commands and additional services). I think we could make an extra git repository for that matter to be able to rely on that specific configuration "template" and kind of copy/paste or export that project before launching the ddev composer create command, but that's far less convenient IMO.

Right now, as the initial command relies on a local ddev "temporary" config, the composer create project command will not have all the necessary requirements in order to run completely. Ideally (not sure it would be possible), once the project have been pulled from the repository by the create project command, a ddev restart should occur in order to use the one provided by the project.

Getting back to the initial issue, one thing I've been thinking of, could the `read /dev/stderr` error be related to ddev warnings? For instance, it the `yarn` command is overidden by a project custom command, a warning will be thrown each time a ddev command is called. Maybe that's why commands called within composer will work with ddev 1.18.1 and not 1.18.2?

**Comment by juban** [comment] 2022-02-14 11:15
Other drawback is that I can't use any git commands during the composer create project script as the tmp .git folder will not be copied to the project folder.

**Comment by rfay** [comment] 2022-02-14 14:15
Ah, I guess I thought it was a generic craft starter for anybody, I guess it's an in-house starter. 

If you have an inter-device move failure, that's odd. But in recent alphas, it doesn't move from /tmp, it has gone back to using a subdirectory and copying instead of moving. 

I also want to make sure you saw
* https://github.com/drud/ddev/issues/3594

And you may want to add to the suggestions there. 

Overall, I think we'll be able to get your `ddev composer create` going better, but the bottom line is that you're doing too much right now in a monolithic structure that isn't working out in a docker context, and I don't think I'm going to be able to help with it as it is. 

I do recommend the approach of using `--no-install` on the initial setup, and then doing the `ddev composer install` afterward.

But I'm going to go ahead and close this, as it seems to be something I'm not going to be able to directly help with. Happy to continue the conversation here or elsewhere, and happy to help architect other approaches.

**Closed by rfay** 2022-02-14 14:15 UTC

**Comment by rfay** [comment] 2022-02-16 21:28
I think this may be related to
* https://github.com/docker/compose/issues/9115

And it would make sense perhaps that you get that with some ddev versions. ddev v1.18.2 moved to docker-compose 2.2.2 for everybody. And I have docker-compose 2.2.3 in my environment, which would explain why you saw it when switching to v1.18.2 and I didn't. What version of docker-compose do you have (`docker-compose --version`)?

**Comment by rfay** [comment] 2022-02-17 00:17
Hmm... did you completely abandon this? I went back to test and it looks like a completely different thing.

**Comment by rfay** [comment] 2022-02-18 20:26
I was going to suggest `git bisect` on docker-compose, but I suspect this problem has existed in docker-compose throughout v2, which is a complete rewrite in golang (v1 was python).

If you're able to figure out a simpler way to reproduce it we might be able to debug the apparent problem in compose, 
* https://github.com/docker/compose/issues/9115

But right now, it's too complicated to sort out I think.

**Comment by rfay** [comment] 2022-03-23 13:41
Well that's nice! ddev v1.19.1 uses docker-compose v2.3.3, and they've been making some progress on stdout/stderr, even though there's still a ways to go.
