### ISSUE TITLE
"Failed to start [sitename]: db service health check timed out

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#805] opened 2018-04-23 17:26 UTC
## What happened (or feature request):
During `ddev start`, I received the following message: `"Failed to start [sitename]: db service health check timed out`

```
~/Sites/sitename [master*]$ ddev start
Starting environment for sitename... 
Creating ddev-sitename-db ... done
Creating ddev-sitename-dba ... done
Creating ddev-sitename-web ... done
 
Network ddev_default is external, skipping 
Creating ddev-router ... done
 
Failed to start sitename: db service health check timed out 
```

## What you expected to happen:
DDEV to start up as normal.

## How to reproduce this:
I'm not sure. I just updated to DDEV 0.17.0 (removed the docker-composer.yml, etc...), rebooted my machine, and the same thing happens. 

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

```
~/Sites/sitename [master*]$ ddev version
cli   	v0.17.0                        
web   	drud/nginx-php-fpm-local:v1.2.2
db    	drud/mariadb-local:v0.9.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.17.0                        
domain	ddev.local 
```

```
~/Sites/sitename [master*]$ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

```
~/Sites/sitename [master*]$ cat .ddev/config.yaml 
APIVersion: "1"
name: sitename
type: drupal8
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
provider: default
```

**Comment by rfay** [comment] 2018-04-23 23:43
This is normally https://github.com/drud/ddev/issues/748 - almost always caused by a corrupted database, most often in a larger database. Since v0.17.0, this is generally only caused by docker being shut down in an ungraceful way. Unfortunately, both Docker for WIndows and Docker for Mac shut down without notifying the container during upgrade, with a manual Docker exit, or at system shutdown. It can be avoided by stopping or remove-ing your projects before letting Docker exit.

To fix, `ddev remove --remove-data`, then `ddev start`.

To avoid this problem, don't let docker shut down while projects are running, as docker doesn't notify the db container, so it can't properly shut down.

**Comment by rfay** [comment] 2018-04-24 21:18
With your permission I'd like to close this in favor of #748, thanks for filing it!

**Closed by rfay** 2018-04-24 21:18 UTC
