### ISSUE TITLE
include additional services (like solr) in ddev describe

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#788] opened 2018-04-16 14:15 UTC
## What happened (or feature request):
I'm playing around with adding additional services to ddev, as described here:
https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr

I've followed the instruction, however the `ddev describe` is not showing the solr on the list of `Other services`

## What you expected to happen:
I would like to see url for accessing solr panel in the Other services section in ddev describe

**Comment by rfay** [comment] 2019-05-23 12:13
Closed https://github.com/drud/ddev/issues/1623 as a duplicate of this one.

**Comment by rfay** [comment] 2019-05-30 17:58
Related integration: clean up docker volumes owned by 3rd party services: https://github.com/drud/ddev/issues/1631

**Closed** 2020-04-08 03:18 UTC
Labels: Prioritized

**Comment by rfay** [comment] 2020-04-08 03:20
Finally @tmotyl ! Will be in v1.14
