### ISSUE TITLE
Add nfs support for web volume on macOS

### ISSUE THREAD

**Issue by RobertLang** [drud/ddev#1418] opened 2019-01-31 09:42 UTC
**Is your feature request related to a problem? Please describe.**
When I am working with macOS and docker I usually use nfs shares to speed up file access times.

**Describe the solution you'd like**
I would like to have a config flag to enable the usage of nfs volumes on macOS
```
# config.yaml
...
mac_nfs_enabled: true / false
```
**Describe alternatives you've considered**
At the moment I am using an additional docker-compose yaml file to overwrite the web volume basedir configuration with a nfs volume:
```
# docker-composer.mac.yaml
version: '3.6'

services:
  web:
    volumes:
      - basedir:/var/www/html

volumes:
  basedir:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/"
```

**Additional context**
`ddev start` would need to check if a nfs volume can be found. The documentation on how to enable nfs shares on macOS should be provided (or linked to) as well.

**Comment by rfay** [comment] 2019-01-31 13:35
This is a duplicate of #976, and there is a PR in review, Could you please try it out @RobertLang ? 

Testing instructions for the PR are at https://github.com/drud/ddev/pull/1396#issuecomment-457872155

**Closed by rfay** 2019-01-31 13:35 UTC
