### ISSUE TITLE
Add a command that will enable/disable an optional docker-compose service

### ISSUE THREAD

**Issue by mradcliffe** [drud/ddev#3269] opened 2021-09-27 19:34 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes we want to provide "heavier" services that not everybody would need to bring up a local development environment such as adding in chromedriver to run core Nightwatch tests (https://github.com/drud/quicksprint/pull/196, https://github.com/shaal/DrupalPod/pull/41)

Copying files around from example folders into `.ddev` seems like something that would be easier for a user to do with a command.

**Describe the solution you'd like**

Maybe we could have two additional commands:
1. Adds a service from some directory (path could include optional services directory or some optional services directory within the local .ddev config?) and starts the service.
2. Removes a service from .ddev by first stopping and then removing the container.

**Describe alternatives you've considered**

README documentation about copying files around.
Adding the service by default anyway despite some services needing extra resource allocation.

**Additional context**

**Comment by rfay** [comment] 2021-09-27 19:37
Is this a duplicate of https://github.com/drud/ddev/issues/3068 ? That one is more ambitious. Your use-case could easily be done with a contributed .ddev/commands/host command.

**Comment by mradcliffe** [comment] 2021-09-27 19:46
Yes, I think this is a more simpler duplicate of that. I was trying to search for optional and service. Feel free to close.

**Comment by rfay** [comment] 2021-09-27 19:48
I still like the simpler thing you're proposing. It might be a fine next step. The other one might really take some time to get together, and yours could be done with just a command. But also I think we should probably think of yours as a first step to the other maybe.

**Comment by gilbertsoft** [comment] 2021-09-27 19:53
For me this sound like a step after the mentioned issue. Here we are talking about conditional services which should only be takken into account if some condition applies e.g. an option is provided like `ddev start --include-service=foo_service`.

I have the same case for my projects also with the chromedriver which is only needed for the tests and I don't like to have always included namely for tests only. Currently I'm solving this by providing an example file which has to be renamed if needed, easily doable with a ddev custom command.

**Closed** 2022-03-03 22:10 UTC
