### ISSUE TITLE
Mention homebrew as an installation option in readme

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#443] opened 2017-08-24 14:04 UTC
## What happened (or feature request):
I'm walking through the Readme and noticed that the installation instructions do not mention Homebrew.

## What you expected to happen:
The readme should be updated to include mention of homebrew as an installation option.

**Comment by cyberswat** [comment] 2017-08-24 14:27
Just noting that there doesn't seem to be a mention of homebrew in the documentation site either.

**Comment by rfay** [comment] 2017-08-30 03:55
Duplicate of #434, right?

**Comment by rickmanelius** [comment] 2017-09-05 16:36
Yup, duplicate.

**Closed by rickmanelius** 2017-09-05 16:36 UTC
