### ISSUE TITLE
Feature Request: Add IPv6 support

### ISSUE THREAD

**Issue by julienloizelet** [drud/ddev#3947] opened 2022-06-29 01:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

For now, DDEV's containers 'ddev-router, web, custom services) have IPv4 IPs and I would like to be able to use IPv6 IPs.

### Describe the solution you'd like

As I saw in the discord channel (https://discord.com/channels/664580571770388500/991275383100014662) , it seems to be quite difficult to achieve this. And maybe it will be easier when traefik will be implemented.

**Comment by rfay** [comment] 2022-06-29 01:59
Thanks for making an issue. Don't know if you saw @gilbertsoft 's effort today, probably in response to your request in Discord, https://github.com/drud/ddev/pull/3945#issuecomment-1168940493 - There are so many problems :) And Traefik doesn't solve the many problems, WSL2 ipv6, Docker Desktop IPv6, etc.

**Comment by rfay** [comment] 2022-06-30 02:41
@julienloizelet could you please add to the issue the *why* of why you want ipv6?

**Comment by julienloizelet** [comment] 2022-06-30 04:53
> @julienloizelet could you please add to the issue the _why_ of why you want ipv6?

Well, I am working on a project whose main function is to implement "decisions" related to IP. In short, when a user accesses a website, we compare its IP to the one stored in some database, and we act accordingly (ban, propose the resolution of a captcha, bypass, etc.). And we aim to be fully compatible with IPv4 and IPv6 addresses.

Technically, we are using the [mlocati/ip-lib](https://github.com/mlocati/ip-lib)  package to handle IP and IP ranges.

I'm using DDEV to develop locally and also to test the code with GitHub actions : mainly integration tests (PHPUnit) and end-to-end test (with some js stuff). 

For now, I can not properly test with IPv6 as all DDEV IPs are IPv4.

Of course, I can use some  workaround (as modifying the code to replace the detected IP by a IPv6 one), but, in an ideal world, I would like to be able to handle IPv6 addresses without too many code tweaks.

That's why I'm asking for this feature :)

**Comment by rfay** [comment] 2022-06-30 15:23
Yeah, you absolutely need a mocking feature for that, and it's going to be terribly important to your project anyway. Even if DDEV had ipv6 support you'd still need mocking. It's like working on datetime or geoip lookups, you'll never be successful testing if you don't work a way to robustly simulate all the different options.

**Comment by julienloizelet** [comment] 2022-07-01 01:11
You are right. I have to enhance this mocking part of my project instead of waiting for DDEV IPv6 support.

Well, thus I don't really need this feature, and you can close it  or let it open if you guess it could be something to do in the future (as you prefer :) ) 

Thanks

**Comment by rfay** [comment] 2022-07-12 21:18
I'm going to close this for now, but I know that it will get reopened down the line when it is easier to implement on all the various platforms. Thanks for creating the issue!

**Closed** 2022-07-12 21:18 UTC

**Comment by mfickers** [comment] 2024-08-05 07:51
Postman at the moment refuses to connect via IPv4: https://github.com/postmanlabs/postman-app-support/issues/13052

This might be unintended behavior, but maybe you should re-evaluate if it's possible to add IPv6 support now. I suspect issues like these will only become more common.

**Comment by rfay** [comment] 2024-08-05 13:29
@mfickers I think this is a result of your setting for `localhost` on your machine. The IPV6 version is given first.  This is not an uncommon problem.

If you configure postman to use `<project>.ddev.site` instead of `localhost` you shouldn't have this problem.

If you need more direction, please open a new issue, but I don't think IPV6 support for DDEV is probably related to your current problem.

**Comment by mfickers** [comment] 2024-08-05 13:51
I appreciate your help. But as I've said this is an issue with Postman, not with DDEV.

These screenshots were taken less than a minute apart. I've just updated Postman and changed nothing else.

Postman 11.1.0:
![Bildschirmfoto 2024-08-05 um 15 45 38](https://github.com/user-attachments/assets/70532dc9-32a4-4758-ad91-f672a3277af3)

Postman 11.6.1:
![Bildschirmfoto 2024-08-05 um 15 46 20](https://github.com/user-attachments/assets/6fb3b356-c5bd-4e53-b868-e57acbc07e05)
![Bildschirmfoto 2024-08-05 um 15 50 19](https://github.com/user-attachments/assets/56fb910a-cd9d-4eaa-9424-fae61f081d12)

**Comment by rfay** [comment] 2024-08-05 15:06
Please try `ping localhost` - I think you'll find it uses the `::1`, which is the problem.
I suspect that if you remove the `::1 localhost` line from your hosts file it will resolve your issues. 

Some OSs are starting to prefer IPV6 for localhost, and that causes all kinds of troubles. In upcoming DDEV v1.23.4 we have tried to change the preference (inside container) to IPV4 because of this.

**Comment by mfickers** [comment] 2024-08-06 06:50
`ping localhost` resolves to `127.0.0.1` as expected. `curl` and any browser have no problem reaching the webserver via the URL or the IP. But for some reason Postman resolves the `https://mag2-dod.ddev.site` URL to `::1:443`, which isn't even valid as far is I can see.

I really appreciate you trying to help me, but this problem is really only limited to Postman. I've just commented on this issue to document this for others who might experience the same behavior and help reassess wether IPv6 support should have a higher priority now compared to when this issue was closed two years ago.

**Comment by rfay** [comment] 2024-08-06 13:53
OK, I'll let you go on your way. This obviously isn't related to this closed issue anyway. Note that if Postman resolves the https://mag2-dod.ddev.site URL to ::1:443 , there are multiple problems. First, "resolution" is about `mag2-dod.ddev.site`, not about the port or the URL. (`https` implies 443 by default). If your system or postman is somehow resolving `mag2-dod.ddev.site` to `::1` then it's doing something none of us could imagine because `*.ddev.site` *only* resolves in DNS to ipv4 127.0.0.1.
