### ISSUE TITLE
Terminus version in web container is out of date, prompts "A new terminus version is available"

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2328] opened 2020-06-23 18:43 UTC
**Describe the bug**
Terminus has updated and prompts users to update

**To Reproduce**
1. ssh into container
2. run `terminus`

CLI returns
```
A new Terminus version v2.4.0 is available.
You are currently using version v2.3.0.
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update
```

**Version and configuration information (please complete the following information):**
 - Mac OS 10.15.5 (19F101)
 - Docker version 19.03.8
 - ddev version 1.14.2

**Comment by rfay** [comment] 2020-06-23 21:13
Thanks so much for the report. 

terminus is already updated in the web container in ddev v1.15-alpha6, so that's one way to go. 

If you're on v1.14.2 and want to stay there until v1.15 stable comes out, you can put this content into .ddev/web-build/Dockerfile:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
```

This will work any time in the future that terminus gets out of date as well. Although the container build for a ddev version pulls the latest terminus, of course their release cadence might not be exactly the same as ddev's, so the Dockerfile snippet above will always fix it. 

I've also subscribed to terminus releases now, so that will help me find out earlier.

**Comment by rfay** [comment] 2020-06-26 00:23
Fixed in recent releases and upcoming v1.15, closing, happy to continue the conversation.

**Closed by rfay** 2020-06-26 00:23 UTC

**Comment by andy-blum** [comment] 2020-06-29 20:21
Just getting back to this. thanks for the Dockerfile snippet!

**Comment by meschenbaum** [comment] 2022-01-20 20:31
@rfay this seems to have re-appeared.

I tried adding your work-around above but without success. Looks like Debug is running even though my config has it disabled. Error messages below.

Version and configuration information:

Mac OS 12.1 (M1)
Docker version 20.10.11
ddev version 1.18.2

Errors:

```
$ ddev start
Starting D9-online-cu... 
Container ddev-ssh-agent  Creating 
Container ddev-ssh-agent  Created 
Container ddev-ssh-agent  Starting 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install]: exit code: 1 
Failed to start D9-online-cu: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-D9-online-cu docker-compose -f /Users/eschenbaumm/Sites/online-cu-starterkit/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#2 [drud/ddev-webserver:v1.18.2-D9-online-cu-built internal] load build definition from Dockerfile
#2 sha256:114e32d155e0022a5d6bcc591752252e048fce3a2541720049b26f6e8c34ae45
#2 transferring dockerfile: 764B done
#2 DONE 0.0s

#1 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built internal] load build definition from Dockerfile
#1 sha256:45a32b011afe606ab7e352c1f83c62ad0150ba12381321b3186854aad5879ae4
#1 transferring dockerfile: 408B done
#1 DONE 0.0s

#3 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built internal] load .dockerignore
#3 sha256:45f9d77dc1ff82d9d930d773b7998058e4fab345cc049a4d209b70d64a3ca480
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [drud/ddev-webserver:v1.18.2-D9-online-cu-built internal] load .dockerignore
#4 sha256:b3ca95d043c73214eb2d694d97c6770b51377d86dd0cad5592238994ec0e375e
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.3:v1.18.2
#5 sha256:6cd0388ecc772ba228c3186d51ef47382bb6290942d199ff376bd4b65c3949a5
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.3:v1.18.2
#6 sha256:07cf94b9ef82d7de9418dd3d61ff948d037827571311e0b6ee28310811993785
#6 DONE 0.0s

#7 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built 2/2] RUN (groupadd --gid 1936919285 "eschenbaumm" || groupadd "eschenbaumm" || true) && (useradd  -l -m -s "/bin/bash" --gid "eschenbaumm" --comment '' --uid 20961030 "eschenbaumm" || useradd  -l -m -s "/bin/bash" --gid "eschenbaumm" --comment '' "eschenbaumm" || useradd  -l -m -s "/bin/bash" --gid "1936919285" --comment '' "eschenbaumm")
#7 sha256:f53a3b3db5b521ad475d0acbaf281749d8a3e2fe1b01c3d47aa591bc05dc031e
#7 CACHED

#9 [drud/ddev-webserver:v1.18.2-D9-online-cu-built internal] load metadata for docker.io/drud/ddev-webserver:v1.18.2
#9 sha256:a0e956ac08d976a1bd62986acb66c5973b95c8670ba8b5501b6de645ddf31d12
#9 DONE 0.0s

#10 [drud/ddev-webserver:v1.18.2-D9-online-cu-built 1/4] FROM docker.io/drud/ddev-webserver:v1.18.2
#10 sha256:5956969c604416a239f364d769d02ec1133a7164e3d0c156bdeb152508133b04
#10 CACHED

#8 [drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built] exporting to image
#8 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#8 exporting layers done
#8 writing image sha256:d3718cea1ac245212a91a2e019d886e3242a3b814ec3446de9a79e8349d648ac done
#8 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.18.2-D9-online-cu-built done
#8 DONE 0.0s

#11 [drud/ddev-webserver:v1.18.2-D9-online-cu-built 2/4] RUN curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
#11 sha256:728b0078c8bc697a9f9c285db660992100f9b01b501abc9576756170a92330c0
#11 0.759 Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9000 (through xdebug.client_host/xdebug.client_port) :-(
#11 0.767 Installing Terminus...
#11 0.781 <warning>You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug</warning>
#11 1.077 <warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>
#11 10.23 Using version ^3.0 for pantheon-systems/terminus
#11 10.23 ./composer.json has been created
#11 10.32 Loading composer repositories with package information
#11 10.52 <warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>
#11 10.53 Updating dependencies (including require-dev)
#11 26.01 Package operations: 45 installs, 0 updates, 0 removals
#11 26.01   - Installing symfony/polyfill-ctype (v1.24.0): Downloading (100%)         
#11 26.62   - Installing symfony/polyfill-mbstring (v1.24.0): Downloading (100%)         
#11 27.23   - Installing twig/twig (v3.3.7): Downloading (100%)         
#11 28.00   - Installing symfony/deprecation-contracts (v2.5.0): Downloading (100%)         
#11 28.49   - Installing symfony/yaml (v5.4.2): Downloading (100%)         
#11 29.12   - Installing symfony/polyfill-php80 (v1.24.0): Downloading (100%)         
#11 29.61   - Installing symfony/process (v5.4.2): Downloading (100%)         
#11 30.23   - Installing symfony/finder (v5.4.2): Downloading (100%)         
#11 30.84   - Installing symfony/polyfill-intl-normalizer (v1.24.0): Downloading (100%)         
#11 31.45   - Installing symfony/polyfill-intl-grapheme (v1.24.0): Downloading (100%)         
#11 32.01   - Installing symfony/string (v5.4.2): Downloading (100%)         
#11 32.68   - Installing psr/container (1.1.2): Downloading (100%)         
#11 33.19   - Installing symfony/service-contracts (v2.5.0): Downloading (100%)         
#11 33.69   - Installing symfony/polyfill-php73 (v1.24.0): Downloading (100%)         
#11 34.18   - Installing symfony/console (v5.4.2): Downloading (100%)         
#11 34.96   - Installing rogervila/array-diff-multidimensional (2.1.0): Downloading (100%)         
#11 35.55   - Installing psr/log (1.1.4): Downloading (100%)         
#11 36.10   - Installing monolog/monolog (2.3.5): Downloading (100%)         
#11 36.85   - Installing justinrainbow/json-schema (5.2.11): Downloading (100%)         
#11 37.45   - Installing psr/http-message (1.0.1): Downloading (100%)         
#11 38.05   - Installing psr/http-client (1.0.1): Downloading (100%)         
#11 38.57   - Installing ralouphie/getallheaders (3.0.3): Downloading (100%)         
#11 39.08   - Installing psr/http-factory (1.0.1): Downloading (100%)         
#11 39.58   - Installing guzzlehttp/psr7 (2.1.0): Downloading (100%)         
#11 40.22   - Installing guzzlehttp/promises (1.5.1): Downloading (100%)         
#11 40.79   - Installing guzzlehttp/guzzle (7.4.1): Downloading (100%)         
#11 41.48   - Installing czproject/git-php (v4.0.2): Downloading (100%)         
#11 42.24   - Installing psr/event-dispatcher (1.0.0): Downloading (100%)         
#11 42.73   - Installing symfony/event-dispatcher-contracts (v2.5.0): Downloading (100%)         
#11 43.25   - Installing symfony/event-dispatcher (v5.4.0): Downloading (100%)         
#11 43.90   - Installing dflydev/dot-access-data (v1.1.0): Downloading (100%)         
#11 44.45   - Installing grasmash/expander (1.0.0): Downloading (100%)         
#11 45.06   - Installing consolidation/config (2.0.2): Downloading (100%)         
#11 45.74   - Installing consolidation/site-alias (3.1.3): Downloading (100%)         
#11 46.49   - Installing symfony/filesystem (v5.4.0): Downloading (100%)         
#11 47.05   - Installing league/container (3.4.1): Downloading (100%)         
#11 47.73   - Installing composer/semver (3.2.7): Downloading (100%)         
#11 48.33   - Installing consolidation/self-update (2.0.3): Downloading (100%)         
#11 48.98   - Installing consolidation/output-formatters (4.2.1): Downloading (100%)         
#11 49.69   - Installing consolidation/log (2.0.4): Downloading (100%)         
#11 50.42   - Installing consolidation/annotated-command (4.5.1): Downloading (100%)         
#11 51.17   - Installing consolidation/robo (3.0.7): Downloading (100%)         
#11 52.07   - Installing consolidation/filter-via-dot-access-data (2.0.2): Downloading (100%)         
#11 52.86   - Installing consolidation/comments (1.0.2): Downloading (100%)         
#11 53.55   - Installing pantheon-systems/terminus (3.0.4): Downloading (100%)         
#11 55.37 symfony/service-contracts suggests installing symfony/service-implementation
#11 55.37 symfony/console suggests installing symfony/lock
#11 55.37 monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
#11 55.37 monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
#11 55.37 monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
#11 55.37 monolog/monolog suggests installing elasticsearch/elasticsearch (Allow sending log messages to an Elasticsearch server via official client)
#11 55.37 monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
#11 55.37 monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
#11 55.37 monolog/monolog suggests installing ext-mongodb (Allow sending log messages to a MongoDB server (via driver))
#11 55.37 monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server (via library))
#11 55.37 monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
#11 55.37 monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
#11 55.37 monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
#11 55.37 guzzlehttp/psr7 suggests installing laminas/laminas-httphandlerrunner (Emit PSR-7 responses)
#11 55.37 symfony/event-dispatcher suggests installing symfony/dependency-injection
#11 55.37 symfony/event-dispatcher suggests installing symfony/http-kernel
#11 55.37 consolidation/output-formatters suggests installing symfony/var-dumper (For using the var_dump formatter)
#11 55.37 consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
#11 55.37 consolidation/robo suggests installing totten/lurkerlite (For monitoring filesystem changes in taskWatch)
#11 55.37 consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
#11 55.37 consolidation/robo suggests installing natxet/cssmin (For minifying CSS files in taskMinify)
#11 55.39 Writing lock file
#11 55.39 Generating autoload files
#11 55.41 
#11 55.43                                                                                              
#11 55.43   [Symfony\Component\Filesystem\Exception\IOException]                                       
#11 55.43   Failed to create symbolic link from "//vendor/bin/terminus" to "/usr/local/bin/terminus".  
#11 55.43                                                                                              
#11 55.43 
#11 55.43 install [--bin-dir [BIN-DIR]] [--install-dir [INSTALL-DIR]] [--install-version [INSTALL-VERSION]]
#11 55.43 
#11 ERROR: executor failed running [/bin/sh -c curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install]: exit code: 1
------
 > [drud/ddev-webserver:v1.18.2-D9-online-cu-built 2/4] RUN curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install:
------
', stderr='failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c curl -ssL -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install]: exit code: 1' ```

**Comment by rfay** [comment] 2022-01-20 22:31
Are you having trouble with the bundled version of terminus in 18.2, or are you just trying to get rid of the prompt? 

What I would probably do if the prompt was annoying me would be to put a .ddev/web-build/Dockerfile with
```Dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN terminus self-update && chmod ugo+rwx /usr/local/bin/terminus
```

I probably didn't know this a year and a half ago :)

**Comment by meschenbaum** [comment] 2022-01-25 20:32
Thanks @rfay,

I was assuming the Docker Build was adjusted to pull the latest terminus upon build. Mine is not doing that and didn't know if it was a bug or by design.

Right now my versions are a full version behind so the notice is appearing: 
```
[notice] A new Terminus version v3.0.4 is available.
You are currently using version v2.6.2.
You can update Terminus by running:
terminus self:update
```

So is it safe to say that adding the run command, you mentioned above, the standard practice till another DDEV major version is released?

**Comment by rfay** [comment] 2022-01-25 20:56
When a ddev release is cut, the current terminus is added to the web container. It doesn't auto-update in the meantime. 

It's probably not that good an idea to update just because software pesters you to do so :)

Please try the Dockerfile suggested and see if it helps.
