### ISSUE TITLE
Hosts mapping breaks Vagrant NFS mounts

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#1489] opened 2019-03-08 19:14 UTC
**Describe the bug**

When using DDEV, Vagrant cannot mount to NFS and causes this issue: https://github.com/hashicorp/vagrant/issues/9666

Why? because attaches its hostnames to the `127.0.0.1 localhost` row. Vagrant freaks out if this row has any other information on it.

**To Reproduce**
1. Configure a ddev project and start it.
2. Start a DrupalVM project
3. See this

```
==> local-example: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.88.1:/Users/mglaman/thinger/project /var/www/drupal

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

**Expected behavior**
Vagrant "just works"

**Comment by andrewfrench** [comment] 2019-03-08 19:49
Thanks for reporting this @mglaman, let me get DrupalVM up and running locally and see if I can reproduce this.

**Comment by andrewfrench** [comment] 2019-03-08 20:58
Alright - this is my first experience with DrupalVM, so let me know if I'm doing something unusually or if your setup is different, but I was able to start DrupalVM and navigate to the default home page with a "dirty," ddev-modified /etc/hosts with the following:

- Vagrant v2.2.4
- DrupalVM v4.9.2
- VirtualBox v6.0.0
- MacOS 10.14.3

Here's what my /etc/hosts file looks like after starting DrupalVM:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost composertest.ddev.local 1402.ddev.local 1434.ddev.local 1368.ddev.local 1386.ddev.local 1481.ddev.local 1486.ddev.local 1485.ddev.local
255.255.255.255	broadcasthost
::1             localhost 

192.168.88.88  drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
192.168.88.88  www.drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
192.168.88.88  adminer.drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
192.168.88.88  xhprof.drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
192.168.88.88  dashboard.drupalvm.test  # VAGRANT: 65d838f7023ba62c81bac261a9828ffe (drupalvm) / f433c65e-a49c-4dd5-aed8-ca258530ee4b
```

The first test was without Docker or a DDEV project running, so I `vagrant destroy`-ed the VM, started Docker, and `ddev start`-ed a project. Running `vagrant up` again successfully started DrupalVM and I could access the page at `drupalvm.test`. Am I skipping over any important preconditions or is my setup significantly different from yours?

**Comment by mglaman** [comment] 2019-03-08 23:50
I'm going to guess my Macbook might be fubar when it comes to VirtualBox + Vagrant + NFS, then :)

That sounds like the proper setup.

**Comment by andrewfrench** [comment] 2019-03-09 00:10
Sounds good - I'll close this issue for now, but feel free to ping us again if you find any more concrete steps to reproduce. Thanks!

**Closed by andrewfrench** 2019-03-09 00:10 UTC

**Comment by rfay** [comment] 2019-03-09 00:14
@mglaman remember that /etc/exports must not have overlaps, and that's likely with default vagrant setup.
