### ISSUE TITLE
Support Composer 2 in ddev

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2383] opened 2020-07-15 18:45 UTC
Composer 2 is almost here, and lots of people would like to try it out. See @ultimike's [blog](https://www.drupaleasy.com/blogs/ultimike/2020/07/composer-20-alpha2-performance-comparison?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+DrupalEasy+%28DrupalEasy%29) and [PHPWatch article](https://php.watch/articles/composer-2)

We plan to have Composer 2 in the web container as soon as it's released, but we'd love to have your reports right now about how it works for you, and any information about compatibility issues.

You can already use Composer 2 with DDEV-Local, there are two different ways.

1. `ddev exec`: Just try it out (and lose it when you stop the project): `ddev exec sudo composer self-update --snapshot` - then you can use `ddev composer` (or composer inside the web container) as long as the session lasts (until you `ddev stop` or `ddev poweroff` or whatever. 
2. add-on Dockerfile: Add this .ddev/web-build/Dockerfile and `ddev start` - you'll have composer 2 every time you start the project:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN composer self-update --snapshot 
```
3. Post-start hook: Add this to your .ddev/config.yaml and composer will be updated on every start (a bit slower than the second option, which only happens once instead of on every start)
```
hooks:
 post-start:
   - exec: sudo composer self-update --snapshot
```

**Comment by heddn** [comment] 2020-07-21 17:45
I tested the self-update process recently while developing a v2 composer plugin. Seemed to work fine. But there are still a lot of plugins that don't support it yet. Have we considered having a `composer` and `composer2` command as distinct options for this bridge time?

While I see some benefit to that, it also isn't clear how long we'd have to keep both and its always easy to add something and more difficult to remove it later.

**Comment by MrPaulDriver** [comment] 2020-09-12 15:12
I tried it out with suggestion 1.) but it didn't appear to be fully compatible with cweagans/composer-patches

For example:

ddev composer require drupal/bootstrap
Using version ^3.23 for drupal/bootstrap
./composer.json has been updated
Running composer update drupal/bootstrap
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cweagans/composer-patches 9999999-dev, found cweagans/composer-patches[dev-master] but it conflicts with another require.

Use the option --with-all-dependencies to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You are using a snapshot build of Composer 2, which may be the cause of the problem. Run `composer self-update --stable` and then try again. In case it solves the problem, please report an issue mentioning Composer 2.

**Comment by BalintCsuthy** [comment] 2020-09-13 18:39
The latest cweagans/composer-patches, version 1.6.7 is not compatible with composer 2. 
https://packagist.org/packages/cweagans/composer-patches
`composer-plugin-api: ^1.0`

But the the fix (composer 2 compatibility) is already committed.
So for now, you need "cweagans/composer-patches": "dev-master" in your composer.json file to use it with composer 2.

**Comment by BalintCsuthy** [comment] 2020-09-13 18:50
> Have we considered having a `composer` and `composer2` command as distinct options for this bridge time?

In that case `composer1` command is needed also, as the `composer` command should default to v2 soon.

**Comment by rfay** [comment] 2020-09-15 02:57
I'm assuming that both composer1 and composer2 will need to be bundled. Probably composer2 will have to be a separate option for some time, because there will be many packages that are incompatible for quite some time.

**Comment by rfay** [comment] 2020-09-24 19:58
I like the idea of adding an option into .ddev/config.yaml that will install composer 2 if desired (just using the temp Dockerfile technique, same as webimage_extra_packages) and then gradually move it to where composer 2 is the default.

**Comment by rfay** [comment] 2020-09-27 17:25
Ooops, the idea in https://github.com/drud/ddev/issues/2383#issuecomment-698557484  would be incompatible with uses of Dockerfile, which wouldn't be acceptable.

**Comment by rfay** [comment] 2020-10-19 13:57
Since a new composer version has just dropped people are fussing about the version again, see #2563, I should mention these things:

1. composer is updated in ddev on every new release
2. You can easily update it any time with either a .ddev/web-build/Dockerfile or a post-start hook
3. You can pin the version that you use (best for teams)

So:

.ddev/web-build/Dockerfile:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN composer self-update
```

That runs only once (on image build), and may result in different versions for your team depending on when they do their first `ddev start`

so better is
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN composer self-update 1.10.15
```

or for composer 2:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN composer self-update 2.0.0-RC2
```

You can also do the same with a post-start hook, but then it runs on every start

**Closed** 2020-10-20 12:14 UTC

**Comment by mightyselwyn** [comment] 2020-12-08 14:17
Relevant and useful article: Preparing your site for Composer 2

https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2

**Comment by rfay** [comment] 2020-12-08 14:22
Just a followup note that composer 2 is fully supported in ddev v1.16. `ddev config --composer-version=2` for example, followed by `ddev start`. The default composer version remains v1.

**Comment by a-r-m-i-n** [comment] 2020-12-13 11:12
Or add 
```
composer_version: "2"
```
to your config.yaml

**Comment by rfay** [comment] 2020-12-13 12:43
Those are the same thing @a-r-m-i-n 😄

**Comment by a-r-m-i-n** [comment] 2020-12-13 13:38
I know. But the Syntax is not the same (dash vs. underscore) so I thought it does not hurt, to mention this.

**Comment by rfay** [comment] 2020-12-13 13:48
I've never quite figured out why all the items in config use underscores but we use dashes in the config commands :)

**Comment by mhuber84** [comment] 2021-02-16 10:50
Hi, is there a way to make composer 2 the default for my whole system? So I can downgrade to composer 1 only if needed?

**Comment by rfay** [comment] 2021-02-16 13:16
Hi @mhuber84 for now, composer 1 is the default, because composer 2 still breaks lots of people's builds. I'd like composer 2 as default also. It's possible the time is near.

For now, just `ddev config --composer-version=2` on either an existing or new project.

**Comment by akalata** [comment] 2021-05-26 20:20
It may be worth noting that if this configuration isn't getting picked up, one of your packages may be specifying composer1. I just ran into this with `drupal/core-dev` 8.x specifying `^1.9.1`.

**Comment by jameswilson** [comment] 2021-06-14 17:33
@rfay Now that composer 2 is the default, is there a way to downgrade ddev-local to composer 1? 

I just tried `ddev config --composer-version=1`  but it didn't make any changes in the .ddev folder to files that are committed to the repo (I don't know if it might have modified files that are excluded via gitignore).

```
❯ ddev composer -- --version
Composer version 2.0.13 2021-04-27 13:11:08

❯ ddev config --composer-version=1
You are reconfiguring the project at /Users/jameswilson/App/MYAPP.
The existing configuration will be updated and replaced.
Found a drupal8 codebase at /Users/jameswilson/App/MYAPP/web
Ensuring write permissions for myapp
Existing settings.php file includes settings.ddev.php
Configuration complete. You may now run 'ddev start'.

❯ ddev composer -- --version
Composer version 2.0.13 2021-04-27 13:11:08
```

**Comment by rfay** [comment] 2021-06-14 17:41
You have to do a `ddev start` after making the change.

**Comment by jameswilson** [comment] 2021-06-14 18:50
Thanks.  That worked. Brilliant!
```
$ ddev composer -- --version
Composer version 2.0.13 2021-04-27 13:11:08
$ ddev config --composer-version=1
$ ddev restart
$ ddev composer -- --version
Composer version 1.10.22 2021-04-27 13:10:45
```

**Comment by asecondwill** [comment] 2022-09-07 16:12
Is it possible to configure composer 2.2 ?  

`Composer 2.3.0 dropped support for PHP <7.2.5 and you are running 5.6.40-57+0~20211119.60+debian11~1.gbp8a9bd1, please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.`


but setting 
`composer_version: "2.2"`
But after ddev restart its still using 2.3

```
 ddev composer -- --version                                                                                                                                                    ⏎ ✖ ✹ ✚
Composer 2.3.0 dropped support for PHP <7.2.5 and you are running 5.6.40-57+0~20211119.60+debian11~1.gbp8a9bd1, please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.
composer [--version] failed, composer command failed: exit status 1. stderr=
```

**Comment by rfay** [comment] 2022-09-07 16:25
Please open new issues for new questions, but current ddev supports major versions:

`ddev config --composer-version=2.2`
or
`composer_version: 2.2`

That will get composer 2.2.18 currently after you restart.

Or, of course, use a supported version of php in php_version.

See composer_version in https://ddev.readthedocs.io/en/latest/users/configuration/config_yaml/

**Comment by gitressa** [comment] 2025-12-31 12:58
See also:
- #7993
