### ISSUE TITLE
TYPO3: web service health check timed out

### ISSUE THREAD

**Issue by nozdrin-brd** [drud/ddev#750] opened 2018-03-26 10:58 UTC
## What happened:
**Failed to start typo-8-7: web service health check timed out** 

## How to reproduce this:
Install ddev on Ubuntu 16.04 / Linux Mint 18.3

## Versions: 
`ddev version:`
cli   	v0.15.1                        
web   	drud/nginx-php-fpm-local:v1.1.0
db    	drud/mariadb-local:v0.8.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.15.1                        
domain	ddev.local 

`docker version`
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false

`.ddev/config.yaml`
APIVersion: "1"
name: typo-8-7
type: typo3
docroot: ../
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.0.0
dbimage: drud/mariadb-local:v0.8.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
provider: default

**Comment by rfay** [comment] 2018-03-26 16:17
If you see this happen again, please post the results of `ddev logs` .  (If the web container is stopped, then use `docker logs <container_id>`)

One of the most likely causes is too much stress on Docker; I've definitely seen it when I go over about 5 sites running on my machine.

Thanks for the report!

**Comment by rfay** [comment] 2018-03-26 16:20
I note that your webimage doesn't match ddev v0.15.1, so that will make debugging startup failure a wee bit harder. Still interested. But it would be better to upgrade. We're working on a solid strategy for that. But if you have no customizations in the .ddev folder, the easiest technique is to delete .ddev and `ddev config`. It's also an option to delete the webimage and dbimage lines, then you'll always have the images specified by ddev itself. The ability to lock the images for a project in config.yaml is deliberate, but it definitely leads to confusion on ddev upgrades, especially as fast as the releases have been coming.

**Comment by nozdrin-brd** [comment] 2018-03-26 16:47
> I note that your webimage doesn't match ddev v0.15.1

The same problem occurs with  v.1.1.0. I've tried to use older image in order to run ddev.

> I've definitely seen it when I go over about 5 sites running on my machine.

It was the first attempt to run a local website using ddev/docker

The webimage container was not loaded. I didn't manage to get any logs concerning it.

**Comment by rfay** [comment] 2018-03-27 04:57
I'm hoping this is repeatable then, you should be able to `ddev start` and see the same results. If it fails in the same way, please do `docker ps -a` and you should see the web container there (nginx-php-fpm-local), use `docker logs <id>` to get the logs.

I note that yours may have been the very first 18.3.0 stable installed anywhere (they just let it go today), so of course they could have broken ddev, hopefully we'll know shortly.  They definitely broke Windows :)

**Comment by rfay** [comment] 2018-03-27 12:05
Thanks so much for doing that.

You're running ddev as root or sudo, which is not what you want to do for a number of reasons. Please add your user to the "docker" group, and then use ddev as a normal user.  ddev does not need to be run with sudo.

**Comment by nozdrin-brd** [comment] 2018-03-27 14:17
You helped me a lot!
Thank you!

**Comment by rickmanelius** [comment] 2018-03-27 14:18
Excellent :) Closing this out and THANK YOU for using DDEV and providing us feedback.

**Closed by rickmanelius** 2018-03-27 14:18 UTC

**Comment by rfay** [comment] 2018-03-27 14:35
Followup: https://github.com/drud/ddev/issues/754 to document correct Docker setup for linux users.

**Comment by sypets** [comment] 2018-04-19 10:25
I just had the same problem here trying `ddev start`. Is it helpful for you if I report this and give more info?

I am **not** running DDEV with sudo. What I _might_ have done is not shutdown DDEV properly before removing the directory. I removed my project folder and created an entirely new one. That's when I got the error. 

So I would say: probably my stupid mistake, but a check and a more clear error message might be helpful. 

After I cleaned up my mess (I mean the mariadb and phpmyadmin docker containers), the problem went away:
```
docker stop 090d3aea3333
docker rm 090d3aea3333
docker stop 6d26b8c9cbdf
docker rm  6d26b8c9cbdf

```


## What happened

Error message: "Failed to start ddev: db service health check timed out"

## How to reproduce this:

```
 ddev start
Starting environment for ddev... 
ddev-ddev-db is up-to-date 
Recreating ddev-ddev-web ...  
Recreating ddev-ddev-web 
Recreating ddev-ddev-web ... done
 
Stopping ddev-router ... done
Removing ddev-router ... done
Network ddev_default is external, skipping 
Creating ddev-router ...  
Creating ddev-router ... done
 

Failed to start ddev: db service health check timed out 

```

I started and stopped the container several times before. Everything was running very smoothly. Then I created a new DDEV project  and got this error. 

## Version

```
 ddev version
cli   	v0.17.0                        
web   	drud/nginx-php-fpm-local:v1.2.2
db    	drud/mariadb-local:v0.9.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.17.0                        
domain	ddev.local            
```

```
docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:53 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:25 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```


```
cat .ddev/config.yaml
APIVersion: "1"
name: ddev
type: typo3
docroot: ""
php_version: "7.2"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
provider: default
```


```
docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                                                                                      NAMES
26ea92cd9762        drud/ddev-router:v0.5.0           "/app/docker-entrypo…"   5 minutes ago       Up 4 minutes (healthy)      0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8025->8025/tcp, 0.0.0.0:8036->8036/tcp   ddev-router
ed0c25a82d4c        drud/nginx-php-fpm-local:v1.2.2   "/start.sh"              6 minutes ago       Up 6 minutes (healthy)      0.0.0.0:32801->80/tcp, 0.0.0.0:32800->8025/tcp                                             ddev-ddev-web
f17edaaf4371        drud/nginx-php-fpm-local:v1.2.2   "/start.sh"              13 minutes ago      Up 13 minutes (healthy)     0.0.0.0:32799->80/tcp, 0.0.0.0:32798->8025/tcp                                             ddev-Build-web
c0805e886e01        drud/phpmyadmin:v0.2.0            "/run.sh phpmyadmin"     13 minutes ago      Up 13 minutes (healthy)     0.0.0.0:32797->80/tcp                                                                      ddev-Build-dba
79e0a8b5040c        drud/mariadb-local:v0.9.0         "/docker-entrypoint.…"   13 minutes ago      Up 13 minutes (unhealthy)   0.0.0.0:32796->3306/tcp                                                                    ddev-Build-db
39499b943aec        typo3gmbh/php72:latest            "/sbin/my_init -- ba…"   2 hours ago         Up 2 hours                                                                                                             typo3_core_test
6d26b8c9cbdf        drud/phpmyadmin:v0.2.0            "/run.sh phpmyadmin"     17 hours ago        Up 27 minutes (healthy)     0.0.0.0:32793->80/tcp                                                                      ddev-ddev-dba
090d3aea3333        drud/mariadb-local:v0.9.0         "/docker-entrypoint.…"   17 hours ago        Up 27 minutes (unhealthy)   0.0.0.0:32792->3306/tcp                                                                    ddev-ddev-db

```

**Comment by rfay** [comment] 2018-04-19 14:06
So you have the *db* service timing out, not the web service.  It's likely https://github.com/drud/ddev/issues/748, which is corruption of the database, and can be resolved by `ddev remove --remove-data` (and re-importing). In recent versions of ddev, this is most likely caused by a docker bug, and can be avoided by using `ddev stop` or `ddev remove` before stopping or upgrading docker, or rebooting the computer.
