### ISSUE TITLE
Linux: Can't start project with docker 23.0.0; fixed with 23.0.1

### ISSUE THREAD

**Issue by anewarray** [drud/ddev#4616] opened 2023-02-07 08:43 UTC
### tldr: This seems to be a docker upgrade problem; `ddev debug refresh` seems to solve it.

More detail at https://github.com/drud/ddev/issues/4616#issuecomment-1421429448

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Normal start of Projects in my enviroment (Win 11, WSL2, Docker 23.0.0 inside WSL2, ddev 1.21.4)

### Actual Behavior

error when starting project

```
ddev start projectname
Starting projectname...
Container ddev-ssh-agent  Recreate
Container ddev-ssh-agent  Recreated
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
failed to solve: failed to walk: resolve : lstat /var/lib/docker/overlay2/diff: no such file or directory
Failed to start projectname: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-projectname docker-compose -f /home/username/projects/projectname/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built internal] load build definition from Dockerfile
#2 transferring dockerfile: 591B done
#2 DONE 0.0s

#3 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#3 DONE 0.0s

#4 [ddev-projectname-adminer internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#5 DONE 0.0s

#6 [ddev-projectname-adminer internal] load build definition from Dockerfile
#6 transferring dockerfile: 127B done
#6 DONE 0.0s

#7 [drud/ddev-webserver:v1.21.4-projectname-built internal] load build definition from Dockerfile
#7 transferring dockerfile: 922B done
#7 DONE 0.0s

#8 [drud/ddev-webserver:v1.21.4-projectname-built internal] load .dockerignore
#8 transferring context: 2B done
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-projectname-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#9 DONE 0.0s

#10 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built 2/2] RUN (groupadd --gid 1000 "username" || groupadd "username" || true) && (useradd  -l -m -s "/bin/bash" --gid "username" --comment '' --uid 1000 "username" || useradd  -l -m -s "/bin/bash" --gid "username" --comment '' "username" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "username" || useradd -l -m -s "/bin/bash" --comment '' username )
#10 CACHED

#11 [drud/ddev-webserver:v1.21.4-projectname-built 1/4] FROM docker.io/drud/ddev-webserver:v1.21.4
#11 DONE 0.0s

#12 [drud/ddev-webserver:v1.21.4-projectname-built 2/4] RUN (groupadd --gid 1000 "username" || groupadd "username" || true) && (useradd  -l -m -s "/bin/bash" --gid "username" --comment '' --uid 1000 "username" || useradd  -l -m -s "/bin/bash" --gid "username" --comment '' "username" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "username" || useradd -l -m -s "/bin/bash" --comment '' username )
#12 CACHED

#13 [drud/ddev-webserver:v1.21.4-projectname-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || composer self-update --2 || true
#13 CACHED

#14 [drud/ddev-webserver:v1.21.4-projectname-built 4/4] RUN mkdir -p /home/username && chown username /home/username && chmod 600 /home/username/.pgpass
#14 CACHED

#15 [drud/ddev-webserver:v1.21.4-projectname-built] exporting to image
#15 exporting layers done
#15 writing image sha256:baabec8807494d5518ea5095d1623edebbd4a129932c5cf083abf6e2e7cdbea7 done
#15 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4-projectname-built done
#15 writing image sha256:bbe7ec53369030ee339fb20d9181421b13e679b1539f595d9afbcd1e740873e7 done
#15 naming to docker.io/drud/ddev-webserver:v1.21.4-projectname-built done
#15 DONE 0.0s

#16 [ddev-projectname-adminer internal] load metadata for docker.io/library/adminer:standalone
#16 DONE 1.4s

#17 [ddev-projectname-adminer 1/2] FROM docker.io/library/adminer:standalone@sha256:19e0ba9e8b43fde46ca276e795c181d7cd07f3edc0fe88cc1e1880b02be0399e
#17 DONE 0.0s

#18 [ddev-projectname-adminer internal] load build context
#18 transferring context: 20B done
#18 ERROR: failed to walk: resolve : lstat /var/lib/docker/overlay2/diff: no such file or directory
------
 > [ddev-projectname-adminer internal] load build context:
------
', stderr='failed to solve: failed to walk: resolve : lstat /var/lib/docker/overlay2/diff: no such file or directory'
```

### Steps To Reproduce

Problem is solved after run `ddev debug test`

**Comment by rfay** [comment] 2023-02-07 14:17
It looks like you have a broken docker setup. Since you didn't do the required `ddev debug test` I can't tell much about your environment. Please do `ddev debug test` and provide the output as a gist or any other pastebin, or an attached txt file. 

Maybe you could at least say what OS you're on and things like that, and whether DDEV was previously working, and whether it works on a trivial project.

**Comment by rfay** [comment] 2023-02-07 14:50
I see you did give a little info in there at top of issue.  Did you deliberately upgrade docker-ce? Was it working before?

**Comment by rfay** [comment] 2023-02-07 14:53
If the problem is solved by running `ddev debug test`... then... ?? should you close this?

**Comment by rfay** [comment] 2023-02-07 15:11
Closing, but happy to continue the conversation here or elsewhere, and happy to reopen. It sounds like you might have upgraded docker without a reboot or without `ddev poweroff`.

**Comment by anewarray** [comment] 2023-02-07 15:15
> Closing, but happy to continue the conversation here or elsewhere, and happy to reopen. It sounds like you might have upgraded docker without a reboot or without `ddev poweroff`.

yes i did upgrading while working. risky life. a reboot didn't help. 
i opened a ticket because ddev debug test corrected the docker configuration but i didn't exactly know what happened while testing.

**Comment by rfay** [comment] 2023-02-07 15:18
Yeah, `ddev debug test` doesn't do anything except start a new trivial project.  But it does a `ddev poweroff`, which maybe you hadn't done. I recommend doing that first when having any trouble. Some strategies for troubleshooting are at https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/ for next time; `ddev poweroff` is first.

**Comment by rfay** [comment] 2023-02-07 20:14
Others are reporting Linux issues with docker 23.0.0, reopening.

**Comment by rfay** [comment] 2023-02-07 20:51
For several people this seemed to fix the issue:

```
ddev debug refresh
```

That forces a rebuild of the docker image layers; it seems that perhaps some docker image cache layers were possibly corrupted by the 23.0.0. upgrade.

**Comment by GitTworn** [comment] 2023-02-08 10:12
FYI: I updated yesterday as well. Ran into this same issue. A reboot did solve the problem for me.

**Comment by rfay** [comment] 2023-02-08 14:22
Related:
* https://github.com/docker/buildx/issues/1595
Suggested `docker system prune -a` which sounds reasonable, but it may lose docker volumes (databases).

**Comment by rfay** [comment] 2023-02-08 16:04
`docker builder prune -a` is also recommended.

**Comment by rfay** [comment] 2023-02-10 00:52
This may have been fixed in Docker [23.0.1](https://github.com/moby/moby/releases/tag/v23.0.1)

**Comment by mattsches** [comment] 2023-02-10 07:19
I can confirm that the upgrade to docker-ce 23.0.1 resolved this for me :fireworks:

**Comment by rfay** [comment] 2023-02-10 17:44
Closing, I think this is sorted now with upgrade to 23.0.1 (and the other techniques work too)

**Closed by rfay** 2023-02-10 17:44 UTC

**Comment by rfay** [comment] 2023-02-13 15:10
Thanks for the report @mbomb007 - did you do the fixes earlier here that sorted it out for users even on 23.0.0?

```
ddev poweroff
docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -q)
docker builder prune -a
ddev debug refresh
```

**Comment by rfay** [comment] 2023-02-13 15:17
Yes, you're using HEAD or v1.21.5-alpha1,  the change there affects people like you who do an ADD or COPY in custom Dockerfile. I had that in the release notes for upcoming v1.21.5, but did not get it into the prerelease release notes, it's there now, https://github.com/drud/ddev/releases/tag/v1.21.5-alpha1

And of course I apologize that you got the prerelease without asking for it, see 
* https://github.com/drud/ddev/issues/4628
