### ISSUE TITLE
"Index column size too large" MySQL error when importing TYPO3 DB

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#654] opened 2018-02-16 12:29 UTC
## What happened (or feature request):
When importing db dump of the TYPO3 9 I've got mysql error:

"Index column size too large. The maximum column size is 767 bytes."
An example failing query is:
```
CREATE TABLE sys_file_processedfile (
uid int(11) NOT NULL auto_increment,
tstamp int(11) NOT NULL default '0',
crdate int(11) NOT NULL default '0',
storage int(11) NOT NULL default '0',
original int(11) NOT NULL default '0',
identifier varchar(512) NOT NULL default '',
name tinytext,
configuration text,
configurationsha1 char(40) NOT NULL default '',
originalfilesha1 char(40) NOT NULL default '',
task_type varchar(200) NOT NULL default '',
checksum char(10) NOT NULL default '',
width int(11) default '0',
height int(11) default '0',
PRIMARY KEY (uid),
KEY combined_1 (original,task_type,configurationsha1),
KEY identifier (storage,identifier(199))
);
```
Error:
Index column size too large. The maximum column size is 767 bytes.

The same error was reported by user trying to install fresh TYPO3 v7.6. However he reported that installation of the fresh 8.7 or 9 went through (probably because starting from 8.7 TYPO3 adds default charset when creating tables).

## How to reproduce this:
log in to ddev mysql, and try to run query from above.

**Comment by tmotyl** [comment] 2018-02-16 13:30
A little more background to the issue after investigating it.
1. the default collation of the ddev db is `utf8mb4_bin`; utf8mb4 uses 4 bytes per char, while "standard" utf8 collation uses 3 bytes per char.
2. If you run above query without having  `DEFAULT CHARSET=utf8` at the end, mysql will try to create table using default db collation which is utf8mb4.
3. in this table we have a `KEY identifier (storage,identifier(199))`.  Doing little math 199 chars *4 bytes = 796 bytes, so already over the 767 limit.

**Comment by tmotyl** [comment] 2018-02-16 14:45
According to the MySQL 5.7 docs:
```
If innodb_large_prefix is enabled (the default), the index key prefix limit is 3072 bytes for InnoDB tables that use DYNAMIC or COMPRESSED row format. If innodb_large_prefix is disabled, the index key prefix limit is 767 bytes for tables of any row format.

innodb_large_prefix is deprecated and will be removed in a future release. innodb_large_prefix was introduced in MySQL 5.5 to disable large index key prefixes for compatibility with earlier versions of InnoDB that do not support large index key prefixes.
```
https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

I would suggest enabling innodb_large_prefix on ddev machines by default to solve issues like that.

**Comment by rfay** [comment] 2018-02-16 14:56
Sounds awesome. Thanks for the work on this. 

If there's any way to make that dump available to us for testing, it would be appreciated. I know a lot of times that won't work.

**Comment by tmotyl** [comment] 2018-02-16 15:29
I've just checked and indeed mysql settings are correct
```
innodb_large_prefix            = 1
innodb_file_format             = Barracuda
```
However to in order to raise the key limit, table needs to have row format set to DYNAMIC.
 
The problem is in the default row format which in MySQL 5.6 is hardcoded to COMPACT. Starting from MySQL 5.7 you can set default row format by changing global variable `innodb_default_row_format`. 

So in order to have correct row format, you either set row format when executing `CREATE TABLE`  or `ALTER TABLE` statements.

**Comment by tmotyl** [comment] 2018-02-16 15:33
What options do we have?
a) ship MySQL 5.7 in ddev
b) change default db charset to utf8 instead of utf8mb4 in ddev

**Comment by rfay** [comment] 2018-02-17 05:06
We're using Mariadb 10.1 in recent versions of ddev - If you still have old containers, you can delete your .ddev and use `ddev config` to get new ones (or just delete the db container line in .ddev/config.yaml).  Not sure that solves this problem, but if Mysql 5.6 is part of the problem, it's long gone.

I don't think that changing the default charset to utf8 is an option for any modern CMS site, since it ruins any usage of emoticons in a horrible way.

**Comment by tmotyl** [comment] 2018-02-18 17:26
Unfortunately Mariadb 10.1 behaves in this regard similar to MySQL 5.6.
See https://mariadb.com/kb/en/library/xtradbinnodb-storage-formats/
Updating to Mariadb 10.2 would solve the problem.

**Comment by rfay** [comment] 2018-02-18 20:14
I don't think anything will really keep us from upgrading to 10.2, but OTOH this may be a day in the life of a particular site that needs to have some index name reduction. 

Will upgrading to 10.2 *alone* fix it, or does that just give us the tools?

**Comment by rickmanelius** [comment] 2018-02-23 23:50
Bump. Just wanted to see if @tmotyl had any thoughts on @rfay's last comment if it's just the upgrade itself or if the upgrade provides necessary tools/options to fix/address a specific database.

**Comment by tmotyl** [comment] 2018-02-26 11:38
The current state is that TYPO3 in v8 & v9 is creating new tables with explicit charset - utf8 - and you can't change it. (there is a feature request to make it configurable, but it's not there yet).
So these versions will be able to create new tables (or install TYPO3) without issues.

Where it's failing is importing db dumped with regular mysqldump.
Just checked it again and its failing on executing:

```
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sys_refindex` (
  `hash` varchar(32) NOT NULL DEFAULT '',
  `tablename` varchar(255) NOT NULL DEFAULT '',
  `recuid` int(11) NOT NULL DEFAULT '0',
  `field` varchar(64) NOT NULL DEFAULT '',
  `flexpointer` varchar(255) NOT NULL DEFAULT '',
  `softref_key` varchar(30) NOT NULL DEFAULT '',
  `softref_id` varchar(40) NOT NULL DEFAULT '',
  `sorting` int(11) NOT NULL DEFAULT '0',
  `deleted` smallint(6) NOT NULL DEFAULT '0',
  `workspace` int(11) NOT NULL DEFAULT '0',
  `ref_table` varchar(255) NOT NULL DEFAULT '',
  `ref_uid` int(11) NOT NULL DEFAULT '0',
  `ref_string` varchar(1024) NOT NULL DEFAULT '',
  PRIMARY KEY (`hash`),
  KEY `lookup_rec` (`tablename`,`recuid`),
  KEY `lookup_uid` (`ref_table`,`ref_uid`),
  KEY `lookup_string` (`ref_string`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```
with error:

```
Failed to import database for typo3-core-master: Failed to run docker-compose [-f .ddev/docker-compose.yaml exec -T db bash -c cat /db/*.sql | mysql], err='exit status 1', stdout='ERROR 1709 (HY000) at line 2451: Index column size too large. The maximum column size is 767 bytes.
', stderr='' 
```

After I modified the dump and manually changed the row to have row format definition like:
```
) ENGINE=InnoDB  ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8;
```
It went through. As dynamic row format is a default one in Mariadb 10.2, I think this will solve the problem, but I have not tested it myself.

After thinking about it, I think its wrong that mysql reports this issue when we explicitly state the charset for a table (so utf-8 should be used, and bytes limit would not be exceeded). It looks like now MySQL uses database default charset to check keys lengths instead of charsed used in the create table statement.

**Comment by beathorst** [comment] 2018-02-28 12:38
I had the same problem, my dirty workaround is to change it to utf8general_ci with the phpmyadmin. but it would be nice to have a better solution within the config

**Comment by rfay** [comment] 2018-03-01 16:10
IMO this is a fundamental issue that we're going to have to address. The reality is that although sites  should already be moving to utf8mb4 and dealing with index length issues, they won't be, and it doesn't matter to most folks that don't have open commenting or similar user content. And people need to be able to use ddev with those sites. 

We need to make it easy to use ddev with sites that aren't ready for utf8mb4.

**Comment by tmotyl** [comment] 2018-03-01 16:39
@rfay is there an ddev image with MariaDB 10.2 I can test?

**Comment by rfay** [comment] 2018-03-01 18:49
Shoot, no there isn't, and it's harder than I remembered, because the image is Alpine, and there's no 10.2 package for Alpine (that I know of). I think it requires building 10.2 as here: https://github.com/wallneradam/docker-mariadb-alpine/blob/master/Dockerfile

I was thinking it was a little easier.  Good reason to avoid Alpine.

**Comment by cyberswat** [comment] 2018-03-02 12:24
Hitting this issue doing demos against existing wordpress sites.  https://github.com/drud/ddev/issues/654#issuecomment-369226790 worked in this scenario as well.

**Comment by rickmanelius** [comment] 2018-03-02 14:05
Hit the same problem and given the time constraint for a demo, used the phpmyadmin work around. So others know what that solution entails, view the instructions here https://www.a2hosting.com/kb/cpanel/cpanel-database-features/changing-the-mysql-collation-settings-in-phpmyadmin. Basically, after a `ddev start`, use `ddev describe` and visit phpmyadmin. Then select the "db" database, go to the operations tab, change the collation, and hit go.

**Comment by beeradb** [comment] 2018-03-02 14:14
I wonder if a short-term solution to this is to add a post-start hook that does an alter the database to set the correct charset?

i.e. `ALTER DATABASE db CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`  -- Source https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by rfay** [comment] 2018-03-02 15:35
Could anybody in this issue please provide an offending database? Thanks! We need both short-term and long-term solutions for this.

**Comment by rfay** [comment] 2018-03-02 19:57
Prioritizing this onto the project board, needs to be solved soon.

**Comment by rfay** [comment] 2018-03-02 21:25
I note that there are only 2 places in ddev that implement utf8mb4:

1. In the wordpress-only generated wp_settings we specify `define('DB_CHARSET', 'utf8mb4');` - I think that's been that way forever.
2. In mariadb-local container the /etc/my.cnf specifies

```
character-set-server = utf8mb4
collation-server = utf8mb4_bin
```

I can see one very general way to work around this: Allow people to provide their own my.cnf, which is something people would naturally want to do. (We already provide the ability to override nginx, and have plans to do it for php.ini.)

We could also place a config for this exact item into .ddev/config.yaml, either `mysql_character-set-server=...` or `utf8mb4: true`. Allowing override of the whole config is more general.

**Comment by rfay** [comment] 2018-03-02 22:21
For a short-term solution, those who are having this problem can use
`dbimage: drud/mariadb-local:v0.7.1-no_utf8mb4` in your .ddev/config.yaml. 

The code changes are in https://github.com/drud/mariadb-local/pull/45, which is pushed only to document this possibility.

I think you have to `ddev remove --remove-data` and `ddev start`, then your `ddev import-db` should work.

**Comment by rfay** [comment] 2018-03-07 18:43
Our plan for resolving this is quite general: We're going to allow custom mysql and php config per project, should be in v0.15.0 shortly.

**Closed** 2018-03-09 01:40 UTC
Labels: work in progress

**Comment by tmotyl** [comment] 2018-03-15 12:47
cross linking documentation - how to apply custom mysql config for ddev
https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-mysqlmariadb-configuration-mycnf

**Comment by toxiroxi** [comment] 2019-03-03 20:40
It is just a long time ago, but i can confirm upgrading from 10.1 to 10.2 completely solved my problem in regards to that error. I've been upgrading it according to Plesk documentation and then did a manual upgrade of all existing databaseses. luckily there were no issues at all.
cheers,

**Comment by evolution-dangerouslyset** [comment] 2025-02-01 14:51
I discovered the answer https://phps.space/questions/what-is-the-best-way-to-ensure-a-column-variable-can-only-be-modified-once-in-phpmysql
