### ISSUE TITLE
Add Solr details to "ddev describe"

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1623] opened 2019-05-23 10:11 UTC
**Is your feature request related to a problem? Please describe.**
It would be really useful if there was a way of seeing the Solr configuration in the "ddev describe" output.

**Describe the solution you'd like**
Some information be added in "ddev describe" when Solr is running, similar to how the database credentials are displayed.

**Comment by rfay** [comment] 2019-05-23 12:12
This is a duplicate of https://github.com/drud/ddev/issues/788, and it's a good idea, but I'll close in favor of that one. Please subscribe to it. 

I'm sure that ddev describe can *show* the extra services, but I'm not sure it can show any details about them, since they're hidden in docker-compose.*.yaml and service configuration.

**Closed by rfay** 2019-05-23 12:12 UTC

**Comment by rfay** [comment] 2019-05-30 17:59
@damienmckenna What details of solr would you add to `ddev describe`? I'm wondering how this can be done in a relatively generic way, and solr makes a good test case.

**Comment by rfay** [comment] 2020-04-08 03:21
3rd party services with URLs are included in `ddev describe` in next release of ddev, v1.14
