### ISSUE TITLE
Completely ignore mutagen flag on Linux

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#3349] opened 2021-10-28 23:39 UTC
**Is your feature request related to a problem? Please describe.**
Linux users really don't need Mutagen for the web container, but we want to have mutagen enabled by default for our devs.

**Describe the solution you'd like**
Can ddev ignore the mutagen flag in `.ddev/config.yaml` entirely and just assume that it's always `no`? Maybe add a `mutagen_force_linux_enable` flag or something like that for people that truly need mutagen on Linux for whatever reason?

**Describe alternatives you've considered**
Maybe there's a way to have OS-specific overrides? `.ddev/config.linux.yaml` or something?

**Additional context**

**Comment by rfay** [comment] 2021-11-02 21:14
I should note that enabling mutagen on linux or windows or wsl2 actually does no damage. If you like it on macOS you won't dislike it on linux or elsewhere. On native Windows the initial sync time is longer because NTFS/CIFS is so slow. But the results after that are glorious. A full test run using mutagen on Linux is run on every push.

**Comment by stephencross** [comment] 2021-11-03 01:18
An approach to turning on Mutagen for MacOS only uses a pre-start hook.

- Create a config file, .ddev/config.mutagen.yaml-macos,  with mutagen on. 
`mutagen_enabled: true`

- Create a pre-start hook that copies the -yaml-maos file to -yaml when running on MacOS

```
hooks:
  pre-start:
    - exec-host: "[[ $OSTYPE == 'darwin'* ]] && cp .ddev/config.mutagen.yaml-macos .ddev/config.mutagen.yaml || echo 'Mutagen not'"
```

**Comment by rfay** [comment] 2021-11-04 22:06
Since linux is one of the key testing places (because it's free on github actions) it would certainly not be reasonable to ignore mutagen on Linux as requested. Also, mutagen works fine on linux.

**Comment by cweagans** [comment] 2021-11-04 22:28
Mutagen works fine on Linux, but it's unnecessary for day-to-day use. I see your point for testing purposes though. Would you consider something along these lines for Linux users who specifically want Mutagen?

```yaml
mutagen_enabed: true
force_linux_mutagen_enabled: true
```

That way, you could still turn it on for tests and everyone would be able to check in their config.yaml that includes `mutagen_enabled: true`. So `mutagen_enabled: true` just turns on Mutagen for macOS and (non WSL) Windows users and `force_linux_mutagen_enabled: true` turns it on for linux users.

**Comment by cweagans** [comment] 2021-11-04 22:30
Alternatively, would you consider OS specific config flag variants? e.g.:

```yaml
mutagen_enabled: true
darwin_mutagen_enabled: true
windows_mutagen_enabled: true
linux_mutagen_enabled: true
```

(applied generally to any config option - it may be unnecessary for most flags. not sure)

**Comment by rfay** [comment] 2021-11-04 23:24
Probably not. The problem is that the more you add to everything, the more confused people get. And IMO (sorry) this problem is so easy to solve so many different ways that it doesn't need any additional code or complexity to make the majority of people happy.

Please consider using `ddev config global --mutagen-enabled` for people who want mutagen in whatever context.

**Comment by deviantintegral** [comment] 2021-11-10 19:32
Related: https://github.com/drud/ddev/issues/3190

However, after discussion there we've been happy with our teams enabling it as a global config. Since having mutagen enabled changes sync expectations (such as waiting for files to sync after changing branches with lots of files), having it be consistent across all projects by developer has been a better experience.

Also, allowing mutagen to work on Linux allows for our linux user to try out and understand how mutagen works when supporting macOS and Windows users.

**Comment by rfay** [comment] 2021-11-10 20:46
@deviantintegral it's completely clear that Mutagen is fully supported and tested on Linux/WSL2 and Traditional Windows, right? So given your preferences you can just check in `mutagen_enabled: true` as project configuration?

**Comment by rfay** [comment] 2021-11-10 20:55
Added https://github.com/drud/ddev/commit/23a1c1dc9da8fb9161a69efb636641550f67a74c for docs

**Comment by deviantintegral** [comment] 2021-11-12 18:28
Your docs update above makes sense to me, thanks!

**Comment by rfay** [comment] 2021-12-01 14:31
I'm open to some kind of per-CMS config override, but it needs to be thought out. I'm not in favor of specific work for mutagen. I think we've talked this through in this issue, so closing this one for now, but happy to continue the conversation here or elsewhere and happy to reopen if needed.

**Closed by rfay** 2021-12-01 14:31 UTC

**Comment by ElijahLynn** [comment] 2021-12-02 17:27
Does Mutagen on Linux cause a performance regression?

**Comment by rfay** [comment] 2021-12-02 17:49
No, it may just be a tiny bit faster. But it introduces complexity that isn't of value for that tiny bit.
