### ISSUE TITLE
Do not allow `ddev config` to be used while a site is running

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#540] opened 2017-11-16 22:27 UTC
## What happened (or feature request):
Changing a site name while actively running a ddev site can cause issues. This is because we are currently using the site name a primary key. 

Currently, we don't have any protections in place to prevent this:

In this console log I do the following:
- config a wordpress site called "wordpress"
- start the site ("wordpress" is started)
- change the name of the site via `ddev config` to "wp2"
- start the site again ("wp2" is started. "wordpress" is still running, orphaned from it's config)
- run `ddev rm wordpress` to delete the original site

The result is that the "wp2" site is removed, since that is what is in the config. The "wordpress" site remains running.

```
ddev/wordpress ‹gke:bbowman› git:(master) ✗ » ddev config
Creating a new ddev project config in the current directory (/Users/beeradb/Projects/ddev/wordpress)
Once completed, your configuration will be written to /Users/beeradb/Projects/ddev/wordpress/.ddev/config.yaml

Project name (wordpress):

The docroot is the directory from which your site is served. This is a relative path from your application root (/Users/beeradb/Projects/ddev/wordpress)
You may leave this value blank if your site files are in the application root
Docroot Location: htdocs
Found a wordpress codebase at /Users/beeradb/Projects/ddev/wordpress/htdocs.
Configuration complete. You may now run 'ddev start'.
ddev/wordpress ‹gke:bbowman› git:(master) ✗ » ddev start
Starting environment for wordpress...
Creating ddev-wordpress-db ...
Creating ddev-wordpress-db ... done
Creating ddev-wordpress-web ...
Creating ddev-wordpress-dba ...
Creating ddev-wordpress-web
Creating ddev-wordpress-web ... done

Creating ddev-router ...
Creating ddev-router ... done

Successfully started wordpress
Your application can be reached at: http://wordpress.ddev.local
ddev/wordpress ‹gke:bbowman› git:(master) ✗ » ddev config
You are reconfiguring the app at /Users/beeradb/Projects/ddev/wordpress.
The existing configuration will be updated and replaced.
Project name (wordpress): wp2

The docroot is the directory from which your site is served. This is a relative path from your application root (/Users/beeradb/Projects/ddev/wordpress)
You may leave this value blank if your site files are in the application root
Docroot Location (htdocs):
Found a wordpress codebase at /Users/beeradb/Projects/ddev/wordpress/htdocs.
Configuration complete. You may now run 'ddev start'.
ddev/wordpress ‹gke:bbowman› git:(master) ✗ » ddev start
Starting environment for wp2...
Creating ddev-wp2-db ...
Creating ddev-wp2-db ... done
Creating ddev-wp2-web ...
Creating ddev-wp2-dba ...
Creating ddev-wp2-web
Creating ddev-wp2-web ... done

ddev-router is up-to-date
Successfully started wp2
Your application can be reached at: http://wp2.ddev.local
ddev/wordpress ‹gke:bbowman› git:(master) ✗ » ddev rm wordpress
Removing container: ddev-wp2-web
Removing container: ddev-wp2-dba
Removing container: ddev-wp2-db
Successfully removed the wp2 application.
```

## What you expected to happen:
Running `ddev config` while a site is running should result in the following error message:

"This ddev site is currently running. Please run 'ddev stop' before attempting to change the configuration"

**Comment by rfay** [comment] 2017-11-16 22:30
👍 , but of course it doesn't stop a whole bevy of related problems:
* User edits config.yaml
* User moves the directory (that's caught by a different check though)
* User changes sitename while containers are stopped.

**Comment by beeradb** [comment] 2017-11-16 22:31
Agreed. As long as we allow user-editing of config files we can't fully prevent these types of errors. I'm hopeful a majority of our users use `ddev config`, though. I guess we lack metrics to know for sure. 

I'm hopeful that a simple conditional here could stop the vast majority of these rename issues.

**Comment by rickmanelius** [comment] 2017-11-17 02:04
Good points here. And it's correct to state that we can't anticipate and adjust for every situation in which a user goes around and manually modifies their system (what happens when they delete the global ~/.ddev folder! what about killing docker containers manually!), but we can/should try to catch/address when using ddev directly. Therefore, the situation of using config when a site is up or paused is very much a valid concern.

A proposed solution could be that config exists whenever containers are detected in any state with a prompt to run `ddev rm`. This is good guidance because it's essentially telling the user to remove the infra stack before modifying the config to rebuild said stack.

**Comment by rfay** [comment] 2018-02-07 05:11
This is a duplicate of #601

**Comment by rfay** [comment] 2019-05-08 20:08
This seems to be unusual, and we don't hear from people about problems, so closing.

**Closed by rfay** 2019-05-08 20:08 UTC
Labels: hibernate
