### ISSUE TITLE
The configuration directory type 'sync' does not exist error when running drush uli

### ISSUE THREAD

**Issue by cedewey** [drud/ddev#880] opened 2018-05-24 19:51 UTC
**Describe the bug**
When running `ddev exec drush uli` I get the following error, 

> [error]  The configuration directory type 'sync' does not exist
Failed to execute command [drush uli]: Failed to run docker-compose [-f /Users/claytondewey/htdocs/drutopia/.ddev/docker-compose.yaml exec -T web drush uli], err='exit status 1', stdout='', stderr=' [error]  The configuration directory type 'sync' does not exist '

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version: 18.03.1-ce
 - ddev version: v0.18.0
 - config.yaml contents

> APIVersion: v0.18.0
> name: drutopia
> type: drupal8
> docroot: web
> php_version: "7.1"
> router_http_port: "80"
> router_https_port: "443"
> xdebug_enabled: false
> additional_hostnames: []
> provider: default

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?  No

**Comment by rfay** [comment] 2018-05-24 19:55
Thanks, I think this is a duplicate of [Generated settings.php needs 'sync' key in drupal8 #504](https://github.com/drud/ddev/issues/504), which is on the docket for attention quite soon. Follow up if  that's not true, and I'll reopen.

However, this doesn't happen on a plain vanilla d8 site, so I assume this is a result of *having* the sync key set right? You'll need to adjust that in your own settings.php or something...

**Comment by cedewey** [comment] 2018-06-01 02:07
Correct, this is *not* on a vanilla site. However, looking at my settings.php file, I don't see a sync folder or key being defined.

**Comment by rfay** [comment] 2018-06-09 17:21
@cedewey if I'm not mistaken you solved this, closing but happy to follow up further if required.

**Closed by rfay** 2018-06-09 17:21 UTC
