### ISSUE TITLE
ddev-router errors on Apple M1 Airbook caused by running amd64 version of ddev

### ISSUE THREAD

**Issue by glappsi** [drud/ddev#2874] opened 2021-03-15 19:24 UTC
Hello,

I am using ddev version v1.17.0-alpha7 on my new Airbook, `drud/ddev-webserver:20210226_heddn_assert_enable` as base image. I am also using the newest Docker Preview and iTerm as the terminal. The ddev-webserver and and the db-server are starting successfully, but the ddev-router fails with the following error

```
Using the local CA at "/root/.local/share/mkcert" ✨
ERROR: failed to execute "update-ca-certificates": exit status 1
```

Could this be a bug or am I doing something wrong?

**Comment by rfay** [comment] 2021-03-15 19:45
Is it possible you're not using the arm64 version of ddev?  Please check over the instructions for m1 in https://github.com/drud/ddev/releases/tag/v1.17.0-alpha7 - if possible please use homebrew to install, and make absolutely sure that you've installed the arm64 version of ddev. You can use `file /path/to/binary/ddev` to verify that you have the arm64/aarch64 version.

The M1 is tricky, because it can mostly run amd64 binaries and images... but it leads to odd errors. Lots of people are using v1.17.0-alpha7 just fine on Apple M1. 

Maybe you could post the output of `docker logs ddev-router` after the failure, although I think it will just say the same thing, or maybe you're just quoting from it.

**Comment by glappsi** [comment] 2021-03-15 21:37
Thank you, you were completely right, I did not install the arm64 version 😩 Now the router starts just fine. Now I get the error `<path> does not seem to be healthy/mounted; docker may not be mounting it`, even though I did all the things mentioned in your link. But that is another issue :D

**Comment by rfay** [comment] 2021-03-15 22:13
This kind of thing is often caused by Docker needing full disk access to allow access to your directory, especially if your project is in ~/Documents or ~/Desktop or on an external disk. Docker (or other tools) pop up a dialog, but if you miss the dialog... it's gone. You can grant access in System Preferences->Security and Privacy->Privacy->Full Disk access if that's it.

**Comment by rfay** [comment] 2021-03-15 22:15
Closing for now, since we found the way to the bottom of the issue. Happy to continue the conversation here or elsewhere, and happy to help with the next problem here or in any of the [support venues](https://ddev.readthedocs.io/en/latest/#support-and-user-contributed-documentation)

**Closed by rfay** 2021-03-15 22:15 UTC

**Comment by glappsi** [comment] 2021-03-15 22:19
Thank you very much :)
Maybe you have some idea where I can look for some more information on what exactly went wrong, or some things I can try. All I see in the ddev logs is
```
ls: cannot open directory '/var/www/html': Stale file handle
/var/www/html does not seem to be healthy/mounted; docker may not be mounting it., exiting
+ echo '/var/www/html does not seem to be healthy/mounted; docker may not be mounting it., exiting'
```

Do you have an idea or some hint?

**Comment by rfay** [comment] 2021-03-15 22:22
I'm only seen that when people are using NFS and it's gone bad. Do you have nfs_mount_enabled set to true? Just `ddev describe | head` and it will show you. If it's on, then it's likely NFS that's bad. Disable it as a first step. Then go through the docs to enable NFS.

Also, if you *do* have NFS, then the same problem exists for nfsd needing full disk access. That's also covered in the [macos nfs docs](https://ddev.readthedocs.io/en/latest/users/performance/#macos-nfs-setup)

**Comment by rfay** [comment] 2021-03-15 22:25
And don't forget those same [release notes](https://github.com/drud/ddev/releases/tag/v1.17.0-alpha7) that detail how to set up your /etc/exports for nfs

**Comment by glappsi** [comment] 2021-03-15 22:36
I did not give nfsd full disk access, this was exactly the issue! Thank you so much! You are the best! ❤️

**Comment by rfay** [comment] 2021-03-15 22:38
Could you say what directory your project was in please? Just `pwd` in the project directory or whatever. I'm interested in knowing which of these situations you hit.
