### ISSUE TITLE
"Docroot Location" should pick up normal directory roots

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#663] opened 2018-02-20 05:22 UTC
## What happened (or feature request): 
Feature request

## What you expected to happen:
When I configured a composer based Drupal project, I figured it would pick up `web` or `docroot` when "Docroot Location"  was asked.

## How to reproduce this:
Run `ddev config`

## Related source links or issues:

Example of what I did in my tool `platform-docker`

```
                // Platform.sh scaffold docroot.
                if (is_dir($this->cwd . '/' . Platform::DEFAULT_WEB_ROOT)) {
                  Config::set('docroot', Platform::DEFAULT_WEB_ROOT);
                }
                // Typical app location.
                elseif (is_dir($this->cwd . '/web')) {
                    Config::set('docroot', 'web');
                }
                // Acquia.
                elseif (is_dir($this->cwd . '/docroot')) {
                    Config::set('docroot', 'docroot');
                }
                else {
                  $question = new Question("<info>What is the document root for the project?");
                  $answer = $helper->ask($input, $output, $question);
                  Config::set('docroot', $answer);
                }
```

source: https://github.com/mglaman/platform-docker/blob/develop/src/Command/InitCommand.php#L48

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

1

**Comment by rfay** [comment] 2018-02-20 20:59
I think this is totally reasonable. I'd think 

* probe those in order of most likely, looking for an index.php in them. 
* Prompt with the discovered docroot as default rather than just going with it.

I actually can't tell you how many times I've had to ctrl-c in the middle of a config operation or use another window to go find what the docroot is.

**Comment by rickmanelius** [comment] 2018-02-23 23:47
Flagging in the milestone to provide better CMS UX. There is a little bit of a challenge in that this may be CMS specific because some codebases (notably TYPO3) can sometimes have two index.php files and we need to have more than just a file/directory check to accurately detect with a 99+% hit rate.

**Comment by mglaman** [comment] 2018-02-24 02:15
So, I know this is in Go. But are option selects possible, like in Symfony Console?

" We detected these docroots, please select correct one", because don't some even use `index_dev.php`? So if someone want to point to dev or something crazy.

**Comment by mglaman** [comment] 2018-02-25 20:26
Okay, giving this a whirl. Looks like all the work needs to be done in `pkg/ddevapp/config.go:358` at `func (app *DdevApp) docrootPrompt() error {`

**Comment by rickmanelius** [comment] 2018-03-05 20:23
I believe this is a duplicate of #663, which has a PR in the final review stages. Going to close this out, but feel free to re-open if it's separate functionality.

**Closed by rickmanelius** 2018-03-05 20:23 UTC
Labels: actionable, needs docs, needs tests

**Comment by mglaman** [comment] 2018-03-05 22:31
@rickmanelius this is #663, and the PR is #678
