### ISSUE TITLE
docker version error does not match users actual installed version

### ISSUE THREAD

**Issue by if-kyle** [drud/ddev#398] opened 2017-07-12 17:48 UTC
## What happened (or feature request):
ddev config
Could not perform update check: open /Users/kylesloan/.ddev/.update: no such file or directory
The docker version currently installed does not meet ddev's requirements: 17.3.1-ce is less than 17.05.0-ce

## What you expected to happen:
The error message doesn't show the correct version of docker for mac that I have installed

docker -v                                                                                                                                                           1 
Docker version 17.03.1-ce, build c6d412e

The error message showed 17.3.1 instead of 17.03.1

## Version: Please include the output of `ddev version` and the project's .ddev/config.yaml.
ddev version
Could not perform update check: open /Users/kylesloan/.ddev/.update: no such file or directory
The docker version currently installed does not meet ddev's requirements: 17.3.1-ce is less than 17.05.0-ce

I cannot get the version via command and .ddev/config.yaml does not exist

## How to reproduce this:
Have a version of docker for mac less then 17.05.0-ce

## Related source links or issues:

**Comment by tannerjfco** [comment] 2017-07-12 18:03
Thanks for the feedback, and for checking out ddev!

We use a semver package to check the version, which considers 17.3.1 and 17.03.1 as the same. You do need Docker 17.05 or later in order to run ddev. Docker 17.06 is the latest stable release, so we recommend upgrading to that version.

As for this error:
```
Could not perform update check: open /Users/kylesloan/.ddev/.update: no such file or directory
```
We recently fixed this issue in #380, so you can expect this to be fixed in the next release. For now, you should be able to get around the issue by manually creating the `.ddev` directory in your home directory.

Once you have Docker upgraded and the .ddev directory in your home directory, you should be able to run ddev config successfully. Hope that helps!

**Comment by if-kyle** [comment] 2017-07-12 18:05
Cool.  I am still on El Capitan, is Sierra just a requirement as that is what you do your testing on or is it a known problem on El Capitan?

**Comment by rickmanelius** [comment] 2017-07-12 18:32
Hi @if-kyle! As of right now, we're only testing against Sierra as noted in the project readme page (https://github.com/drud/ddev). That said, if upgrading is a blocker and we're seeing an increased demand for one back, we can certainly consider it.

**Comment by tannerjfco** [comment] 2017-07-12 20:02
We're not aware of any issues running ddev on El Capitan. Docker for Mac lists El Capitan for minimum system requirements, so you should be able to run Docker 17.06. I suspect you should be able to run ddev without much issue, but I'm pretty sure we're all developing on Sierra at this point so I couldn't say for certain.

**Comment by rfay** [comment] 2017-09-26 13:36
I removed "actionable" because this still has "needs decision" - not understanding how it can be actionable if it needs a decision, and a  quick scan doesn't show me what the decision is that needs to be made. 

1. We absolutely need to make the error message report a true docker version if it doesn't. Not sure how that problem could happen.
2. If we need to decide about supporting other OSX versions, that should be spun off. 
3. We need to test and update docs to cover High Sierra, see https://github.com/drud/ddev/issues/480

**Comment by rickmanelius** [comment] 2017-10-12 17:44
At this stage with High Sierra out and the general goal being latest OS + one version back (when it makes sense because this may not be possible for Windows), I'd say that we can't really commit to testing an issue specific to El Capitan. If you upgrade to Sierra/High Sierra and still experience this, let us know and we'd be more than happy to help!

**Comment by rfay** [comment] 2017-10-12 17:47
@rickmanelius this seemed to be fundamentally about the docker version reported though. It's worth testing to recreate this on any OS. I wouldn't be surprised if we're reporting the server version not the client, or something like that.

**Comment by rickmanelius** [comment] 2017-10-12 17:50
@rfay My apologies! I was looking at the last ~ 4 comments and it seemed more focused on the supported OS. Yes assuring the proper Docker version reported would be valid and useful. So while we have one decision made (and therefore we can remove that label), we can proceed on the actionability of testing and verifying the proper Docker version.

**Comment by rickmanelius** [comment] 2017-12-11 14:33
Updated the metadata. This is more a bug fix and we should get it in the timeline. Thanks!

**Comment by rfay** [comment] 2017-12-11 14:40
If I understand right, this issue is about the fact that the error message reported the user's docker version as 17.3.1-ce when it was really 17.03.1-ce. 

1. This is unlikely to happen this far down the line as most people (except on ubuntu) have long-since upgraded to 17.05+
2. The error was not a very big one, since with semver the result was the same anyway.

I think this could be easily tested by just creating a script called "docker" that reported various versions.

**Comment by rfay** [comment] 2017-12-11 14:53
I can easily demonstrate this problem by setting DockerVersionConstraint to 17.10.1-ce

**Comment by rickmanelius** [comment] 2017-12-11 14:59
While this seems like such a simple thing, I'm not fully grokking what the issue is here without manually testings and seeing what is actually breaking (yes I understand a version mismatch but I'm not fully sure what the cause is). That said, @rfay if there is a straightforward way to address this I'm happy to proceed on this nit and put it behind us.

**Comment by rfay** [comment] 2017-12-11 15:02
This is a result of:

* We use github.com/Masterminds/semver to check the version constraint
* Docker uses a strange formation "17.09" etc, when they should have just used "17.9"
* semver parses based on actual semver, where "09" is really "9"
* We use semver's constraint explanation, which ends up with 17.3.1 (in the OP) instead of the provided 17.03.1.

I'd say let's chalk this up to docker versioning strangeness and close this. It doesn't do much harm, and the workaround for it would be to rewrite the semver response... but that means giving away all other constraints we might want to have in the future. We're better off being able to give a legit constraint in the future if something goes wrong with docker than we are having a perfect error message.

**Comment by rickmanelius** [comment] 2017-12-11 16:32
Excellent. Thanks for the overview and I'm happy to close this for now and re-address if it becomes a persistent, ongoing request/issue.

**Closed by rickmanelius** 2017-12-11 16:32 UTC
Labels: incubate
