### ISSUE TITLE
Allow a user to start/stop/remove all running projects

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#952] opened 2018-06-28 18:19 UTC
**Is your feature request related to a problem? Please describe.**
It's currently time-consuming and frustrating to stop or remove many projects.

**Describe the solution you'd like**
I'd like to be able to stop or remove all possible sites with a command like `ddev remove --all`/`ddev stop --all`. I'd also like to be able to pass multiple project names into `ddev remove` and `ddev stop`.

**Describe alternatives you've considered**
A user can currently do this:
```
ddev list -j | jq -r .raw[].name | xargs -t -I % ddev rm %
```
...but that's not very welcoming.

**Comment by rfay** [comment] 2018-06-28 20:08
I'd like to see the ability to 

`ddev stop --all`
`ddev rm --all`
`ddev start/stop/rm proj1 proj2 proj3` (there may be other commands that deserve this)

**Comment by rfay** [comment] 2018-06-28 20:40
This is really a duplicate of [As CLI user, I want the ability to interact with each site from any directory  #44 ](https://github.com/drud/ddev/issues/44) but I think what we have here is more actionable

**Closed** 2018-07-09 14:34 UTC
Labels: actionable, needs tests
