### ISSUE TITLE
Webserrver-image DDEV 1.14.2 missing xdebug

### ISSUE THREAD

**Issue by Padina14** [drud/ddev#2439] opened 2020-08-05 07:10 UTC
I tried to run xdebug on phpunit-tests with phpstorm using ddev 1.14.2. PHPstorm won't find xdebug. It don't work
After a rollback to Version 1.13.0 it works fine.

The Image for the webserver in version 1.14.2 seems to be buggy.

https://youtrack.jetbrains.com/issue/WI-54532?replyTo=27-4317436

**Comment by rfay** [comment] 2020-08-05 12:57
This is a duplicate of https://github.com/drud/ddev/issues/2245 which explains how you can fix that up. 

PHPStorm's usage of the web container is a very unusual usage, unrelated to ddev (it's runs its own separate container). 

Maybe if two people have tried to use it that way we'll just make it work the other way.

**Closed by rfay** 2020-08-05 12:57 UTC

**Comment by rfay** [comment] 2020-09-01 16:45
Note that in v1.16.0-alpha1+ xdebug is enabled by default

**Comment by Padina14** [comment] 2020-09-02 12:29
Thanks for your work. 
I tested it with ddev version v1.16.0-alpha2. It works fine now.
