### ISSUE TITLE
`ddev create` for TYPO3 fails if `--docroot != public`

### ISSUE THREAD

**Issue by marble** [drud/ddev#3701] opened 2022-03-14 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

ddev version v1.18.2, is generally running fine

### Current Behavior

Intention: ddev composer install TYPO3

I am trying to `ddev composer` install TYPO3 following the recommended procedure  on docs.typo3.org [Exeute Composer Create-Project (card: ddev)](https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/Install.html#execute-composer-create-project).

### Problem
That recipe only works, if `--docroot` exactly is `public`. I need `public_html` however. If we leave out the parameter or give it a different value the recipe doesn't work. Assumed reason: Conflict between `ddev create` and the implicite `composer create`.

### Observed problematic behaviour
<pre>
[...]
Container ddev-router  Creating
Container ddev-router  Created
Container ddev-router  Starting
Container ddev-router  Started
TYPO3 does not seem to have been set up yet, missing LocalConfiguration.php (/home/marble/ddevprojects/dummy/public_html/typo3conf/LocalConfiguration.php)
Generating AdditionalConfiguration.php file for database connection.
Unable to create settings file '/home/marble/ddevprojects/dummy/public_html/typo3conf/LocalConfiguration.php': failed to write TYPO3 AdditionalConfiguration.php file: mkdir /home/marble/ddevprojects/dummy/public_html/typo3conf: no such file or directory
 </pre>

In effect `public_html/typo3conf/` is empty. There is no file `AdditionalConfiguration.php`.

### Expected Behavior

`public_html/typo3conf/AdditionalConfiguration.php` should be generated by `ddev` and be present for TYPO3 to be picked up. This works, if `--docroot=public`, but if doesn't work otherwise.

### Steps To Reproduce

How to replicate with ddev version v1.18.2

<pre>
# Create a directory for your project
mkdir example-project-directory

# Go into that directory
cd example-project-directory

# Tell DDEV to create a new project of type "typo3"
ddev config  --project-type=typo3 --docroot=public_html --create-docroot

# Start the ddev instance
ddev start

# Fetch a basic TYPO3 installation and its' dependencies
ddev composer create "typo3/cms-base-distribution:^11"  --no-install
</pre>

### Anything else?

See also:

Here is a working workaround I found that DOES work:
https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/issues/54#issuecomment-1066099907

But the goal must, of course be, to get `ddev create ...` going.

**Comment by rfay** [comment] 2022-03-14 13:14
I don't think this has to do with ddev does it? Isn't it the composer.json provided by packagist?

`ddev create` is just a wrapper on `composer create-project`, which downloads a composer.json from packagist. I think you'll have to use an updated composer.json if you want a different docroot. I'm not a composer expert, but I imagine this is what's going on.

@gilbertsoft I imagine you know the answer to this one. I wasn't able to figure out quickly how the docroot is set in TYPO3 composer build.

**Comment by marble** [comment] 2022-03-15 12:50
Ok, I went down another spirale into the rabbithole :-) And I still think, it's a DDEV thing.

### Proposal (mandatory): Make `--docroot=public` the default in DDEV

Currently the default value is the empty string. That makes it necessary to mention the `--docroot=public` setting in our DDEV recipes. That's ambiguous. It suggests, that it's an option that you can set at will. But you cannot. 

This should be an easy fix and eliminate my main concern. My main concern is, that even experienced developers, and especially those, will run into trouble and dump TYPO3 for that. Make `--docroot=public` the default. Then we don't need to mention that setting in our installation recipes and the biggest problem is solved.


### Suggestion (optional)

IMHO DDEV could and should be improved.

For understanding - what's currently going on: 

* `ddev config --project-type=typo3` creates `public/typo3conf/AdditionalConfiguration.php`.
* `ddev create` then deletes everything in `public`, including the previously built `AdditionalConfiguration.php`, or will stop
* composer is run in a tempdir
* the result is rsynced to the webroot
* `AdditionalConfiguration.php` for TYPO3 is created again if it's missing

#### The follwowing script is working

It is what I'm looking for, but it is "ugly".

With the following you can use `ddev create --no-install` and do the `ddev composer install` later.
And, you can give `public-root` a name you like. I'm presenting it as a script, so you can exactly see what I'm trying to achieve and demonstrate. I'm running the script top-down to set up project `~/ddevprojects/dummytest-project/dummytest/public_html`.

<pre>
PROJECT_FOLDER_NAME=dummytest
PROJECT=~/ddevprojects/${PROJECT_FOLDER_NAME}-project/${PROJECT_FOLDER_NAME}
HOST_TEMP_FOLDER=~/ddevprojects/${PROJECT_FOLDER_NAME}-project/GENERATED
PUBLIC_FOLDER=public_html
PORT_DIGITS=70

# http://dummy.ddev.site:8070
# http://dummy.ddev.site:44370

## Remove the project, in case it exists
true \
   &&  [[ ! -z "${PROJECT}" ]] \
   &&  ddev poweroff \
   &&  cd ${PROJECT}  \
   &&  ddev delete --omit-snapshot --yes \
   &&  cd ..  \
   &&  rm -rf ${PROJECT} \
   &&  rm -rf ${HOST_TEMP_FOLDER}

## Create project

## in the following the rsync is a workaround and should be made superflous
true \
   &&  [[ ! -z "${PROJECT}" ]] \
   &&  mkdir -p ${PROJECT} \
   &&  mkdir -p ${HOST_TEMP_FOLDER} \
   &&  cd ${PROJECT} \
   &&  ddev config \
       --auto \
       --project-name=${PROJECT_FOLDER_NAME} \
       --http-port=80${PORT_DIGITS} \
       --https-port=443${PORT_DIGITS} \
       --project-type=typo3 \
       --create-docroot \
       --docroot=${PUBLIC_FOLDER} \
   &&  rsync -av ${PUBLIC_FOLDER} ${HOST_TEMP_FOLDER}/ \
   &&  ddev composer create "typo3/cms-base-distribution:^10.4" --no-install
## ddev shouldn't stop with exitcode!=0 here

## In the following the `cp` is a workaround and should be made superflous
true \
   &&  ddev composer config "extra.typo3/cms.web-dir" ""${PUBLIC_FOLDER}"" \
   &&  ddev composer install \
   &&  cp "$HOST_TEMP_FOLDER/public_html/typo3conf/AdditionalConfiguration.php" "$PROJECT/$PUBLIC_FOLDER/typo3conf/" \
   &&  ddev exec "touch ${PUBLIC_FOLDER}/FIRST_INSTALL" \
   &&  ddev launch
</pre>

#### Nice: And this is what I get
![039](https://user-images.githubusercontent.com/307057/158380459-bc8b1814-29f7-4f41-a1a0-ce2a9e552b99.png)


#### What to improve

However:

* `ddev create ... --no-install` will cancel further execution with `editcode!=0`.
* I need to take care of saving and restoring of `AdditionalConfiguration.php` myself
* I'm seeing warnings and/or error messages.

What do you think?

**Comment by rfay** [comment] 2022-03-15 13:18
So... DDEV is not a TYPO3 tool, it's a general tool. The most common docroot historically for all PHP projects has been the project root. 

A standard TYPO3 composer built puts it in "public". A standard Drupal9 composer build puts it in "web". 

DDEV autodetects docroot on a project that's already built, but the problem is if the code isn't there yet. 

I hope you're understanding what the issues are.

**Comment by marble** [comment] 2022-03-15 15:51
> So... DDEV is not a TYPO3 tool, it's a general tool.

I totally understand that.

> I hope you're understanding what the issues are.

Sure, I do. 

But ddev knows about a `--project-type=typo3` (which is great). All I'm really asking for is that in that case it should use the equivalent of `--docroot=public` automatically. So I would NOT have to state `--docroot=public` in the `ddev config` line just to define the default value..

IMHO that small change makes a big difference when I try to convince somebody to use ddev. Because then I don't have to explain: "You know, ddev is a great tool, and it knows about how to set up a TYPO3 project. However, it doesn't know TYPO3's default web root folder, so that's why you have to name it. And, you have to know, that `public` is the only valid value you may use. Why? Well... " I'd very much like to avoid discussions of that kind.

**Comment by rfay** [comment] 2022-03-15 22:43
Yeah, DDEV doesn't know, or have any reasonable way to know, the behavior of the TYPO3 composer.json that you get with `composer create-project`. And since people can do any kind of `ddev composer create` they might want, not just a small set, and since they all have different behaviors, and different behaviors that vary over time... I don't think it's a solvable problem. You just have to understand how your own composer.json works. You may want to consider avoiding `ddev composer create` (`composer create-project`) completely in favor of custom composer.json that behave in a way you know what they're going to do.  (I'm not much of a fan of the magic `composer create-project` myself. I'd rather see a set of standard composer.json files that could easily be used as starters. 

I'm going to close this now, as I think you probably understand why DDEV can't solve the problem you're up against, but happy to continue the conversation here or elsewhere.

**Closed by rfay** 2022-03-15 22:43 UTC
