### ISSUE TITLE
The "Moving installation to project root" part of `ddev composer create` is very slow without mutagen or NFS

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3480] opened 2021-12-28 19:23 UTC
I'm not sure what the cause is, however I've found a major slowdown when using the Drupal 9 Quickstart Composer Setup example instructions. 

When I was using the previous version of DDEV, I would issue the 
`ddev composer create "drupal/recommended-project" `
command, and it would pull down the repo, and then say  "Moving installation to project root", and this step would take mere seconds, and I was on to the next step. I'm not sure what has changed, but since updating to 1.18.2, I issue the "create" command, it pulls the repo as quickly as ever, and gives me the "Congratulations" and "Next steps"  messages, and then it says
`Moving installation to project root`
and, no exaggeration, it takes 8-9 **minutes** to complete the move, and go on to where it stops/removes/recreates the containers. Once I get beyond that point, everything else is fine, but I have tried this several times, I have done `ddev poweroff` and restarted ddev, I have shut down Docker, power cycled the computer, none of it makes any difference. 

Am I the only one experiencing this issue? 

MacOS Catalina, Docker v. 4.3.2

**Comment by rfay** [comment] 2021-12-28 19:32
It means you should probably use mutagen for starters. Could be some regression in Docker I guess. Have you changed your settings regarding NFS, mutagen or regular mount? You didn't include the requested gist showing your settings, so I don't have a way to know the details I would usually ask. Maybe you could do that now? 

> 2. Please run a quick diagnostic and post the results as a new gist on gist.github.com (or on another pastebin-type site if you prefer). You can download [test_ddev.sh](https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh) and run it per the instructions at the top. That will help so we don't have to ask so many questions... And if it works, it probably means there's something wrong with your project, not ddev. Put the link to the gist here.

Are you able to demonstrate the difference by using the previous version of ddev (whatever it was)?  (See "How to install specific version of ddev at https://ddev.readthedocs.io/en/latest/users/faq/)

**Comment by begrafx** [comment] 2021-12-28 22:35
The only change was updating to the new version of DDEV. (well, Docker has had an update or two, but that doesn't seem to have any impact.) I have run the script you linked, the output is here:

https://gist.github.com/begrafx/eeea401abf56f7c3a60b2059288dca7f

**Comment by rfay** [comment] 2021-12-28 23:01
Thanks for the diagnostic, it helps keep me from asking so many questions. 

However, you didn't answer the other questions above:

* Have you changed your settings regarding NFS, mutagen or regular mount? (Which are you using?)
* Are you able to demonstrate the difference by using the previous version of ddev (whatever it was)? (See "How to install specific version of ddev at https://ddev.readthedocs.io/en/latest/users/faq/)

**Comment by begrafx** [comment] 2021-12-29 01:23
I haven't changed any settings on NFS, I was using regular mount when I posted the question and when I ran the diagnostic, I have since enabled mutagen on the "sanctuary" project. I have not yet gone back to the previous version in any way.  I've run a test install of a Drupal9 project, with Mutagen enabled the "Moving Installation to project root" process took about 4 minutes instead of the 8-9 it was. 

As I looked at stepping back to a previous version, I moved to 1.18.2, and I want to say that prior to that I was running 1.17.6 or 1.17.7. I don't recall specifically which. Looking over the releases list, I see that I did jump several releases. I'm not sure if that could somehow be an issue? I did `ddev poweroff` before updating. I'm wondering if perhaps I should Uninstall/reinstall, and see if that helps? Would that be wise/helpful?

**Comment by rfay** [comment] 2021-12-29 03:35
I don't think that uninstalling or reinstalling would have any effect. It looks like you have plenty of space in docker. 

I'm actually seeing it be very slow right now, but without nfs and without mutagen. Normally I use mutagen all the time globallly, but seem to have turned it off. 

It just took from 3m43.452s start to finish on a `ddev composer create drupal/recommended-project` with neither mutagen nor nfs on an M1 MBA.

I turned on mutagen and it took 40s start to finish and the "moving installation to project root" took 7s.

There was a change in how this works in a recent version - It used to do the composer install into a (mounted) subdirectory and them mv it into the main directory. Now it builds it (really fast) into /tmp, and then copies that into the (mounted) directory.

Please show a `ddev describe` for one of the projects you're working on. Does it show NFS?

**Comment by begrafx** [comment] 2021-12-29 03:40
Here's what it shows: 

`ddev describe
┌─────────────────────────────────────────────────────────────────────────────┐
│ Project: mutant ~/WebDev/mutant https://mutant.ddev.site                    │
├────────────┬──────┬──────────────────────────────────┬──────────────────────┤
│ SERVICE    │ STAT │ URL/PORT                         │ INFO                 │
├────────────┼──────┼──────────────────────────────────┼──────────────────────┤
│ web        │ OK   │ https://mutant.ddev.site         │ php PHP7.4           │
│            │      │ InDocker: ddev-mutant-web:443,80 │ nginx-fpm            │
│            │      │ ,8025                            │ docroot:'web'        │
│            │      │ Host: localhost:53117,53118      │ Mutagen enabled (ok) │
├────────────┼──────┼──────────────────────────────────┼──────────────────────┤
│ db         │ OK   │ InDocker: ddev-mutant-db:3306    │ MariaDB 10.3         │
│            │      │ Host: localhost:53113            │ User/Pass: 'db/db'   │
│            │      │                                  │ or 'root/root'       │
├────────────┼──────┼──────────────────────────────────┼──────────────────────┤
│ PHPMyAdmin │ OK   │ https://mutant.ddev.site:8037    │                      │
│            │      │ InDocker: ddev-mutant-dba:80,80  │                      │
│            │      │ `ddev launch -p`                 │                      │
├────────────┼──────┼──────────────────────────────────┼──────────────────────┤
│ Mailhog    │      │ MailHog: https://mutant.ddev.sit │                      │
│            │      │ e:8026                           │                      │
│            │      │ `ddev launch -m`                 │                      │
├────────────┼──────┼──────────────────────────────────┼──────────────────────┤
│ All URLs   │      │ https://mutant.ddev.site,        │                      │
│            │      │ https://127.0.0.1:53117,         │                      │
│            │      │ http://mutant.ddev.site,         │                      │
│            │      │ http://127.0.0.1:53118           │                      │
└────────────┴──────┴──────────────────────────────────┴──────────────────────┘
 
brianeller@Brians-Mac-mini mutant % 
`

**Comment by rfay** [comment] 2021-12-29 04:54
You never mentioned that you had upgraded macOS. What it says there is that you have mutagen enabled. So there's lots of apples and oranges going on here.

**Comment by begrafx** [comment] 2021-12-29 05:01
The upgrade to macOS was prior to the upgrade of DDEV. This issue (the time on moving installation to project root) didn't come up until the upgrade to DDEV 1.18.2. Mutagen was just enabled tonight, for the first time. That gist report that I sent was generated prior to enabling mutagen.

**Comment by rfay** [comment] 2021-12-29 22:46
I definitely agree that without NFS or mutagen the "moving to project root" is pretty painful. However, the part *before* the "moving to root" is far faster, because it takes place on a docker-native linux filesystem. That was the intent of the change, which was https://github.com/drud/ddev/pull/3226

My experience is that a plain `ddev composer create drupal/recommended-project` "moving to project root" takes about 40s with NFS, nearly 3m with no NFS and no mutagen, and 7s with mutagen. 

I'd be interested to know why you use `ddev composer create drupal/recommended-project` so often that it annoys you. I think for most people it's unusual.

I should note that you can easily change the whole process with
```
ddev composer create --no-install drupal/recommended-project -y
ddev composer require --no-install drush/drush
ddev composer install
```

It wouldn't surprise me if that's just an absolutely better workflow anyway.

**Comment by rfay** [comment] 2022-01-14 18:07
I'm in favor of changing all the recipes to use
`ddev composer create -n --no-install <project>`
like
``
ddev composer create -n --no-install drupal/recomended
ddev composer require -n "drush/drush:*"
ddev composer install
```

My bet is that your problem totally goes away. And I think it's cleaner overall than composer trying installs at every step.

I sure agree it's really, really slow right now without nfs or mutagen.

**Comment by rfay** [comment] 2022-01-15 19:37
I am changing this back to the way it used to be in https://github.com/drud/ddev/pull/3519, but I think you'll find that the *composer install* part is much slower as a result if you don't have NFS or mutagen. But I think the "copying" part will be faster.

I would be interested to know though: Why do you do this often, instead of having a standard base repo where you can just `ddev composer install` ?

**Comment by rfay** [comment] 2022-01-15 22:07
I tested the change I had in #3519, but it made the `composer install` part of `ddev composer create` so terribly slow that it was absolutely not worth it. I think you noticed in the end that the "moving to project root" was slow, but didn't notice how hugely much faster the composer install was. so closing this.

**Closed by rfay** 2022-01-15 22:07 UTC
